# -*- coding: utf-8 -*-
"""Articles du blog Qibla (français), contenu éditorial sur l'architecture islamique."""

ARTICLES = [
dict(
  slug="architecture-islamique-histoire-principes",
  titre="Qu'est-ce que l'architecture islamique ? Histoire et principes fondateurs",
  description="Origines, principes et grandes périodes de l'architecture islamique : de la mosquée du Prophète aux chefs-d'œuvre ottomans, moghols et contemporains.",
  date="2026-01-12",
  temps_lecture="7 min",
  eyebrow="Histoire",
  intro="On parle d'« architecture islamique » pour désigner un ensemble de traditions bâties, nées dans le monde musulman à partir du VIIe siècle, qui partagent des préoccupations communes (orienter le fidèle vers La Mecque, rassembler la communauté, orner sans représenter le vivant) tout en se transformant radicalement selon les époques et les régions.",
  corps=[
    ("Un point de départ : la mosquée du Prophète",
     "La première mosquée de l'histoire est de facto la maison du Prophète Muhammad à Médine, un enclos de terre battue entouré de huttes et ombragé de palmes. Cette forme simple, une cour, un mur orienté vers la qibla, un espace couvert pour la prière, restera la matrice de la mosquée dite « hypostyle », faite de rangées de colonnes soutenant une toiture plate, qu'on retrouve des siècles plus tard à la <a href=\"{RAC}mosquees/kairouan/index.html\">Grande Mosquée de Kairouan</a> ou dans la salle de prière de la <a href=\"{RAC}mosquees/cordoue/index.html\">mosquée-cathédrale de Cordoue</a>."),
    ("Des influences byzantines et perses",
     "Dès les conquêtes omeyyades puis abbassides, les bâtisseurs musulmans héritent des savoir-faire des civilisations qu'ils côtoient : la coupole et la maçonnerie de pierre de l'empire byzantin, l'art du décor et de la brique cuite de la Perse sassanide. La <a href=\"{RAC}mosquees/masjid-al-haram/index.html\">Masjid al-Haram</a> de La Mecque et la mosquée du Prophète à Médine ne cesseront d'ailleurs de s'agrandir au fil des dynasties, additionnant portiques, coupoles et minarets sans jamais renier leur fonction d'origine : entourer un lieu sacré."),
    ("L'apogée ottomane : la coupole comme signature",
     "À partir du XVe siècle, les architectes ottomans, Sinan en tête, perfectionnent l'art de la grande coupole centrale portée par des demi-coupoles en cascade, une prouesse structurelle directement inspirée de Sainte-Sophie. La <a href=\"{RAC}mosquees/mosquee-bleue/index.html\">Mosquée bleue</a> et la <a href=\"{RAC}mosquees/suleymaniye/index.html\">mosquée Süleymaniye</a> d'Istanbul illustrent cet équilibre entre monumentalité extérieure et intimité lumineuse intérieure, carrelée de céramiques d'Iznik."),
    ("Le monde persan et moghol : le règne du décor",
     "En Iran et en Asie du Sud, l'accent se déplace vers la parure : céramiques polychromes, muqarnas sculptés, vitraux colorés. La <a href=\"{RAC}mosquees/cheikh-lotfollah/index.html\">mosquée Cheikh Lotfollah</a> d'Ispahan ou la <a href=\"{RAC}mosquees/nasir-al-mulk/index.html\">mosquée Nasir al-Mulk</a> de Chiraz, surnommée « mosquée rose », transforment l'architecture en expérience presque picturale, où la lumière filtrée par le verre teinté devient un matériau de construction à part entière."),
    ("Une architecture toujours vivante",
     "Loin d'être figée dans le passé, l'architecture islamique continue de s'inventer : la <a href=\"{RAC}mosquees/hassan-ii/index.html\">mosquée Hassan II</a> de Casablanca marie décor traditionnel marocain et prouesses d'ingénierie contemporaine (son minaret culmine à plus de 200 mètres), tandis que la <a href=\"{RAC}mosquees/cheikh-zayed/index.html\">mosquée Cheikh Zayed</a> d'Abou Dabi assume un classicisme monumental en marbre blanc, pensé pour le XXIe siècle. D'une hutte de palmes à un vaisseau de marbre climatisé, le fil conducteur reste le même : bâtir un espace qui tourne la communauté vers un même point.")
  ],
  mosquees_liees=["kairouan", "cordoue", "mosquee-bleue", "suleymaniye", "hassan-ii"],
  photos=[
    dict(chemin="kairouan/photo-6.webp", description="Salle de prière hypostyle de la Grande Mosquée de Kairouan",
         source="Wikimedia Commons", auteur="Dennis G. Jarvis", licence="CC BY-SA 2.0",
         url="https://commons.wikimedia.org/wiki/File:Great_Mosque_of_Kairouan,_prayer_hall.jpg"),
    dict(chemin="hassan-ii/photo-3.webp", description="Vue d'ensemble de la mosquée Hassan II, Casablanca",
         source="Wikimedia Commons", auteur="Tinuzzo", licence="CC BY 4.0",
         url="https://commons.wikimedia.org/wiki/File:Hassan_II_Mosque_-_general_framing,_Casablanca,_Morocco.jpg"),
  ]
),
dict(
  slug="coupoles-minarets-symboles-mosquees",
  titre="Coupoles et minarets : pourquoi reconnaît-on une mosquée de loin ?",
  description="D'où viennent la coupole et le minaret, les deux éléments qui rendent une mosquée reconnaissable à des kilomètres ? Histoire et rôle de ces deux symboles architecturaux.",
  date="2026-01-19",
  temps_lecture="6 min",
  eyebrow="Architecture",
  intro="Silhouette caractéristique à l'horizon d'Istanbul, du Caire ou de Casablanca : la coupole et le minaret sont devenus, dans l'imaginaire collectif, les emblèmes visuels de la mosquée. Pourtant, ni l'une ni l'autre n'existaient à l'époque du Prophète : ce sont des ajouts progressifs, chargés d'histoire et de fonctions bien concrètes.",
  corps=[
    ("Le minaret, une tour pour l'appel à la prière",
     "Le mot « minaret » vient de l'arabe manāra, « qui donne de la lumière ». À l'origine, ces tours servaient parfois de phares ou de repères. Leur fonction s'est fixée autour de l'appel à la prière (adhan) : du haut du minaret, le muezzin devait porter sa voix le plus loin possible dans la ville. Les formes varient énormément selon les régions : minaret carré et trapu en Afrique du Nord (comme à la <a href=\"{RAC}mosquees/koutoubia/index.html\">Koutoubia</a> de Marrakech), tour-fusée effilée dans le monde ottoman, minaret-tronc de forme conique et spiralée à la <a href=\"{RAC}mosquees/kairouan/index.html\">Grande Mosquée de Kairouan</a>, l'un des plus anciens du monde islamique."),
    ("La coupole, un défi d'ingénieurs avant d'être un symbole",
     "La coupole n'a rien de spécifiquement islamique à l'origine : les Romains puis les Byzantins l'utilisaient déjà pour couvrir de grands espaces sans colonnes intermédiaires. Les architectes musulmans en héritent, notamment après la conquête de Constantinople, et en font l'élément central de la mosquée impériale ottomane. Techniquement, la coupole permet de couvrir une vaste salle de prière d'un seul tenant, sans piliers qui gêneraient l'alignement des rangs de fidèles, un vrai avantage liturgique autant qu'esthétique."),
    ("Des records d'ingénierie",
     "Certaines coupoles sont devenues de véritables prouesses techniques : celle de la <a href=\"{RAC}mosquees/cheikh-zayed/index.html\">mosquée Cheikh Zayed</a> d'Abou Dabi, en marbre blanc, compte parmi les plus grandes au monde ; le minaret de la <a href=\"{RAC}mosquees/hassan-ii/index.html\">mosquée Hassan II</a> de Casablanca, à plus de 200 mètres, est resté longtemps le plus haut du monde. À l'inverse, certaines grandes mosquées historiques comme celle de <a href=\"{RAC}mosquees/djenne/index.html\">Djenné</a>, bâtie en banco (terre crue), se passent presque entièrement de coupole : ses contreforts de bois (les toron) et sa silhouette pyramidale répondent à une autre contrainte, celle de la construction en terre en climat sahélien."),
    ("Deux symboles, une même fonction : orienter et rassembler",
     "Au-delà de la prouesse technique, coupole et minaret remplissent une fonction commune : signaler la présence de la communauté et organiser l'espace de la prière. Le minaret appelle et rassemble ; la coupole abrite et unifie le regard vers le mihrab, la niche qui indique la direction de La Mecque. Deux réponses architecturales différentes à une même exigence spirituelle.")
  ],
  mosquees_liees=["koutoubia", "kairouan", "cheikh-zayed", "hassan-ii", "djenne"],
  photos=[
    dict(chemin="koutoubia/photo-2.webp", description="Le minaret de la Koutoubia, Marrakech",
         source="Wikimedia Commons", auteur="Holger Uwe Schmitt", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:1158_wurde_die_Koutoubia-Moschee_in_Marrakesch_er%C3%B6fnet._01.jpg"),
    dict(chemin="cheikh-zayed/photo-10.webp", description="Coupoles de marbre blanc de la mosquée Cheikh Zayed, Abou Dabi",
         source="Wikimedia Commons", auteur="Francesco Bini", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Abu_dhabi,_Moschea_dello_Sceicco_Zayed,_aula_di_preghiera,_01.jpg"),
  ]
),
dict(
  slug="muqarnas-motifs-geometriques-art-islamique",
  titre="Muqarnas et motifs géométriques : les secrets mathématiques de l'art islamique",
  description="Étoiles à huit branches, entrelacs et muqarnas en nid d'abeille : comment les artisans de l'art islamique ont transformé la géométrie en décor sacré, sans jamais représenter de figure vivante.",
  date="2026-01-26",
  temps_lecture="6 min",
  eyebrow="Décor",
  intro="Aucune figure humaine ou animale sur les murs d'une mosquée : cette retenue, souvent résumée (un peu vite) sous le terme d'« aniconisme », a poussé les artisans du monde islamique à développer l'un des langages ornementaux les plus sophistiqués de l'histoire de l'art, fondé sur la géométrie, la calligraphie et la répétition infinie du motif.",
  corps=[
    ("Le girih, ou l'art de l'entrelacs",
     "Le girih (« nœud » en persan) désigne ces réseaux de lignes entrelacées qui composent étoiles à six, huit ou seize branches, polygones et rosaces enchevêtrés à l'infini. Construits à la règle et au compas à partir de figures géométriques simples, ces motifs peuvent pourtant produire des compositions d'une complexité redoutable : des chercheurs ont montré en 2007 que certains décors du XVe siècle, comme ceux de la mosquée-madrasa de Darb-i Imam en Iran, préfiguraient des pavages quasi-périodiques que les mathématiques occidentales ne formaliseront (avec les pavages de Penrose) que cinq siècles plus tard."),
    ("Le muqarnas, sculpter la lumière en nid d'abeille",
     "Le muqarnas est une structure en alvéoles superposées, un peu comme des stalactites de plâtre, de bois ou de pierre, utilisée pour habiller la transition entre un mur droit et une coupole ronde, ou pour orner un portail, une niche, un plafond. Chaque alvéole capte et diffuse la lumière différemment selon l'heure du jour, créant un jeu d'ombres changeant. Les muqarnas de la <a href=\"{RAC}mosquees/cheikh-lotfollah/index.html\">mosquée Cheikh Lotfollah</a> d'Ispahan ou ceux qui ornent nombre de portails en Afrique du Nord et au Moyen-Orient comptent parmi les sommets de cet art."),
    ("La calligraphie, un décor qui se lit",
     "Troisième pilier du décor islamique : l'écriture elle-même. Versets coraniques, noms de Dieu ou de son prophète sont stylisés en frises coufiques anguleuses ou en cursives fluides, intégrées aux frises géométriques au point de devenir, pour l'œil non-arabophone, un motif abstrait de plus. Cette fusion entre texte sacré et ornement est particulièrement spectaculaire dans les céramiques polychromes des mosquées ottomanes et persanes, comme celles qui recouvrent l'intérieur de la <a href=\"{RAC}mosquees/mosquee-bleue/index.html\">Mosquée bleue</a> d'Istanbul."),
    ("La lumière colorée, un matériau à part entière",
     "Dans le monde persan, un quatrième langage décoratif s'ajoute aux trois précédents : le vitrail. À la <a href=\"{RAC}mosquees/nasir-al-mulk/index.html\">mosquée Nasir al-Mulk</a> de Chiraz, des kilomètres de verre coloré projettent, chaque matin, des taches de lumière arc-en-ciel sur les tapis de la salle de prière, un rappel que dans l'art islamique, le décor n'est jamais un simple habillage : il transforme l'expérience même de l'espace sacré.")
  ],
  mosquees_liees=["cheikh-lotfollah", "mosquee-bleue", "nasir-al-mulk"],
  photos=[
    dict(chemin="cheikh-lotfollah/photo-9.webp", description="Motifs et muqarnas de la mosquée Cheikh Lotfollah, Ispahan",
         source="Wikimedia Commons", auteur="Monaesfandiar", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:4R9A7644.jpg"),
    dict(chemin="nasir-al-mulk/photo-6.webp", description="Vitraux colorés de la mosquée Nasir al-Mulk, Chiraz",
         source="Wikimedia Commons", auteur="dynamosquito from France", licence="CC BY-SA 2.0",
         url="https://commons.wikimedia.org/wiki/File:A_touch_of_paradise_(2470492244).jpg"),
  ]
),
dict(
  slug="mosquees-malaisie-architecture-moderne",
  titre="Les mosquées de Malaisie : entre tradition malaise et modernisme spectaculaire",
  description="De la Mosquée Nationale à la mosquée Putra, comment la Malaisie a fait de ses mosquées des manifestes architecturaux depuis son indépendance.",
  date="2026-02-02",
  temps_lecture="6 min",
  eyebrow="Asie du Sud-Est",
  intro="Peu de pays ont autant fait de leurs mosquées des symboles d'identité nationale que la Malaisie. Depuis l'indépendance en 1957, chaque grande mosquée y est aussi un manifeste architectural, mêlant héritage malais, influences moyen-orientales et modernisme assumé.",
  corps=[
    ("La Mosquée Nationale, un manifeste d'indépendance",
     "Achevée en 1965, la Masjid Negara (Mosquée Nationale) de Kuala Lumpur est pensée dès l'origine comme le symbole architectural d'une nation tout juste indépendante. Sa toiture principale, un parapluie plissé à 18 pointes, ne cherche pas à imiter une coupole traditionnelle : elle évoque à la fois une fleur épanouie et le pliage d'un umbrella cérémoniel malais, tout en comptant symboliquement les treize États de la fédération et les cinq piliers de l'islam. Son minaret élancé, en forme de fusée à ailerons, tranche radicalement avec les tours ottomanes ou mogholes."),
    ("La mosquée Putra, entre lac et granit rose",
     "À Putrajaya, ville administrative construite à la fin des années 1990, la <a href=\"{RAC}mosquees/putra/index.html\">mosquée Putra</a> pousse plus loin le mélange des influences : dôme et minaret inspirés de l'Iran et de l'Asie centrale, mais construction en granit rose local et implantation en grande partie sur un lac artificiel, résolument contemporaine."),
    ("La Mosquée bleue de Shah Alam, un gabarit hors normes",
     "Non loin de Kuala Lumpur, la mosquée du Sultan Salahuddin Abdul Aziz à Shah Alam, surnommée « Mosquée bleue » pour son immense dôme turquoise, l'un des plus grands du monde, illustre une autre tendance : la course au gigantisme, avec une capacité dépassant parfois les 24 000 fidèles, portée par les moyens d'un État pétrolier régional."),
    ("Un vocabulaire propre à l'Asie du Sud-Est",
     "Avant l'arrivée de ces grands programmes officiels, l'architecture mosquée malaise puisait dans un vocabulaire vernaculaire très différent : toitures étagées en tuiles, charpentes de bois, influences chinoises et indiennes issues des routes commerciales. Ce fonds vernaculaire n'a pas disparu : on le retrouve encore dans de nombreuses petites mosquées de villages (kampung), en contrepoint des géants de béton et de granit des grandes villes.")
  ],
  mosquees_liees=["putra"],
  photos=[
    dict(chemin="blog/mosquees-malaisie-architecture-moderne/photo-1.webp", description="La Mosquée Nationale de Malaisie (Masjid Negara), Kuala Lumpur",
         source="Wikimedia Commons", auteur="Marcin Konsek", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:2016_Kuala_Lumpur,_Meczet_Narodowy_Malezji_(02).jpg"),
    dict(chemin="putra/photo-2.webp", description="La mosquée Putra et son dôme de granit rose, Putrajaya",
         source="Wikimedia Commons", auteur="Ariff Shah Sopian", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Putra_Mosque,_Putrajaya.jpg"),
  ]
),
dict(
  slug="mosquees-algerie-heritage-ottoman-contemporain",
  titre="Les mosquées d'Algérie : de l'héritage ottoman au plus haut minaret d'Afrique",
  description="De la mosquée Ketchaoua d'Alger, façonnée par trois régimes successifs, à Djamaâ El Djazaïr et son minaret record, panorama de l'architecture mosquée en Algérie.",
  date="2026-02-09",
  temps_lecture="6 min",
  eyebrow="Maghreb",
  intro="L'Algérie concentre, sur un même territoire, l'un des plus vieux sanctuaires almoravides du Maghreb et l'un des plus jeunes records architecturaux du monde musulman : un minaret de 265 mètres, achevé en 2019. Entre les deux, des siècles d'allers-retours entre pouvoirs ottoman, colonial et national.",
  corps=[
    ("Ketchaoua, une mosquée à trois vies",
     "Peu d'édifices religieux ont connu un destin aussi mouvementé que la mosquée Ketchaoua, dans la Casbah d'Alger. Construite (ou largement reconstruite) à l'époque ottomane au XVIIIe siècle, elle est transformée en cathédrale après la prise d'Alger par la France en 1830 : ses deux minarets sont alors surmontés de clochers. À l'indépendance en 1962, l'édifice redevient une mosquée. Ses portes sculptées et ses colonnes de marbre témoignent aujourd'hui de ces strates successives, ottomane, coloniale, puis à nouveau religieuse musulmane."),
    ("La Grande Mosquée d'Alger, doyenne almoravide",
     "Alger conserve aussi un patrimoine bien plus ancien : la Grande Mosquée (Djamaa al-Kebir), dont le noyau daterait du XIe siècle, sous la dynastie almoravide, ce qui en fait l'une des plus anciennes mosquées encore en activité du Maghreb central. Sa salle de prière à colonnades et son minaret sobre, ajouté au XVIe siècle, rappellent la sobriété des débuts de l'architecture mosquée nord-africaine, avant les grands décors des siècles suivants."),
    ("Djamaâ El Djazaïr, un record contemporain",
     "À l'autre extrémité de la chronologie, Djamaâ El Djazaïr (« la Grande Mosquée d'Alger »), inaugurée en 2019 sur le front de mer, revendique le troisième rang mondial par sa capacité d'accueil et le minaret le plus haut d'Afrique, culminant à 265 mètres. Ses galeries d'arcades continues sur plusieurs centaines de mètres et sa salle de prière conçue pour résister aux séismes en font un manifeste d'ingénierie autant que de foi, à l'échelle des grands projets contemporains du Golfe."),
    ("Une architecture de transition, entre Maghreb et Méditerranée",
     "Entre ces extrêmes chronologiques, l'Algérie a aussi hérité de mosquées ottomanes plus modestes dans les grandes villes côtières (Alger, Constantine, Annaba), reconnaissables à leurs dômes trapus et à leurs minarets octogonaux proches des modèles turcs, une signature que l'on retrouve autour de toute la Méditerranée ottomane, de Tunis à Sarajevo.")
  ],
  mosquees_liees=[],
  photos=[
    dict(chemin="blog/mosquees-algerie-heritage-ottoman-contemporain/photo-1.webp", description="Djamaâ El Djazaïr (Grande Mosquée d'Alger) et son minaret de 265 mètres",
         source="Wikimedia Commons", auteur="Rachid Hamatou", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Djama%C3%A2_El_Djaza%C3%AFr_%E2%80%93_The_Great_Mosque_of_Algiers_1.jpg"),
    dict(chemin="blog/mosquees-algerie-heritage-ottoman-contemporain/photo-2.webp", description="Les minarets ottomans de la mosquée Ketchaoua, Alger",
         source="Wikimedia Commons", auteur="Dan Sloan", licence="CC BY-SA 2.0",
         url="https://commons.wikimedia.org/wiki/File:20141113-_DSC0096-3_(15887428745).jpg"),
  ]
),
dict(
  slug="mosquees-maroc-tradition-almohade",
  titre="Les mosquées du Maroc : de la doyenne de Fès aux prouesses de Casablanca",
  description="D'Al Quaraouiyine, plus ancienne université du monde selon l'UNESCO, à la mosquée Hassan II : panorama de la tradition mosquée marocaine, almohade puis contemporaine.",
  date="2026-02-16",
  temps_lecture="6 min",
  eyebrow="Maghreb",
  intro="Le Maroc n'a jamais cessé de bâtir des mosquées depuis le IXe siècle, sans jamais rompre totalement avec son vocabulaire almohade (toits de tuiles vertes, arcs outrepassés, zelliges géométriques) que l'on retrouve autant dans la doyenne de Fès que dans le géant contemporain de Casablanca.",
  corps=[
    ("Al Quaraouiyine, une mosquée devenue université millénaire",
     "Fondée en 859 à Fès par Fatima al-Fihriya, une riche héritière, la mosquée Al Quaraouiyine abrite l'une des plus anciennes institutions d'enseignement encore en activité au monde, reconnue comme telle par l'UNESCO et le Livre Guinness des records. Agrandie sur plus d'un millénaire, elle conserve un plan hypostyle typique des débuts de l'architecture mosquée nord-africaine, avec cour à bassins et salle de prière profonde soutenue par des arcades en fer à cheval."),
    ("L'empreinte almohade : la Koutoubia comme modèle",
     "Aux XIIe et XIIIe siècles, la dynastie almohade impose dans tout le Maghreb et al-Andalus un vocabulaire commun : minaret carré massif, décor d'arcs entrelacés en pierre sculptée, toiture de tuiles vertes vernissées. La <a href=\"{RAC}mosquees/koutoubia/index.html\">Koutoubia</a> de Marrakech en est l'exemple le plus abouti, et son influence se lit directement dans la Giralda de Séville ou la tour Hassan de Rabat, bâties à la même époque par les mêmes ateliers."),
    ("Tin Mal, le sanctuaire fondateur dans l'Atlas",
     "Loin des grandes villes, la mosquée de Tin Mal, isolée dans les montagnes du Haut Atlas, marque le berceau spirituel du mouvement almohade : c'est ici que son fondateur, Ibn Toumert, établit sa base avant la conquête de Marrakech. Dépouillée d'ornements superflus, l'édifice frappe par la pureté de ses volumes et reste, huit siècles plus tard, un lieu de pèlerinage architectural pour comprendre l'origine du style almohade."),
    ("Hassan II, la synthèse contemporaine",
     "Achevée en 1993 à Casablanca, la <a href=\"{RAC}mosquees/hassan-ii/index.html\">mosquée Hassan II</a> reprend consciemment ce vocabulaire almohade (zelliges, plâtres ciselés, toit de tuiles vertes) à une échelle inédite, avec un minaret dépassant 200 mètres et une salle de prière au toit ouvrant, bâtie en partie sur l'océan Atlantique. Une manière d'affirmer que la tradition mosquée marocaine, huit siècles après Tin Mal, reste une architecture vivante plutôt qu'un style figé.")
  ],
  mosquees_liees=["koutoubia", "hassan-ii"],
  photos=[
    dict(chemin="koutoubia/photo-9.webp", description="La Koutoubia et son décor almohade, Marrakech",
         source="Wikimedia Commons", auteur="Samuel Romero", licence="CC BY 3.0",
         url="https://commons.wikimedia.org/wiki/File:A_Place_To_Pray_(260498733).jpeg"),
    dict(chemin="hassan-ii/photo-8.webp", description="Zelliges et plâtres ciselés de la mosquée Hassan II, Casablanca",
         source="Wikimedia Commons", auteur="Walaadari", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Maroc,_Mosqu%C3%A9e_Hassan_2,_Grand_Casablanca_2.jpg"),
  ]
),
dict(
  slug="plus-belle-plus-grande-mosquee-tunisie",
  titre="La Zitouna et Malek Ibn Anas : les plus belles et plus grandes mosquées de Tunisie",
  description="Zitouna, la doyenne millénaire de la médina de Tunis, et Malek Ibn Anas, le géant contemporain de Carthage : deux façons de répondre à la question « quelle est la plus grande mosquée de Tunisie ? »",
  date="2026-02-23",
  temps_lecture="6 min",
  eyebrow="Maghreb",
  intro="Poser la question de « la plus belle et la plus grande mosquée de Tunisie » revient en réalité à en désigner deux : la mosquée Zitouna, cœur spirituel et intellectuel de la médina de Tunis depuis plus de treize siècles, et la mosquée Malek Ibn Anas, géant contemporain de Carthage qui détient aujourd'hui le record de capacité du pays.",
  corps=[
    ("Zitouna, « l'olivier » au cœur de la médina",
     "Fondée à la toute fin du VIIe siècle et considérablement agrandie sous les Aghlabides au IXe siècle, la Grande Mosquée Zitouna (« mosquée de l'olivier ») est la plus ancienne mosquée de Tunis et l'une des plus vastes du pays, avec près de 5 000 m² au cœur de la médina classée à l'UNESCO. Sa salle de prière hypostyle, portée par plus de 160 colonnes antiques réemployées (marbre, granit, porphyre), et son minaret carré de style almohade en font l'un des monuments les plus photographiés de Tunisie."),
    ("Une université presque aussi vieille que la mosquée",
     "Comme Al Quaraouiyine à Fès ou Al-Azhar au Caire, Zitouna n'est pas seulement un lieu de culte : dès le VIIIe siècle, on y enseigne le droit, la grammaire et les sciences religieuses, ce qui en fait l'un des plus anciens foyers d'enseignement supérieur du monde musulman. Cette double vocation, spirituelle et savante, a irrigué toute l'histoire intellectuelle tunisienne jusqu'à la création de l'université Zitouna moderne, qui perpétue cet héritage."),
    ("Malek Ibn Anas, le nouveau record de capacité",
     "À une vingtaine de kilomètres de là, sur la colline de Carthage, la mosquée Malek Ibn Anas, aussi connue sous le nom de mosquée El Abidine, est aujourd'hui la plus grande mosquée de Tunisie par sa capacité d'accueil, de l'ordre de plusieurs dizaines de milliers de fidèles esplanade comprise. Achevée au début des années 2000, elle reprend le vocabulaire almohade classique (arcs outrepassés, minaret élancé, portails sculptés) à une échelle monumentale, dans la lignée des grandes mosquées nationales bâties ailleurs dans le Maghreb au tournant du XXIe siècle."),
    ("Deux réponses à une même question",
     "Zitouna l'emporte sur l'ancienneté, le rayonnement intellectuel et la densité patrimoniale ; Malek Ibn Anas l'emporte sur la superficie et la capacité d'accueil. Plutôt qu'un classement, les deux édifices racontent la même histoire sous deux angles : celle d'un pays qui n'a jamais cessé de bâtir des mosquées, du VIIe siècle à aujourd'hui, sans rompre avec son vocabulaire architectural nord-africain (arcs en fer à cheval, minarets carrés, portails sculptés) hérité de Kairouan et transmis de génération en génération de bâtisseurs.")
  ],
  mosquees_liees=["kairouan"],
  photos=[
    dict(chemin="blog/mosquees-tunisie-zitouna-malik-ibn-anas/photo-1.webp", description="Cour intérieure et minaret de la Grande Mosquée Zitouna, Tunis",
         source="Wikimedia Commons", auteur="Noomen9", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Minaret_zitouna_(44957).jpg"),
    dict(chemin="blog/mosquees-tunisie-zitouna-malik-ibn-anas/photo-2.webp", description="Façade et minaret illuminés de la mosquée Malek Ibn Anas, Carthage",
         source="Wikimedia Commons", auteur="Gharbi Ryadh", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:Grande_mosqu%C3%A9e_Anas_Ibn_Malak_de_Carthage.jpg"),
  ]
),
dict(
  slug="top-3-plus-belles-mosquees-malaisie",
  titre="Top 3 des plus belles mosquées de Malaisie",
  description="Masjid Kristal, mosquée Putra et Masjid Negara : notre sélection des trois mosquées les plus spectaculaires de Malaisie, entre verre, granit rose et modernisme des années 1960.",
  date="2026-03-02",
  temps_lecture="8 min",
  eyebrow="Classement",
  intro="Difficile de choisir tant la Malaisie a multiplié, depuis son indépendance, les mosquées-manifestes. Voici néanmoins notre sélection des trois plus spectaculaires, du verre flottant de Terengganu au granit rose de Putrajaya, avec pour chacune l'histoire, les chiffres et les détails qui justifient sa place sur ce podium.",
  corps=[
    ("#1, Masjid Kristal, la mosquée de verre flottante",
     "À Kuala Terengganu, capitale de l'État du Terengganu sur la côte est de la péninsule malaise, la Masjid Kristal (« mosquée de cristal ») occupe la première place pour une raison simple : c'est l'une des seules mosquées au monde bâtie presque entièrement en verre, en acier et en aluminium, posée sur une plateforme qui semble flotter à la confluence de la rivière Terengganu et de la mer de Chine méridionale. Construite sur l'île de Wan Man, inaugurée en février 2008 par le sultan de l'État, elle constitue la pièce maîtresse du Parc de la civilisation islamique (Taman Tamadun Islam), un vaste complexe qui présente, sur cette même île, des répliques à échelle réduite d'une vingtaine de monuments islamiques célèbres à travers le monde, de la Kaaba au Taj Mahal. "
     "Sa structure d'acier et de verre feuilleté, plutôt qu'une maçonnerie traditionnelle, lui permet un tour de force que ni la pierre ni le béton ne pourraient offrir : changer littéralement d'apparence selon l'heure et la météo. Dorée et cuivrée au lever et au coucher du soleil, elle vire à l'argenté sous le plein soleil de midi et se pare, la nuit venue, d'un jeu de lumières LED programmables qui colorent tour à tour dômes et minarets. Sa position, presque entièrement entourée d'eau, ajoute un effet miroir quasi permanent qu'aucune autre grande mosquée d'Asie du Sud-Est ne reproduit à cette échelle. Elle peut accueillir environ 1 500 fidèles, un gabarit modeste comparé aux deux mosquées suivantes de ce classement, compensé par une identité visuelle qu'aucune autre mosquée du pays ne revendique."),
    ("#2, La mosquée Putra, le granit rose sur le lac",
     "À <a href=\"{RAC}mosquees/putra/index.html\">Putrajaya</a>, ville administrative fédérale construite de toutes pièces à la fin des années 1990 pour désengorger Kuala Lumpur, la mosquée Putra doit sa place sur ce podium à un choix de matériau aussi simple que radical : un dôme et des murs en granit rose, une teinte que l'on ne retrouve dans aucune autre grande mosquée d'Asie du Sud-Est, directement inspirée des camaïeux de rose de la mosquée du Cheikh Lotfollah et d'autres édifices persans safavides. Achevée en 1999, elle peut accueillir environ 15 000 fidèles répartis entre la salle de prière et l'esplanade, et se dresse aux trois quarts au-dessus du lac artificiel de Putrajaya, creusé spécialement pour donner à la nouvelle capitale administrative un visage monumental. "
     "Son minaret, qui culmine à 116 mètres, l'un des plus hauts d'Asie du Sud-Est, est structuré en cinq sections distinctes, un découpage qui symbolise les cinq piliers de l'islam ; l'ensemble du complexe, avec sa grande cour à arcades et ses portes sculptées, assume un mélange revendiqué d'influences moyen-orientales (perse et moyen-orientale pour le vocabulaire décoratif) et malaises (dans les proportions générales et certains détails de toiture). Elle est aujourd'hui l'une des mosquées les plus visitées du pays, notamment en raison de sa proximité avec le complexe du Premier ministre et les administrations fédérales qui l'entourent."),
    ("#3, Masjid Negara, le manifeste de l'indépendance",
     "La Mosquée nationale de Kuala Lumpur ferme ce podium, non pas pour son ancienneté au sens absolu (elle date de 1965, quand plusieurs mosquées de ce site remontent à plusieurs siècles) mais pour sa radicalité formelle. Inaugurée le 27 août 1965, moins de dix ans après l'indépendance de la Malaisie (1957), elle est conçue dès l'origine comme un symbole national plutôt que comme une simple mosquée de quartier : sa toiture principale, un parapluie de béton plissé à 18 pointes, rompt délibérément avec la coupole hémisphérique traditionnelle du monde ottoman ou moghol, et son minaret en forme de fusée à ailerons, haut de 73 mètres, reste, soixante ans après son inauguration, l'une des silhouettes les plus reconnaissables de toute l'architecture mosquée du XXe siècle. "
     "Le chiffre 18 n'est pas arbitraire : il additionne les treize États fédérés de la Malaisie et les cinq piliers de l'islam. Le complexe, qui peut accueillir environ 15 000 fidèles, s'étend sur près de 5 hectares de jardins et de bassins réfléchissants, sur le site de l'ancien terrain de polo du Selangor Turf Club en plein cœur de la capitale. Le projet, mené par une équipe d'architectes britanniques et malaisiens réunis pour l'occasion, a volontairement cherché à s'affranchir des références ottomanes ou mogholes alors dominantes dans l'imagerie mondiale de la mosquée, pour proposer un vocabulaire propre, une démarche que l'on retrouvera, des décennies plus tard, dans la mosquée Putra puis la Masjid Kristal."),
    ("Des critères forcément subjectifs",
     "Ce classement reste évidemment une question de goût : la « Mosquée bleue » de Shah Alam (mosquée du Sultan Salahuddin Abdul Aziz), avec l'un des plus grands dômes du monde et une capacité dépassant parfois les 24 000 fidèles, ou la doyenne Masjid Kampung Kling à Malacca, un rare exemple de mosquée malaisienne au toit étagé de style pagode chinoise datant du XVIIIe siècle, auraient tout aussi bien mérité leur place. Mais Masjid Kristal, Putra et Negara ont ceci de commun qu'elles illustrent, chacune à sa manière et à une génération d'écart (1965, 1999, 2008), la même ambition constante depuis l'indépendance : faire de la mosquée malaisienne un manifeste architectural et une affirmation d'identité nationale, plutôt qu'une simple reproduction des modèles importés du Moyen-Orient.")
  ],
  mosquees_liees=["putra"],
  photos=[
    dict(chemin="blog/top-3-plus-belles-mosquees-malaisie/photo-1.webp", nom="Masjid Kristal", description="La Masjid Kristal (mosquée de cristal) flottant sur l'eau, Kuala Terengganu",
         source="Wikimedia Commons", auteur="DestinationFearFan", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Crystal_Mosque_in_Kuala_Terengganu_Malaysia.jpg"),
    dict(chemin="blog/top-3-plus-belles-mosquees-malaisie/photo-2.webp", nom="Masjid Kristal", description="Vue aérienne de la Masjid Kristal sur la rivière Terengganu",
         source="Wikimedia Commons", auteur="Saha 165", licence="CC BY 3.0",
         url="https://commons.wikimedia.org/wiki/File:Crystal_Mosque_Aerial_Shot_1.jpg"),
    dict(chemin="blog/top-3-plus-belles-mosquees-malaisie/photo-3.webp", nom="Masjid Kristal", description="Intérieur du dôme de verre et lustre central de la Masjid Kristal",
         source="Wikimedia Commons", auteur="Azuladnan", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Crystal_Mosque_Interior.jpg"),
    dict(chemin="putra/photo-2.webp", nom="Mosquée Putra", description="La mosquée Putra et son dôme de granit rose, Putrajaya",
         source="Wikimedia Commons", auteur="Muhammad Faqih", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Masjid_Putra,_Putrajaya.jpg"),
    dict(chemin="putra/photo-3.webp", nom="Mosquée Putra", description="Intérieur de la grande salle de prière de la mosquée Putra",
         source="Wikimedia Commons", auteur="Slices of Light", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Masjid_Putra_-_Main_Prayer_Hall.jpg"),
    dict(chemin="putra/photo-4.webp", nom="Mosquée Putra", description="Le minaret à cinq étages de la mosquée Putra",
         source="Wikimedia Commons", auteur="Slices of Light", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Putra_Mosque_Spire.jpg"),
    dict(chemin="blog/top-3-plus-belles-mosquees-malaisie/photo-4.webp", nom="Masjid Negara", description="Le minaret en forme de fusée de la Masjid Negara, Kuala Lumpur",
         source="Wikimedia Commons", auteur="Non spécifié (domaine public, CC0)", licence="CC0",
         url="https://commons.wikimedia.org/wiki/File:20190822_National_Mosque_of_Malaysia_minaret-1.jpg"),
    dict(chemin="blog/top-3-plus-belles-mosquees-malaisie/photo-5.webp", nom="Masjid Negara", description="Cour à bassins et bâtiments annexes de la Masjid Negara",
         source="Wikimedia Commons", auteur="Non spécifié (domaine public, CC0)", licence="CC0",
         url="https://commons.wikimedia.org/wiki/File:20190822_National_Mosque_of_Malaysia_fountain-1.jpg"),
    dict(chemin="blog/mosquees-malaisie-architecture-moderne/photo-1.webp", nom="Masjid Negara", description="La toiture en étoile plissée à 18 pointes de la Masjid Negara",
         source="Wikimedia Commons", auteur="Marcin Konsek", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:2016_Kuala_Lumpur,_Meczet_Narodowy_Malezji_(02).jpg"),
  ]
),
dict(
  slug="mosquees-insolites-architecture-hors-normes",
  titre="6 mosquées insolites qui sortent des sentiers battus",
  description="Terre crue, 99 coupoles, dôme en or, mosquée enterrée dans une colline : six lieux de culte qui prouvent que l'architecture mosquée ne se résume pas au dôme et au minaret classiques.",
  date="2026-03-09",
  temps_lecture="7 min",
  eyebrow="Insolite",
  intro="Pas de dôme, pas de minaret, une couleur qui détonne ou un matériau improbable : ces six mosquées ont en commun de rompre, chacune à sa façon, avec l'image la plus attendue de l'architecture mosquée. Deux figurent déjà parmi nos 20 mosquées incontournables ; les quatre autres méritaient elles aussi le détour.",
  corps=[
    ("La Grande Mosquée de Djenné, une ville entière en terre crue",
     "Impossible de parler d'insolite sans commencer par <a href=\"{RAC}mosquees/djenne/index.html\">Djenné</a>, au Mali : c'est tout simplement le plus grand édifice en terre crue (banco) du monde. Chaque année, avant la saison des pluies, toute la ville participe au « crépissage », une fête collective où l'on ré-enduit les murs de terre fraîche à mains nues. Les torons de palmier qui hérissent la façade ne sont pas décoratifs : ce sont des échafaudages permanents, plantés dans le mur, qui permettent cet entretien annuel indispensable à la survie du bâtiment."),
    ("La Grande Mosquée de Xi'an, sans dôme ni minaret",
     "À l'autre extrême esthétique, la <a href=\"{RAC}mosquees/xian/index.html\">Grande Mosquée de Xi'an</a>, en Chine, ne ressemble à aucune autre mosquée du monde : ni dôme, ni minaret visibles, mais une succession de cours et de pavillons de bois aux toitures incurvées, strictement identiques dans leur composition aux temples chinois traditionnels. Seule l'orientation est-ouest de son axe, contraire aux temples chinois classiques orientés nord-sud, trahit sa fonction : elle pointe vers La Mecque."),
    ("La mosquée aux 99 coupoles de Makassar",
     "En Indonésie, la mosquée Al-Asmaul Husna, plus connue sous le nom de « mosquée aux 99 coupoles » (Masjid 99 Kubah), pousse un symbole islamique jusqu'à l'extrême architectural : son toit est littéralement composé de 99 petites coupoles, une pour chacun des 99 noms attribués à Dieu dans la tradition musulmane (les Asmaul Husna). Construite sur un terre-plein gagné sur la mer à Makassar, dans le sud de l'île de Sulawesi, vue de l'intérieur, la coupole centrale forme une étoile éclatante entourée de ce chapelet de mini-dômes, un motif que l'on ne retrouve dans aucune autre mosquée au monde."),
    ("La mosquée au dôme d'or de Depok",
     "Toujours en Indonésie, la mosquée Dian Al-Mahri, surnommée « mosquée au dôme d'or » (Masjid Kubah Emas), assume un autre genre de démesure : ses coupoles sont recouvertes de plaques d'or véritable. Financée par une fondation privée et inaugurée en 2006 dans la banlieue de Depok, près de Jakarta, elle est devenue l'un des monuments religieux les plus photographiés du pays, visible de loin grâce à l'éclat de ses dômes dorés qui tranche avec le vert et le blanc habituels des grandes mosquées d'Asie du Sud-Est."),
    ("La mosquée creusée dans une colline, en Turquie",
     "Près d'Istanbul, la mosquée de Sancaklar prend le contre-pied total de l'imagerie classique : conçue par l'architecte Emre Arolat et achevée en 2012, elle est littéralement enfouie dans le flanc d'une colline, sans dôme ni minaret traditionnel : seule une fine colonne de pierre, à peine plus haute qu'un lampadaire, en tient lieu. À l'intérieur, la lumière filtre depuis une fente au sommet du volume, dans une ambiance minérale presque monacale. Le projet a été distingué par l'un des plus prestigieux prix internationaux d'architecture, l'Aga Khan Award for Architecture."),
    ("La mosquée au plafond étoilé de Dhaka",
     "À Dhaka, capitale du Bangladesh, la mosquée Bait ur Rouf, conçue par l'architecte Marina Tabassum et achevée en 2012, renonce elle aussi au dôme et au minaret : un simple cylindre de brique nue, financé par une donatrice privée sur un terrain modeste de quartier. Sa prouesse se cache au plafond : des puits de lumière circulaires percent la voûte de béton et projettent, la nuit venue, un semis de points lumineux qui évoque un ciel étoilé au-dessus des fidèles. Le bâtiment a remporté l'Aga Khan Award for Architecture en 2016, une récompense rare pour une mosquée de quartier au budget aussi modeste.")
  ],
  mosquees_liees=["djenne", "xian"],
  photos=[
    dict(chemin="djenne/hero.webp", nom="Grande Mosquée de Djenné", description="Façade en terre crue (banco) de la Grande Mosquée de Djenné, Mali",
         source="Wikimedia Commons", auteur="Andy Gilham", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:Great_Mosque_of_Djenn%C3%A9_1.jpg"),
    dict(chemin="xian/hero.webp", nom="Grande Mosquée de Xi'an", description="Pavillons de style chinois traditionnel de la Grande Mosquée de Xi'an",
         source="Wikimedia Commons", auteur="Gaius Cornelius", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:Great_Mosque_of_Xi'an,_long_view.JPG"),
    dict(chemin="blog/mosquees-insolites/photo-1.webp", nom="Masjid 99 Kubah Asmaul Husna", description="Les 99 petites coupoles vues de l'intérieur de la mosquée Asmaul Husna, Makassar",
         source="Wikimedia Commons", auteur="Sekar Jarwo Soekarno", licence="CC BY 4.0",
         url="https://commons.wikimedia.org/wiki/File:Masjid_99_Kubah_Asmaul_Husna_Makassar_1.jpg"),
    dict(chemin="blog/mosquees-insolites/photo-2.webp", nom="Masjid Dian Al-Mahri (Kubah Emas)", description="Les coupoles recouvertes d'or de la mosquée Dian Al-Mahri, Depok",
         source="Wikimedia Commons", auteur="Alamnirvana", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:Menara_Masjid_Dian_Al_Mahri.jpg"),
    dict(chemin="blog/mosquees-insolites/photo-3.webp", nom="Mosquée de Sancaklar", description="La mosquée de Sancaklar, enfouie dans le flanc d'une colline, Turquie",
         source="Wikimedia Commons", auteur="Miraydwerri", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:04_EAA_Sancaklar-Mosque_ph-Cemal-Emden_full.jpg"),
    dict(chemin="blog/mosquees-insolites/photo-4.webp", nom="Mosquée Bait ur Rouf", description="Le plafond percé de puits de lumière de la mosquée Bait ur Rouf, Dhaka",
         source="Wikimedia Commons", auteur="Aashaa", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Bait_Ur_Rouf_mosque.jpg"),
  ]
),
dict(
  slug="deux-lieux-saints-mecque-medine",
  titre="La Mecque et Médine : les deux lieux saints de l'islam",
  description="Masjid al-Haram et Masjid an-Nabawi : comment les deux sanctuaires fondateurs de l'islam n'ont cessé de grandir depuis le VIIe siècle jusqu'à devenir les plus vastes lieux de culte du monde.",
  date="2026-02-02",
  temps_lecture="6 min",
  eyebrow="Histoire",
  intro="Deux villes, deux sanctuaires, un même point de départ : c'est à La Mecque et à Médine que l'islam prend racine au VIIe siècle. Quatorze siècles plus tard, la <a href=\"{RAC}mosquees/masjid-al-haram/index.html\">Masjid al-Haram</a> et la <a href=\"{RAC}mosquees/masjid-an-nabawi/index.html\">Masjid an-Nabawi</a> sont devenues les deux plus vastes lieux de culte de la planète, sans jamais cesser de s'agrandir.",
  corps=[
    ("La Mosquée sacrée, autour de la Kaaba",
     "La Masjid al-Haram entoure la Kaaba, l'édifice cubique vers lequel se tournent les musulmans du monde entier pour la prière. Simple enceinte à ciel ouvert aux premiers temps de l'islam, elle n'a cessé de croître : les califes omeyyades et abbassides lui donnent ses premières galeries à arcades, les Ottomans ses coupoles de pierre, avant que les extensions saoudiennes du XXe et du XXIe siècle n'en fassent le plus vaste sanctuaire du monde. La Pierre noire enchâssée dans l'angle de la Kaaba serait, selon la tradition, tombée du ciel à l'époque d'Adam ; le puits de Zamzam, situé dans l'enceinte, alimente les pèlerins en eau depuis des siècles."),
    ("Un chantier permanent, à l'échelle du pèlerinage",
     "Le sanctuaire actuel couvre plusieurs dizaines d'hectares sur plusieurs niveaux, irrigué par un réseau de tunnels, d'esplanades et de minarets dépassant 100 mètres. Chaque année, il accueille le <a href=\"https://fr.wikipedia.org/wiki/Hajj\" target=\"_blank\" rel=\"noopener\">hajj</a>, l'un des plus grands rassemblements humains au monde, ce qui en fait autant une prouesse logistique qu'un chef-d'œuvre spirituel. La tour de l'horloge voisine, l'Abraj Al Bait, porte l'un des plus grands cadrans d'horloge du monde, visible à des kilomètres."),
    ("La mosquée du Prophète, fondée en 622",
     "À 340 kilomètres de là, la Masjid an-Nabawi de Médine a été fondée par le Prophète Muhammad lui-même en 622, année de l'Hégire. Comme à La Mecque, l'édifice n'a cessé de s'agrandir au fil des dynasties, jusqu'à devenir aujourd'hui l'un des plus grands lieux de culte du monde, reconnaissable à son célèbre Dôme vert qui surmonte la tombe du Prophète."),
    ("Une avance technologique inattendue",
     "La mosquée fut l'un des tout premiers lieux du monde arabe à être éclairé à l'électricité, dès la fin du XIXe siècle. Aujourd'hui, ses 250 parasols géants, déployés automatiquement, climatisent des dizaines de milliers de mètres carrés d'esplanade. Le mihrab d'origine du Prophète et la Rawda, « jardin du Paradis », attirent une file continue de visiteurs jour et nuit."),
  ],
  mosquees_liees=["masjid-al-haram", "masjid-an-nabawi"],
  photos=[
    dict(chemin="masjid-al-haram/photo-5.webp", description="La Kaaba au centre de la cour de la Masjid al-Haram, La Mecque",
         source="Wikimedia Commons", auteur="Ilham Kurniawan Gumilang", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Ka%27bah_Mekkah.jpg"),
    dict(chemin="masjid-an-nabawi/hero.webp", description="Vue de la Masjid an-Nabawi et de son Dôme vert, Médine",
         source="Wikimedia Commons", auteur="M sh شراونة محمد", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:%D8%A7%D9%84%D9%85%D8%B3%D8%AC%D8%AF_%D8%A7%D9%84%D9%86%D8%A8%D9%88%D9%8A_%D8%A7%D9%84%D8%B4%D8%B1%D9%8A%D9%81_%D9%81%D9%8A_%D8%A7%D9%84%D9%85%D8%AF%D9%8A%D9%86%D8%A9_%D8%A7%D9%84%D9%85%D9%86%D9%88%D8%B1%D8%A9.jpg"),
    dict(chemin="masjid-an-nabawi/photo-5.webp", description="Les parasols géants déployés sur l'esplanade de la Masjid an-Nabawi",
         source="Wikimedia Commons", auteur="Tevfik Teker", licence="CC BY 3.0",
         url="https://commons.wikimedia.org/wiki/File:Canopies_of_Al_Masjid_Al_Nabawi_-_panoramio.jpg"),
  ]
),
dict(
  slug="mosquees-ottomanes-istanbul",
  titre="Mosquée bleue et Süleymaniye : les deux chefs-d'œuvre ottomans d'Istanbul",
  description="Comment la Mosquée bleue et la Süleymaniye, bâties à un demi-siècle d'écart, ont fixé le style de la mosquée impériale ottomane et dessiné la silhouette d'Istanbul.",
  date="2026-02-09",
  temps_lecture="6 min",
  eyebrow="Architecture",
  intro="Six minarets élancés et une cascade de coupoles côté Sultanahmet, une coupole unique dominant la Corne d'Or côté Süleymaniye : à un demi-siècle d'écart, ces deux mosquées ont fixé pour des siècles la silhouette d'Istanbul et le vocabulaire de l'architecture ottomane impériale.",
  corps=[
    ("La Süleymaniye, le chef-d'œuvre de Sinan",
     "Bâtie entre 1550 et 1557 par l'architecte <a href=\"https://fr.wikipedia.org/wiki/Mimar_Sinan\" target=\"_blank\" rel=\"noopener\">Mimar Sinan</a>, considéré comme le plus grand bâtisseur ottoman, la <a href=\"{RAC}mosquees/suleymaniye/index.html\">mosquée Süleymaniye</a> est dédiée à Soliman le Magnifique. Sinan, alors septuagénaire, la considérait comme son œuvre de « compagnon », la Selimiye d'Edirne restant à ses yeux son chef-d'œuvre absolu. Une pièce spéciale de la mosquée collectait la suie des lampes à huile, utilisée pour fabriquer l'encre des calligraphes ; des œufs d'autruche étaient suspendus aux lustres, censés éloigner les araignées et donc les toiles."),
    ("La Mosquée bleue, une prouesse et une polémique",
     "Construite entre 1609 et 1616 par l'architecte Sedefkâr Mehmed Ağa, la <a href=\"{RAC}mosquees/mosquee-bleue/index.html\">Mosquée bleue</a> (Sultan Ahmed) doit son surnom aux milliers de carreaux de céramique d'Iznik qui ornent son intérieur. Ses six minarets égalaient alors ceux de la Masjid al-Haram de La Mecque : le sultan aurait dû financer un septième minaret pour le sanctuaire mecquois afin d'apaiser la polémique que ce nombre inédit avait provoquée. Une légende raconte même que l'architecte aurait confondu « or » (altın) et « six » (altı) dans les ordres du sultan."),
    ("Deux réponses à un même défi structurel",
     "Les deux mosquées relèvent le même défi hérité de Sainte-Sophie : couvrir un vaste espace de prière d'une grande coupole centrale, sans piliers qui gêneraient l'alignement des rangs de fidèles. La Süleymaniye choisit une coupole unique portée par deux demi-coupoles ; la Mosquée bleue préfère une cascade de coupoles et de demi-coupoles en dégradé, renforcée par quatre piliers massifs surnommés « pattes d'éléphant »."),
    ("Un héritage commun, deux silhouettes",
     "La demande de carreaux d'Iznik pour la Mosquée bleue fut telle qu'elle épuisa les ateliers et contribua à leur déclin dans les décennies suivantes. Aujourd'hui encore, les deux mosquées restent en activité et se distinguent au premier coup d'œil sur la ligne d'horizon d'Istanbul : la Süleymaniye domine la Corne d'Or depuis sa colline, tandis que la Mosquée bleue fait face à Sainte-Sophie sur l'ancienne place de l'Hippodrome."),
  ],
  mosquees_liees=["mosquee-bleue", "suleymaniye"],
  photos=[
    dict(chemin="mosquee-bleue/hero.webp", description="Vue extérieure de la Mosquée bleue (Sultan Ahmed), Istanbul",
         source="Wikimedia Commons", auteur="David Berkowitz", licence="CC BY 2.0",
         url="https://commons.wikimedia.org/wiki/File:Sultan_Ahmed_Mosque_-_Blue_Mosque_-_Istanbul,_Turkey_(10582551665).jpg"),
    dict(chemin="suleymaniye/hero.webp", description="Vue extérieure de la mosquée Süleymaniye, Istanbul",
         source="Wikimedia Commons", auteur="İhsan Deniz Kılıçoğlu (NeoRetro)", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:S%C3%BCleymaniye_Mosque_exterior_view.JPG"),
  ]
),
dict(
  slug="asie-centrale-balkans-mosquees",
  titre="Samarcande, Sarajevo, Tirana : les mosquées d'Asie centrale et des Balkans",
  description="De la démesure timouride de Bibi-Khanym à la petite mosquée Et'hem Bey de Tirana, trois mosquées qui racontent l'expansion de l'islam vers l'Asie centrale et l'Europe des Balkans.",
  date="2026-02-16",
  temps_lecture="6 min",
  eyebrow="Découverte",
  intro="De Samarcande à Tirana en passant par Sarajevo, ces trois mosquées jalonnent une route moins connue de l'architecture islamique : celle de l'Asie centrale timouride et des Balkans ottomans, où l'islam s'est enraciné dès le Moyen Âge sans jamais cesser d'y être pratiqué.",
  corps=[
    ("Bibi-Khanym, la démesure de Tamerlan",
     "Construite entre 1398 et 1404 sur ordre de <a href=\"https://fr.wikipedia.org/wiki/Tamerlan\" target=\"_blank\" rel=\"noopener\">Tamerlan</a> (Timur), la <a href=\"{RAC}mosquees/bibi-khanym/index.html\">mosquée Bibi-Khanym</a> de Samarcande devait rassembler toute la population masculine de la ville pour la prière du vendredi. Timur fit venir des architectes et artisans de sa campagne d'Inde pour la bâtir à l'échelle de son empire ; à son achèvement, c'était l'une des plus grandes mosquées du monde islamique. La construction hâtive fragilisa cependant l'édifice, et l'arc de son portail principal s'effondra lors d'un séisme en 1897."),
    ("Gazi Husrev-beg, cœur spirituel de Sarajevo",
     "Construite en 1530, financée par le waqf du gouverneur ottoman Gazi Husrev-beg, la <a href=\"{RAC}mosquees/gazi-husrev-beg/index.html\">mosquée Gazi Husrev-beg</a> est la plus grande mosquée historique de Bosnie-Herzégovine et l'un des exemples les plus représentatifs de l'architecture ottomane classique dans les Balkans. Gravement endommagée par les bombardements du siège de Sarajevo (1992-1996), elle a été restaurée dès 1996, redevenant le symbole de la résilience de la communauté musulmane bosniaque."),
    ("Et'hem Bey, la mosquée qui a survécu à l'athéisme d'État",
     "Commencée vers 1791 par Molla Bey et achevée au début du XIXe siècle par son fils Haxhi Et'hem Bey, la <a href=\"{RAC}mosquees/ethem-bey/index.html\">mosquée Et'hem Bey</a> de Tirana se distingue par ses fresques représentant arbres, cascades et ponts, rares dans l'art religieux ottoman tardif. Fermée durant la période communiste, quand l'Albanie se proclama officiellement premier État athée du monde, elle a survécu grâce à son statut de monument historique protégé. Le 18 janvier 1991, environ 10 000 personnes y assistèrent à la prière du vendredi malgré l'interdiction gouvernementale encore en vigueur, un moment resté dans les mémoires comme la fin de facto de l'interdiction religieuse en Albanie."),
    ("Trois destins, une même continuité",
     "Ces trois mosquées, séparées par des milliers de kilomètres et plusieurs siècles, racontent chacune une résilience différente : celle d'un édifice trop ambitieux pour ses propres fondations à Samarcande, celle d'une reconstruction après la guerre à Sarajevo, celle d'une résistance silencieuse à l'interdiction religieuse à Tirana."),
  ],
  mosquees_liees=["bibi-khanym", "gazi-husrev-beg", "ethem-bey"],
  photos=[
    dict(chemin="bibi-khanym/photo-2.webp", description="Vue rapprochée du dôme principal de la mosquée Bibi-Khanym, Samarcande",
         source="Wikimedia Commons", auteur="Игорь Улитин (Igor Ulitin)", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Dome_of_the_Bibi-Khonim_Mosque.jpg"),
    dict(chemin="gazi-husrev-beg/hero.webp", description="Vue extérieure de la mosquée Gazi Husrev-beg, Sarajevo",
         source="Wikimedia Commons", auteur="Adam Harangozó", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Gazi_Husrev-beg_Mosque_in_Sarajevo.jpg"),
    dict(chemin="ethem-bey/hero.webp", description="Vue extérieure de la mosquée Et'hem Bey, Tirana",
         source="Wikimedia Commons", auteur="Pudelek", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Ethem_Bey_mosque,_Tirana_(by_Pudelek).jpg"),
  ]
),
dict(
  slug="mosquees-moghol-delhi-lahore",
  titre="Jama Masjid et Badshahi : les géantes moghol es de Delhi et Lahore",
  description="Comment les empereurs moghols Shah Jahan et Aurangzeb ont bâti, à Delhi puis à Lahore, deux des plus vastes mosquées du monde en grès rouge et marbre blanc.",
  date="2026-02-23",
  temps_lecture="5 min",
  eyebrow="Architecture",
  intro="À une vingtaine d'années d'écart, deux empereurs moghols font ériger deux mosquées à l'échelle de leur empire : la Jama Masjid de Delhi, achevée en 1656, et la mosquée Badshahi de Lahore, achevée en 1673, qui restera la plus grande mosquée du monde pendant près de trois siècles.",
  corps=[
    ("La Jama Masjid, la mosquée qui reflète le monde",
     "Commandée par l'empereur <a href=\"https://fr.wikipedia.org/wiki/Shah_Jahan\" target=\"_blank\" rel=\"noopener\">Shah Jahan</a>, le bâtisseur du Taj Mahal, et achevée entre 1650 et 1656, la <a href=\"{RAC}mosquees/jama-masjid/index.html\">Jama Masjid</a> de Delhi peut accueillir environ 25 000 fidèles dans sa cour. Son nom officiel, Masjid-i Jahan-Numa, signifie « la mosquée qui reflète le monde ». La montée d'un de ses minarets offre l'une des plus belles vues sur le Vieux Delhi et le Fort rouge voisin ; la mosquée conserve aussi des reliques attribuées au Prophète, montrées aux visiteurs à certaines occasions."),
    ("La mosquée Badshahi, l'« impériale » de Lahore",
     "Commandée par l'empereur Aurangzeb et achevée entre 1671 et 1673, la <a href=\"{RAC}mosquees/badshahi/index.html\">mosquée Badshahi</a> de Lahore resta la plus grande mosquée du monde pendant près de trois siècles ; ses minarets sont plus hauts que ceux du Taj Mahal. À l'époque sikhe puis britannique, l'édifice servit un temps de caserne et de poudrière avant d'être restauré. Sa petite galerie au-dessus du portail abrite elle aussi des reliques vénérées, dont des objets attribués au Prophète et à sa famille."),
    ("Le grès rouge, signature de l'architecture moghole tardive",
     "Les deux mosquées partagent le même vocabulaire architectural : grès rouge de Delhi souligné de marbre blanc, grands portails à iwan, coupoles bulbeuses cannelées et minarets élancés à bandes alternées. Ce style, hérité des palais et des mausolées moghols comme le Taj Mahal, atteint avec ces deux mosquées son expression la plus monumentale, pensée pour impressionner autant que pour accueillir la prière collective."),
  ],
  mosquees_liees=["jama-masjid", "badshahi"],
  photos=[
    dict(chemin="jama-masjid/hero.webp", description="Vue de la Jama Masjid et de sa cour, Delhi",
         source="Wikimedia Commons", auteur="Shashwat Nagpal", licence="CC BY 2.0",
         url="https://commons.wikimedia.org/wiki/File:Jama_Masjid_Delhi.JPG"),
    dict(chemin="badshahi/hero.webp", description="Vue de la mosquée Badshahi avec le Minar-e-Pakistan en arrière-plan, Lahore",
         source="Wikimedia Commons", auteur="Q. Isa Daudpota (Idaudpota)", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Badshahi_Mosque_with_Minar_e_Pakistan_in_the_background._Lahore.jpg"),
  ]
),
dict(
  slug="mosquees-egypte-kairouan-racines",
  titre="Al-Azhar, Ibn Touloun, Kairouan : les racines nord-africaines de l'architecture islamique",
  description="Trois mosquées fondatrices d'Égypte et de Tunisie, entre la plus ancienne université du monde, une rampe en spirale unique et le plus vieux minaret encore debout du monde islamique.",
  date="2026-03-02",
  temps_lecture="6 min",
  eyebrow="Histoire",
  intro="Le Caire et Kairouan comptent parmi les plus anciens foyers de l'architecture islamique en Afrique du Nord. Trois mosquées y résument à elles seules plusieurs siècles d'invention architecturale, de la Tunisie aghlabide à l'Égypte fatimide puis abbasside.",
  corps=[
    ("Kairouan, l'un des plus vieux minarets du monde islamique",
     "Fondée vers 670 par le général arabe Uqba ibn Nafi, la <a href=\"{RAC}mosquees/kairouan/index.html\">Grande Mosquée de Kairouan</a>, en Tunisie, conserve un minaret commencé vers 730, considéré comme le plus ancien encore debout du monde islamique. Ses colonnes de marbre et de porphyre proviennent de sites romains et byzantins comme Carthage. Un dicton local affirmait que sept pèlerinages à Kairouan équivalaient à un pèlerinage à La Mecque, une tradition populaire jamais reconnue comme canonique."),
    ("Ibn Touloun, une rampe en spirale sans équivalent",
     "Bâtie entre 876 et 879 sur ordre d'Ahmad ibn Touloun, gouverneur abbasside quasi indépendant d'Égypte, la <a href=\"{RAC}mosquees/ibn-tulun/index.html\">mosquée Ibn Touloun</a> du Caire se distingue par la rampe en spirale extérieure de son minaret, inspirée des ziggourats mésopotamiennes. Une légende raconte qu'Ibn Touloun aurait eu l'idée de cette spirale en enroulant distraitement un parchemin autour de son doigt. La mosquée aurait été bâtie sur la colline de Yashkur, où, selon la tradition locale, l'arche de Noé se serait posée."),
    ("Al-Azhar, une mosquée devenue université",
     "Fondée entre 970 et 972 par le général du <a href=\"https://fr.wikipedia.org/wiki/Calife_fatimide\" target=\"_blank\" rel=\"noopener\">califat fatimide</a> Jawhar al-Siqilli, la <a href=\"{RAC}mosquees/al-azhar/index.html\">mosquée Al-Azhar</a> est à la fois un lieu de culte et la plus ancienne université encore en activité au monde. Son nom, « la resplendissante », ferait référence à Fatima al-Zahra, fille du Prophète, dont se réclamaient les Fatimides. Des étudiants du monde entier y logeaient par « riwaq », des galeries attribuées par pays d'origine ; ses cinq minarets, construits à des époques différentes, forment un véritable manuel d'histoire de l'architecture égyptienne."),
    ("Trois strates d'une même histoire",
     "De Kairouan à Al-Azhar, ces trois mosquées jalonnent trois siècles d'expansion de l'islam en Afrique du Nord, chacune innovant à sa manière : la forme hypostyle et le minaret le plus ancien à Kairouan, la géométrie audacieuse de la spirale à Ibn Touloun, la vocation intellectuelle et universitaire à Al-Azhar."),
  ],
  mosquees_liees=["kairouan", "ibn-tulun", "al-azhar"],
  photos=[
    dict(chemin="kairouan/hero.webp", description="Vue panoramique de la Grande Mosquée de Kairouan et de son minaret",
         source="Wikimedia Commons", auteur="MAREK SZAREJKO from Clonmel, Ireland - Poland", licence="CC BY-SA 2.0",
         url="https://commons.wikimedia.org/wiki/File:Great_Mosque_of_Kairouan_Panorama_-_Grande_Mosqu%C3%A9e_de_Kairouan_Panorama.jpg"),
    dict(chemin="ibn-tulun/hero.webp", description="Vue de la mosquée Ibn Touloun et de son minaret à rampe en spirale, Le Caire",
         source="Wikimedia Commons", auteur="ولاء", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Ibn_Tulun_Mosque,_Cairo98.jpg"),
    dict(chemin="al-azhar/hero.webp", description="Cour de la mosquée Al-Azhar, Le Caire",
         source="Wikimedia Commons", auteur="Vyacheslav Argenberg", licence="CC BY 4.0",
         url="https://commons.wikimedia.org/wiki/File:The_Courtyard_of_Al-Azhar_Mosque,_Cairo,_Egypt.jpg"),
  ]
),
dict(
  slug="mosquees-banco-afrique-ouest",
  titre="Djenné, Larabanga, Bobo-Dioulasso : l'art du banco en Afrique de l'Ouest",
  description="Trois grandes mosquées en terre crue du Mali, du Ghana et du Burkina Faso, entretenues chaque année par leurs communautés dans le style architectural soudano-sahélien.",
  date="2026-03-09",
  temps_lecture="6 min",
  eyebrow="Découverte",
  intro="Du Mali au Ghana en passant par le Burkina Faso, une même tradition architecturale traverse les frontières : celle du banco, la brique de terre crue, sculptée en façades hérissées de bois et entretenue chaque année par toute une communauté.",
  corps=[
    ("Djenné, le plus grand édifice en terre crue du monde",
     "La <a href=\"{RAC}mosquees/djenne/index.html\">Grande Mosquée de Djenné</a>, au Mali, est le plus grand édifice en terre crue (banco) du monde. Chaque année, avant la saison des pluies, toute la ville participe au « crépissage », une fête collective où l'on ré-enduit les murs de terre fraîche à mains nues. Les torons de palmier qui hérissent la façade ne sont pas décoratifs : ce sont des échafaudages permanents, plantés dans le mur, qui permettent cet entretien annuel indispensable à la survie du bâtiment."),
    ("Larabanga, la « Mecque de l'Afrique de l'Ouest »",
     "Fondée selon la tradition en 1421, la <a href=\"{RAC}mosquees/larabanga/index.html\">mosquée de Larabanga</a>, au Ghana, est considérée comme la plus ancienne du pays et l'une des plus anciennes d'Afrique de l'Ouest, ce qui lui vaut le surnom de « Mecque de l'Afrique de l'Ouest ». Douze contreforts coniques, renforcés de bois horizontal saillant, soutiennent ses murs de terre. Selon la tradition locale, elle abriterait un ancien Coran considéré comme un don du ciel offert en 1650 à l'imam Bramah."),
    ("Bobo-Dioulasso, née d'une alliance politique",
     "Probablement le plus grand exemple d'architecture soudano-sahélienne du Burkina Faso, la <a href=\"{RAC}mosquees/bobo-dioulasso/index.html\">Grande Mosquée de Bobo-Dioulasso</a> est entièrement bâtie en latérite, argile et beurre de karité. Exemple typique de l'<a href=\"https://fr.wikipedia.org/wiki/Architecture_soudanaise\" target=\"_blank\" rel=\"noopener\">architecture soudanaise</a>, sa construction, entre 1812 et 1880 selon les sources, est liée à l'alliance entre le chef religieux almamy Sidiki Sanou et le royaume de Sia, face à la menace du royaume voisin du Kénédougou. Comme à Djenné, ses tours et piliers de bois saillants servent d'échafaudage permanent pour le crépissage annuel."),
    ("Une architecture vivante, pas un décor figé",
     "Ce qui distingue ces trois mosquées de la plupart des monuments historiques, c'est qu'elles ne sont pas figées : elles sont refaites, littéralement, chaque année par les mains de leurs communautés. Le banco n'est pas un matériau permanent comme la pierre, mais une matière vivante qui exige un entretien collectif constant : une architecture qui ne survit que parce qu'elle reste habitée et pratiquée."),
  ],
  mosquees_liees=["djenne", "larabanga", "bobo-dioulasso"],
  photos=[
    dict(chemin="djenne/hero.webp", description="Vue de la Grande Mosquée de Djenné, Mali",
         source="Wikimedia Commons", auteur="Andy Gilham", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:Great_Mosque_of_Djenn%C3%A9_1.jpg"),
    dict(chemin="larabanga/hero.webp", description="Vue de la mosquée de Larabanga, Ghana",
         source="Wikimedia Commons", auteur="Sathyan Velumani", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:Larabanga_Mosque_Ghana.jpg"),
    dict(chemin="bobo-dioulasso/hero.webp", description="Façade est de la Grande Mosquée de Bobo-Dioulasso, Burkina Faso",
         source="Wikimedia Commons", auteur="Semiliki", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:BoboDioulasso-GrandMosqueE.JPG"),
  ]
),
dict(
  slug="mosquees-iran-vitraux-coupoles",
  titre="Nasir al-Mulk et Cheikh Lotfollah : les mosquées iraniennes de la lumière",
  description="À Chiraz et à Ispahan, deux mosquées iraniennes qui font de la lumière filtrée un matériau de construction à part entière, l'une par ses vitraux colorés, l'autre par son dôme sans minaret.",
  date="2026-03-16",
  temps_lecture="5 min",
  eyebrow="Architecture",
  intro="En Iran, l'architecture religieuse a fait de la lumière un matériau à part entière. À Chiraz, la mosquée Nasir al-Mulk transforme chaque matin la prière en kaléidoscope de couleurs ; à Ispahan, la mosquée Cheikh Lotfollah cache derrière un couloir sombre l'un des dômes les plus parfaits de l'architecture persane.",
  corps=[
    ("Nasir al-Mulk, la « mosquée rose »",
     "Construite entre 1876 et 1888 par l'architecte Mohammad Hasan-e Memâr, la <a href=\"{RAC}mosquees/nasir-al-mulk/index.html\">mosquée Nasir al-Mulk</a> de Chiraz doit son surnom de « mosquée rose » à ses carreaux de céramique, qui en font l'une des mosquées les plus photographiées du monde. Chaque matin, tôt et surtout en hiver, ses vitraux colorés projettent des motifs éclatants sur le sol de la salle de prière, un spectacle qui ne dure que quelques heures. La fondation qui l'entretient est toujours gérée par les descendants de son commanditaire."),
    ("Cheikh Lotfollah, l'art du dévoilement progressif",
     "Construite entre 1603 et 1619 par l'architecte Mohammad Reza Isfahani pour l'usage privé de la cour royale, exemple de l'<a href=\"https://fr.wikipedia.org/wiki/Art_safavide\" target=\"_blank\" rel=\"noopener\">art safavide</a>, la <a href=\"{RAC}mosquees/cheikh-lotfollah/index.html\">mosquée Cheikh Lotfollah</a> d'Ispahan se distingue par l'absence de cour et de minaret, un choix architectural rare pour une mosquée de cette importance. Son couloir d'accès est volontairement coudé et sombre, pour que l'éblouissement de la coupole n'en soit que plus fort une fois franchi. Depuis l'entrée de la salle, le reflet de la lumière forme la queue déployée d'un paon dont le corps est peint au sommet du dôme."),
    ("Deux façons d'apprivoiser la lumière",
     "Là où Nasir al-Mulk laisse entrer la couleur par des dizaines de petits vitraux directement visibles depuis l'extérieur, Cheikh Lotfollah retient la lumière et la révèle progressivement, dans un parcours pensé comme une mise en scène. Deux approches radicalement différentes d'un même sujet : faire de la lumière naturelle un élément de composition architecturale à part entière, plutôt qu'une simple contrainte à éclairer."),
  ],
  mosquees_liees=["nasir-al-mulk", "cheikh-lotfollah"],
  photos=[
    dict(chemin="nasir-al-mulk/hero.webp", description="Vue de la mosquée Nasir al-Mulk, Chiraz",
         source="Wikimedia Commons", auteur="Mohammad Reza Domiri Ganji (Newyork3)", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Nasir_al-_mulk_mosque,_Shiraz.jpg"),
    dict(chemin="cheikh-lotfollah/hero.webp", description="Vue de la mosquée Cheikh Lotfollah, Ispahan",
         source="Wikimedia Commons", auteur="ZareMohsen1991", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Sheikh_Lotfollah_Mosque_-_isfahan.jpg"),
  ]
),
dict(
  slug="mosquees-malaisie-deux-visages",
  titre="Putra et Masjid Jamek : deux visages de la Malaisie musulmane",
  description="La mosquée rose contemporaine de Putrajaya et la mosquée coloniale fondatrice de Kuala Lumpur : deux façons de raconter l'histoire de l'islam en Malaisie, à un siècle d'écart.",
  date="2026-03-23",
  temps_lecture="5 min",
  eyebrow="Découverte",
  intro="À un siècle d'écart et à quelques dizaines de kilomètres l'une de l'autre, la Masjid Jamek et la mosquée Putra racontent deux Malaisies différentes : celle, coloniale, qui a vu naître Kuala Lumpur, et celle, contemporaine, d'une capitale administrative dessinée de toutes pièces.",
  corps=[
    ("Masjid Jamek, la mosquée fondatrice de Kuala Lumpur",
     "Construite en 1909 par l'architecte britannique Arthur Benison Hubback dans le style indo-sarrasin, la <a href=\"{RAC}mosquees/masjid-jamek/index.html\">Masjid Jamek</a> se dresse au confluent des rivières Klang et Gombak, à l'endroit précis où Kuala Lumpur (« confluent boueux ») a été fondée. Elle fut la principale mosquée de la ville jusqu'à la construction de la mosquée nationale en 1965. Endommagée lors d'un raid aérien japonais en 1941, elle a aussi vu l'un de ses dômes s'effondrer sous de fortes pluies en 1993, depuis réparé."),
    ("Putra, la mosquée rose de la capitale administrative",
     "Achevée en 1999 dans la capitale administrative <a href=\"https://fr.wikipedia.org/wiki/Putrajaya\" target=\"_blank\" rel=\"noopener\">Putrajaya</a>, la <a href=\"{RAC}mosquees/putra/index.html\">mosquée Putra</a> doit sa teinte rose caractéristique à un mélange de ciment rose, et non à une simple peinture. Bâtie au bord d'un lac artificiel, dans laquelle elle se reflète, elle est devenue l'un des symboles architecturaux de la Malaisie moderne, entre héritage moyen-oriental et identité nationale contemporaine."),
    ("Un siècle d'architecture religieuse malaisienne",
     "De la mosquée coloniale en briques rouges de Kuala Lumpur à la mosquée rose ultra-contemporaine de Putrajaya, ces deux édifices résument l'évolution de l'architecture religieuse malaisienne : un pays qui a d'abord composé avec l'héritage architectural britannique avant d'affirmer, un siècle plus tard, une identité islamique et nationale entièrement assumée dans le décor de sa nouvelle capitale."),
  ],
  mosquees_liees=["masjid-jamek", "putra"],
  photos=[
    dict(chemin="masjid-jamek/hero.webp", description="Vue extérieure de la Masjid Jamek, Kuala Lumpur",
         source="Wikimedia Commons", auteur="Stefan Fussan", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:Kuala_Lumpur_Masjid_Jamek.jpg"),
    dict(chemin="putra/hero.webp", description="Vue de la mosquée Putra et de son reflet dans le lac, Putrajaya",
         source="Wikimedia Commons", auteur="Ariff Shah Sopian", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Putra_Mosque,_Putrajaya.jpg"),
  ]
),
dict(
  slug="grotte-hira-naissance-islam-mosquee-quba",
  titre="De la grotte de Hira à la mosquée de Quba : les lieux fondateurs de l'islam",
  description="Comment une grotte de méditation, un premier verset révélé et une étape de l'Hégire ont donné naissance à l'islam, à sa première mosquée et au lieu où la direction de la prière a changé.",
  date="2026-03-30",
  temps_lecture="7 min",
  eyebrow="Histoire",
  intro="Selon la tradition musulmane, l'histoire de l'islam commence dans une grotte de montagne, avant de se prolonger jusqu'à la fondation de sa toute première mosquée. De la grotte de Hira à la mosquée de Quba, en passant par Masjid al-Qiblatayn, quatre lieux racontent la naissance progressive d'une nouvelle religion et de son architecture.",
  corps=[
    ("La grotte de Hira, un lieu de retraite avant la révélation",
     "Sur le mont Jabal al-Nour, aux abords de La Mecque, une petite grotte accueillait, selon la tradition, les retraites spirituelles annuelles de Muhammad avant même qu'il ne devienne prophète : il avait pour habitude de s'y isoler en méditation (tahannuth) pendant un mois. C'est dans cette grotte que la tradition situe la toute première révélation, vers l'an 610, datée de la Nuit du Destin (Laylat al-Qadr). Les premiers versets révélés y sont ceux de la sourate Al-Alaq, dont le mot d'ouverture, « Iqra » (« Lis » ou « Récite »), marque traditionnellement le point de départ de l'islam."),
    ("De la révélation à l'Hégire",
     "Après cette première révélation, la prédication de Muhammad à La Mecque se heurte à l'hostilité d'une partie de sa tribu, les Quraych. En 622, il quitte la ville avec ses compagnons pour rejoindre Médine : cette migration, l'Hégire (Hijra), marque le point de départ du calendrier musulman. C'est en chemin, lors d'une étape au village de Quba, aux portes de Médine, que se joue un épisode fondateur pour l'architecture religieuse de l'islam."),
    ("Quba, la première mosquée de l'islam",
     "La <a href=\"https://fr.wikipedia.org/wiki/Mosqu%C3%A9e_de_Quba\" target=\"_blank\" rel=\"noopener\">mosquée de Quba</a> est traditionnellement présentée comme la toute première mosquée construite dans l'histoire de l'islam. Les récits varient sur les détails de sa fondation : certains rapportent que le Prophète lui-même en aurait posé la première pierre à son arrivée à Quba, d'autres qu'elle aurait déjà été édifiée par les premiers émigrants avant son arrivée. Le séjour de Muhammad à Quba, avant son entrée officielle à Médine, aurait duré de trois à une vingtaine de jours selon les sources. L'édifice a été reconstruit et agrandi à de nombreuses reprises au fil des siècles, jusqu'à une reconstruction complète dans les années 1980 qui lui donne son visage actuel, aux dômes blancs caractéristiques."),
    ("Masjid al-Qiblatayn, la mosquée des deux qiblas",
     "À Médine se trouve un second lieu fondateur, distinct de Quba : <a href=\"https://fr.wikipedia.org/wiki/Masjid_al-Qiblatayn\" target=\"_blank\" rel=\"noopener\">Masjid al-Qiblatayn</a>, « la mosquée aux deux qiblas ». La tradition rapporte qu'en plein milieu d'une prière, le 15 Sha'ban de l'an 2 de l'Hégire (623), Muhammad y aurait reçu l'ordre de changer la direction de la prière : jusque-là tournée vers Jérusalem et la mosquée Al-Aqsa, elle se tourne désormais, et pour toujours, vers La Mecque et la Kaaba. C'est le seul lieu où le Prophète aurait prié vers deux qiblas différentes au cours d'une même prière, ce qui vaut son nom à la mosquée. L'édifice comportait à l'origine deux mihrabs orientés dans des directions différentes ; lors d'une reconstruction plus récente, le mihrab tourné vers Jérusalem a été retiré et remplacé par un simple repère commémoratif, sous un dôme secondaire."),
    ("Quatre lieux, une même trajectoire",
     "De la grotte de Hira à Masjid al-Qiblatayn, ces lieux dessinent la trajectoire fondatrice de l'islam naissant : un lieu de retraite et de révélation, une migration fondatrice, une première mosquée, et le geste architectural et spirituel qui fixe définitivement l'orientation de la prière vers La Mecque, celle-là même qui donne son nom au projet Qibla."),
  ],
  mosquees_liees=[],
  photos=[
    dict(chemin="blog/hira-quba-qiblatayn/photo-1.webp", description="La grotte de Hira sur le mont Jabal al-Nour, près de La Mecque",
         source="Wikimedia Commons", auteur="saudipics", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Hira_Cave.jpg"),
    dict(chemin="blog/hira-quba-qiblatayn/photo-3.webp", description="Vue extérieure de la mosquée de Quba, Médine",
         source="Wikimedia Commons", auteur="Kaliper1", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Quba_Mosque_(2024).jpg"),
    dict(chemin="blog/hira-quba-qiblatayn/photo-5.webp", description="Vue de la mosquée Masjid al-Qiblatayn, Médine",
         source="Wikimedia Commons", auteur="Bintladen", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Masjid_al-Qiblatayn.jpg"),
  ]
),
]
