# -*- coding: utf-8 -*-
"""Articles du blog Qibla (français) — contenu éditorial sur l'architecture islamique."""

ARTICLES = [
dict(
  slug="architecture-islamique-histoire-principes",
  titre="Qu'est-ce que l'architecture islamique ? Histoire et principes fondateurs",
  description="Origines, principes et grandes périodes de l'architecture islamique : de la mosquée du Prophète aux chefs-d'œuvre ottomans, moghols et contemporains.",
  date="2026-01-12",
  temps_lecture="7 min",
  eyebrow="Histoire",
  intro="On parle d'« architecture islamique » pour désigner un ensemble de traditions bâties, nées dans le monde musulman à partir du VIIe siècle, qui partagent des préoccupations communes — orienter le fidèle vers La Mecque, rassembler la communauté, orner sans représenter le vivant — tout en se transformant radicalement selon les époques et les régions.",
  corps=[
    ("Un point de départ : la mosquée du Prophète",
     "La première mosquée de l'histoire est de facto la maison du Prophète Muhammad à Médine, un enclos de terre battue entouré de huttes et ombragé de palmes. Cette forme simple — une cour, un mur orienté vers la qibla, un espace couvert pour la prière — restera la matrice de la mosquée dite « hypostyle », faite de rangées de colonnes soutenant une toiture plate, qu'on retrouve des siècles plus tard à la <a href=\"{RAC}mosquees/kairouan/index.html\">Grande Mosquée de Kairouan</a> ou dans la salle de prière de la <a href=\"{RAC}mosquees/cordoue/index.html\">mosquée-cathédrale de Cordoue</a>."),
    ("Des influences byzantines et perses",
     "Dès les conquêtes omeyyades puis abbassides, les bâtisseurs musulmans héritent des savoir-faire des civilisations qu'ils côtoient : la coupole et la maçonnerie de pierre de l'empire byzantin, l'art du décor et de la brique cuite de la Perse sassanide. La <a href=\"{RAC}mosquees/masjid-al-haram/index.html\">Masjid al-Haram</a> de La Mecque et la mosquée du Prophète à Médine ne cesseront d'ailleurs de s'agrandir au fil des dynasties, additionnant portiques, coupoles et minarets sans jamais renier leur fonction d'origine : entourer un lieu sacré."),
    ("L'apogée ottomane : la coupole comme signature",
     "À partir du XVe siècle, les architectes ottomans — Sinan en tête — perfectionnent l'art de la grande coupole centrale portée par des demi-coupoles en cascade, une prouesse structurelle directement inspirée de Sainte-Sophie. La <a href=\"{RAC}mosquees/mosquee-bleue/index.html\">Mosquée bleue</a> et la <a href=\"{RAC}mosquees/suleymaniye/index.html\">mosquée Süleymaniye</a> d'Istanbul illustrent cet équilibre entre monumentalité extérieure et intimité lumineuse intérieure, carrelée de céramiques d'Iznik."),
    ("Le monde persan et moghol : le règne du décor",
     "En Iran et en Asie du Sud, l'accent se déplace vers la parure : céramiques polychromes, muqarnas sculptés, vitraux colorés. La <a href=\"{RAC}mosquees/cheikh-lotfollah/index.html\">mosquée Cheikh Lotfollah</a> d'Ispahan ou la <a href=\"{RAC}mosquees/nasir-al-mulk/index.html\">mosquée Nasir al-Mulk</a> de Chiraz, surnommée « mosquée rose », transforment l'architecture en expérience presque picturale, où la lumière filtrée par le verre teinté devient un matériau de construction à part entière."),
    ("Une architecture toujours vivante",
     "Loin d'être figée dans le passé, l'architecture islamique continue de s'inventer : la <a href=\"{RAC}mosquees/hassan-ii/index.html\">mosquée Hassan II</a> de Casablanca marie décor traditionnel marocain et prouesses d'ingénierie contemporaine (son minaret culmine à plus de 200 mètres), tandis que la <a href=\"{RAC}mosquees/cheikh-zayed/index.html\">mosquée Cheikh Zayed</a> d'Abou Dabi assume un classicisme monumental en marbre blanc, pensé pour le XXIe siècle. D'une hutte de palmes à un vaisseau de marbre climatisé, le fil conducteur reste le même : bâtir un espace qui tourne la communauté vers un même point.")
  ],
  mosquees_liees=["kairouan", "cordoue", "mosquee-bleue", "suleymaniye", "hassan-ii"],
  photos=[
    dict(chemin="kairouan/photo-6.webp", description="Salle de prière hypostyle de la Grande Mosquée de Kairouan",
         source="Wikimedia Commons", auteur="Dennis G. Jarvis", licence="CC BY-SA 2.0",
         url="https://commons.wikimedia.org/wiki/File:Great_Mosque_of_Kairouan,_prayer_hall.jpg"),
    dict(chemin="hassan-ii/photo-3.webp", description="Vue d'ensemble de la mosquée Hassan II, Casablanca",
         source="Wikimedia Commons", auteur="Tinuzzo", licence="CC BY 4.0",
         url="https://commons.wikimedia.org/wiki/File:Hassan_II_Mosque_-_general_framing,_Casablanca,_Morocco.jpg"),
  ]
),
dict(
  slug="coupoles-minarets-symboles-mosquees",
  titre="Coupoles et minarets : pourquoi reconnaît-on une mosquée de loin ?",
  description="D'où viennent la coupole et le minaret, les deux éléments qui rendent une mosquée reconnaissable à des kilomètres ? Histoire et rôle de ces deux symboles architecturaux.",
  date="2026-01-19",
  temps_lecture="6 min",
  eyebrow="Architecture",
  intro="Silhouette caractéristique à l'horizon d'Istanbul, du Caire ou de Casablanca : la coupole et le minaret sont devenus, dans l'imaginaire collectif, les emblèmes visuels de la mosquée. Pourtant, ni l'une ni l'autre n'existaient à l'époque du Prophète — ce sont des ajouts progressifs, chargés d'histoire et de fonctions bien concrètes.",
  corps=[
    ("Le minaret, une tour pour l'appel à la prière",
     "Le mot « minaret » vient de l'arabe manāra, « qui donne de la lumière » — à l'origine, ces tours servaient parfois de phares ou de repères. Leur fonction s'est fixée autour de l'appel à la prière (adhan) : du haut du minaret, le muezzin devait porter sa voix le plus loin possible dans la ville. Les formes varient énormément selon les régions : minaret carré et trapu en Afrique du Nord (comme à la <a href=\"{RAC}mosquees/koutoubia/index.html\">Koutoubia</a> de Marrakech), tour-fusée effilée dans le monde ottoman, minaret-tronc de forme conique et spiralée à la <a href=\"{RAC}mosquees/kairouan/index.html\">Grande Mosquée de Kairouan</a>, l'un des plus anciens du monde islamique."),
    ("La coupole, un défi d'ingénieurs avant d'être un symbole",
     "La coupole n'a rien de spécifiquement islamique à l'origine : les Romains puis les Byzantins l'utilisaient déjà pour couvrir de grands espaces sans colonnes intermédiaires. Les architectes musulmans en héritent, notamment après la conquête de Constantinople, et en font l'élément central de la mosquée impériale ottomane. Techniquement, la coupole permet de couvrir une vaste salle de prière d'un seul tenant, sans piliers qui gêneraient l'alignement des rangs de fidèles — un vrai avantage liturgique autant qu'esthétique."),
    ("Des records d'ingénierie",
     "Certaines coupoles sont devenues de véritables prouesses techniques : celle de la <a href=\"{RAC}mosquees/cheikh-zayed/index.html\">mosquée Cheikh Zayed</a> d'Abou Dabi, en marbre blanc, compte parmi les plus grandes au monde ; le minaret de la <a href=\"{RAC}mosquees/hassan-ii/index.html\">mosquée Hassan II</a> de Casablanca, à plus de 200 mètres, est resté longtemps le plus haut du monde. À l'inverse, certaines grandes mosquées historiques comme celle de <a href=\"{RAC}mosquees/djenne/index.html\">Djenné</a>, bâtie en banco (terre crue), se passent presque entièrement de coupole : ses contreforts de bois (les toron) et sa silhouette pyramidale répondent à une autre contrainte, celle de la construction en terre en climat sahélien."),
    ("Deux symboles, une même fonction : orienter et rassembler",
     "Au-delà de la prouesse technique, coupole et minaret remplissent une fonction commune : signaler la présence de la communauté et organiser l'espace de la prière. Le minaret appelle et rassemble ; la coupole abrite et unifie le regard vers le mihrab, la niche qui indique la direction de La Mecque. Deux réponses architecturales différentes à une même exigence spirituelle.")
  ],
  mosquees_liees=["koutoubia", "kairouan", "cheikh-zayed", "hassan-ii", "djenne"],
  photos=[
    dict(chemin="koutoubia/photo-2.webp", description="Le minaret de la Koutoubia, Marrakech",
         source="Wikimedia Commons", auteur="Holger Uwe Schmitt", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:1158_wurde_die_Koutoubia-Moschee_in_Marrakesch_er%C3%B6fnet._01.jpg"),
    dict(chemin="cheikh-zayed/photo-10.webp", description="Coupoles de marbre blanc de la mosquée Cheikh Zayed, Abou Dabi",
         source="Wikimedia Commons", auteur="Francesco Bini", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Abu_dhabi,_Moschea_dello_Sceicco_Zayed,_aula_di_preghiera,_01.jpg"),
  ]
),
dict(
  slug="muqarnas-motifs-geometriques-art-islamique",
  titre="Muqarnas et motifs géométriques : les secrets mathématiques de l'art islamique",
  description="Étoiles à huit branches, entrelacs et muqarnas en nid d'abeille : comment les artisans de l'art islamique ont transformé la géométrie en décor sacré, sans jamais représenter de figure vivante.",
  date="2026-01-26",
  temps_lecture="6 min",
  eyebrow="Décor",
  intro="Aucune figure humaine ou animale sur les murs d'une mosquée : cette retenue, souvent résumée (un peu vite) sous le terme d'« aniconisme », a poussé les artisans du monde islamique à développer l'un des langages ornementaux les plus sophistiqués de l'histoire de l'art — fondé sur la géométrie, la calligraphie et la répétition infinie du motif.",
  corps=[
    ("Le girih, ou l'art de l'entrelacs",
     "Le girih (« nœud » en persan) désigne ces réseaux de lignes entrelacées qui composent étoiles à six, huit ou seize branches, polygones et rosaces enchevêtrés à l'infini. Construits à la règle et au compas à partir de figures géométriques simples, ces motifs peuvent pourtant produire des compositions d'une complexité redoutable : des chercheurs ont montré en 2007 que certains décors du XVe siècle, comme ceux de la mosquée-madrasa de Darb-i Imam en Iran, préfiguraient des pavages quasi-périodiques que les mathématiques occidentales ne formaliseront (avec les pavages de Penrose) que cinq siècles plus tard."),
    ("Le muqarnas, sculpter la lumière en nid d'abeille",
     "Le muqarnas est une structure en alvéoles superposées, un peu comme des stalactites de plâtre, de bois ou de pierre, utilisée pour habiller la transition entre un mur droit et une coupole ronde, ou pour orner un portail, une niche, un plafond. Chaque alvéole capte et diffuse la lumière différemment selon l'heure du jour, créant un jeu d'ombres changeant. Les muqarnas de la <a href=\"{RAC}mosquees/cheikh-lotfollah/index.html\">mosquée Cheikh Lotfollah</a> d'Ispahan ou ceux qui ornent nombre de portails en Afrique du Nord et au Moyen-Orient comptent parmi les sommets de cet art."),
    ("La calligraphie, un décor qui se lit",
     "Troisième pilier du décor islamique : l'écriture elle-même. Versets coraniques, noms de Dieu ou de son prophète sont stylisés en frises coufiques anguleuses ou en cursives fluides, intégrées aux frises géométriques au point de devenir, pour l'œil non-arabophone, un motif abstrait de plus. Cette fusion entre texte sacré et ornement est particulièrement spectaculaire dans les céramiques polychromes des mosquées ottomanes et persanes, comme celles qui recouvrent l'intérieur de la <a href=\"{RAC}mosquees/mosquee-bleue/index.html\">Mosquée bleue</a> d'Istanbul."),
    ("La lumière colorée, un matériau à part entière",
     "Dans le monde persan, un quatrième langage décoratif s'ajoute aux trois précédents : le vitrail. À la <a href=\"{RAC}mosquees/nasir-al-mulk/index.html\">mosquée Nasir al-Mulk</a> de Chiraz, des kilomètres de verre coloré projettent, chaque matin, des taches de lumière arc-en-ciel sur les tapis de la salle de prière — un rappel que dans l'art islamique, le décor n'est jamais un simple habillage : il transforme l'expérience même de l'espace sacré.")
  ],
  mosquees_liees=["cheikh-lotfollah", "mosquee-bleue", "nasir-al-mulk"],
  photos=[
    dict(chemin="cheikh-lotfollah/photo-9.webp", description="Motifs et muqarnas de la mosquée Cheikh Lotfollah, Ispahan",
         source="Wikimedia Commons", auteur="Monaesfandiar", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:4R9A7644.jpg"),
    dict(chemin="nasir-al-mulk/photo-6.webp", description="Vitraux colorés de la mosquée Nasir al-Mulk, Chiraz",
         source="Wikimedia Commons", auteur="dynamosquito from France", licence="CC BY-SA 2.0",
         url="https://commons.wikimedia.org/wiki/File:A_touch_of_paradise_(2470492244).jpg"),
  ]
),
dict(
  slug="mosquees-malaisie-architecture-moderne",
  titre="Les mosquées de Malaisie : entre tradition malaise et modernisme spectaculaire",
  description="De la Mosquée Nationale à la mosquée Putra, comment la Malaisie a fait de ses mosquées des manifestes architecturaux depuis son indépendance.",
  date="2026-02-02",
  temps_lecture="6 min",
  eyebrow="Asie du Sud-Est",
  intro="Peu de pays ont autant fait de leurs mosquées des symboles d'identité nationale que la Malaisie. Depuis l'indépendance en 1957, chaque grande mosquée y est aussi un manifeste architectural, mêlant héritage malais, influences moyen-orientales et modernisme assumé.",
  corps=[
    ("La Mosquée Nationale, un manifeste d'indépendance",
     "Achevée en 1965, la Masjid Negara (Mosquée Nationale) de Kuala Lumpur est pensée dès l'origine comme le symbole architectural d'une nation tout juste indépendante. Sa toiture principale, un parapluie plissé à 18 pointes, ne cherche pas à imiter une coupole traditionnelle : elle évoque à la fois une fleur épanouie et le pliage d'un umbrella cérémoniel malais, tout en comptant symboliquement les treize États de la fédération et les cinq piliers de l'islam. Son minaret élancé, en forme de fusée à ailerons, tranche radicalement avec les tours ottomanes ou mogholes."),
    ("La mosquée Putra, entre lac et granit rose",
     "À Putrajaya, ville administrative construite à la fin des années 1990, la <a href=\"{RAC}mosquees/putra/index.html\">mosquée Putra</a> pousse plus loin le mélange des influences : dôme et minaret inspirés de l'Iran et de l'Asie centrale, mais construction en granit rose local et implantation en grande partie sur un lac artificiel, résolument contemporaine."),
    ("La Mosquée bleue de Shah Alam, un gabarit hors normes",
     "Non loin de Kuala Lumpur, la mosquée du Sultan Salahuddin Abdul Aziz à Shah Alam — surnommée « Mosquée bleue » pour son immense dôme turquoise, l'un des plus grands du monde — illustre une autre tendance : la course au gigantisme, avec une capacité dépassant parfois les 24 000 fidèles, portée par les moyens d'un État pétrolier régional."),
    ("Un vocabulaire propre à l'Asie du Sud-Est",
     "Avant l'arrivée de ces grands programmes officiels, l'architecture mosquée malaise puisait dans un vocabulaire vernaculaire très différent : toitures étagées en tuiles, charpentes de bois, influences chinoises et indiennes issues des routes commerciales. Ce fonds vernaculaire n'a pas disparu : on le retrouve encore dans de nombreuses petites mosquées de villages (kampung), en contrepoint des géants de béton et de granit des grandes villes.")
  ],
  mosquees_liees=["putra"],
  photos=[
    dict(chemin="blog/mosquees-malaisie-architecture-moderne/photo-1.webp", description="La Mosquée Nationale de Malaisie (Masjid Negara), Kuala Lumpur",
         source="Wikimedia Commons", auteur="Marcin Konsek", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:2016_Kuala_Lumpur,_Meczet_Narodowy_Malezji_(02).jpg"),
    dict(chemin="putra/photo-2.webp", description="La mosquée Putra et son dôme de granit rose, Putrajaya",
         source="Wikimedia Commons", auteur="Ariff Shah Sopian", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Putra_Mosque,_Putrajaya.jpg"),
  ]
),
dict(
  slug="mosquees-algerie-heritage-ottoman-contemporain",
  titre="Les mosquées d'Algérie : de l'héritage ottoman au plus haut minaret d'Afrique",
  description="De la mosquée Ketchaoua d'Alger, façonnée par trois régimes successifs, à Djamaâ El Djazaïr et son minaret record, panorama de l'architecture mosquée en Algérie.",
  date="2026-02-09",
  temps_lecture="6 min",
  eyebrow="Maghreb",
  intro="L'Algérie concentre, sur un même territoire, l'un des plus vieux sanctuaires almoravides du Maghreb et l'un des plus jeunes records architecturaux du monde musulman : un minaret de 265 mètres, achevé en 2019. Entre les deux, des siècles d'allers-retours entre pouvoirs ottoman, colonial et national.",
  corps=[
    ("Ketchaoua, une mosquée à trois vies",
     "Peu d'édifices religieux ont connu un destin aussi mouvementé que la mosquée Ketchaoua, dans la Casbah d'Alger. Construite (ou largement reconstruite) à l'époque ottomane au XVIIIe siècle, elle est transformée en cathédrale après la prise d'Alger par la France en 1830 — ses deux minarets sont alors surmontés de clochers. À l'indépendance en 1962, l'édifice redevient une mosquée. Ses portes sculptées et ses colonnes de marbre témoignent aujourd'hui de ces strates successives, ottomane, coloniale, puis à nouveau religieuse musulmane."),
    ("La Grande Mosquée d'Alger, doyenne almoravide",
     "Alger conserve aussi un patrimoine bien plus ancien : la Grande Mosquée (Djamaa al-Kebir), dont le noyau daterait du XIe siècle, sous la dynastie almoravide, ce qui en fait l'une des plus anciennes mosquées encore en activité du Maghreb central. Sa salle de prière à colonnades et son minaret sobre, ajouté au XVIe siècle, rappellent la sobriété des débuts de l'architecture mosquée nord-africaine, avant les grands décors des siècles suivants."),
    ("Djamaâ El Djazaïr, un record contemporain",
     "À l'autre extrémité de la chronologie, Djamaâ El Djazaïr (« la Grande Mosquée d'Alger »), inaugurée en 2019 sur le front de mer, revendique le troisième rang mondial par sa capacité d'accueil et le minaret le plus haut d'Afrique, culminant à 265 mètres. Ses galeries d'arcades continues sur plusieurs centaines de mètres et sa salle de prière conçue pour résister aux séismes en font un manifeste d'ingénierie autant que de foi, à l'échelle des grands projets contemporains du Golfe."),
    ("Une architecture de transition, entre Maghreb et Méditerranée",
     "Entre ces extrêmes chronologiques, l'Algérie a aussi hérité de mosquées ottomanes plus modestes dans les grandes villes côtières (Alger, Constantine, Annaba), reconnaissables à leurs dômes trapus et à leurs minarets octogonaux proches des modèles turcs, une signature que l'on retrouve autour de toute la Méditerranée ottomane, de Tunis à Sarajevo.")
  ],
  mosquees_liees=[],
  photos=[
    dict(chemin="blog/mosquees-algerie-heritage-ottoman-contemporain/photo-1.webp", description="Djamaâ El Djazaïr (Grande Mosquée d'Alger) et son minaret de 265 mètres",
         source="Wikimedia Commons", auteur="Rachid Hamatou", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Djama%C3%A2_El_Djaza%C3%AFr_%E2%80%93_The_Great_Mosque_of_Algiers_1.jpg"),
    dict(chemin="blog/mosquees-algerie-heritage-ottoman-contemporain/photo-2.webp", description="Les minarets ottomans de la mosquée Ketchaoua, Alger",
         source="Wikimedia Commons", auteur="Dan Sloan", licence="CC BY-SA 2.0",
         url="https://commons.wikimedia.org/wiki/File:20141113-_DSC0096-3_(15887428745).jpg"),
  ]
),
dict(
  slug="mosquees-maroc-tradition-almohade",
  titre="Les mosquées du Maroc : de la doyenne de Fès aux prouesses de Casablanca",
  description="D'Al Quaraouiyine, plus ancienne université du monde selon l'UNESCO, à la mosquée Hassan II : panorama de la tradition mosquée marocaine, almohade puis contemporaine.",
  date="2026-02-16",
  temps_lecture="6 min",
  eyebrow="Maghreb",
  intro="Le Maroc n'a jamais cessé de bâtir des mosquées depuis le IXe siècle, sans jamais rompre totalement avec son vocabulaire almohade — toits de tuiles vertes, arcs outrepassés, zelliges géométriques — que l'on retrouve autant dans la doyenne de Fès que dans le géant contemporain de Casablanca.",
  corps=[
    ("Al Quaraouiyine, une mosquée devenue université millénaire",
     "Fondée en 859 à Fès par Fatima al-Fihriya, une riche héritière, la mosquée Al Quaraouiyine abrite l'une des plus anciennes institutions d'enseignement encore en activité au monde, reconnue comme telle par l'UNESCO et le Livre Guinness des records. Agrandie sur plus d'un millénaire, elle conserve un plan hypostyle typique des débuts de l'architecture mosquée nord-africaine, avec cour à bassins et salle de prière profonde soutenue par des arcades en fer à cheval."),
    ("L'empreinte almohade : la Koutoubia comme modèle",
     "Aux XIIe et XIIIe siècles, la dynastie almohade impose dans tout le Maghreb et al-Andalus un vocabulaire commun : minaret carré massif, décor d'arcs entrelacés en pierre sculptée, toiture de tuiles vertes vernissées. La <a href=\"{RAC}mosquees/koutoubia/index.html\">Koutoubia</a> de Marrakech en est l'exemple le plus abouti, et son influence se lit directement dans la Giralda de Séville ou la tour Hassan de Rabat, bâties à la même époque par les mêmes ateliers."),
    ("Tin Mal, le sanctuaire fondateur dans l'Atlas",
     "Loin des grandes villes, la mosquée de Tin Mal, isolée dans les montagnes du Haut Atlas, marque le berceau spirituel du mouvement almohade : c'est ici que son fondateur, Ibn Toumert, établit sa base avant la conquête de Marrakech. Dépouillée d'ornements superflus, l'édifice frappe par la pureté de ses volumes et reste, huit siècles plus tard, un lieu de pèlerinage architectural pour comprendre l'origine du style almohade."),
    ("Hassan II, la synthèse contemporaine",
     "Achevée en 1993 à Casablanca, la <a href=\"{RAC}mosquees/hassan-ii/index.html\">mosquée Hassan II</a> reprend consciemment ce vocabulaire almohade — zelliges, plâtres ciselés, toit de tuiles vertes — à une échelle inédite, avec un minaret dépassant 200 mètres et une salle de prière au toit ouvrant, bâtie en partie sur l'océan Atlantique. Une manière d'affirmer que la tradition mosquée marocaine, huit siècles après Tin Mal, reste une architecture vivante plutôt qu'un style figé.")
  ],
  mosquees_liees=["koutoubia", "hassan-ii"],
  photos=[
    dict(chemin="koutoubia/photo-9.webp", description="La Koutoubia et son décor almohade, Marrakech",
         source="Wikimedia Commons", auteur="Samuel Romero", licence="CC BY 3.0",
         url="https://commons.wikimedia.org/wiki/File:A_Place_To_Pray_(260498733).jpeg"),
    dict(chemin="hassan-ii/photo-8.webp", description="Zelliges et plâtres ciselés de la mosquée Hassan II, Casablanca",
         source="Wikimedia Commons", auteur="Walaadari", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Maroc,_Mosqu%C3%A9e_Hassan_2,_Grand_Casablanca_2.jpg"),
  ]
),
dict(
  slug="plus-belle-plus-grande-mosquee-tunisie",
  titre="La Zitouna et Malek Ibn Anas : les plus belles et plus grandes mosquées de Tunisie",
  description="Zitouna, la doyenne millénaire de la médina de Tunis, et Malek Ibn Anas, le géant contemporain de Carthage : deux façons de répondre à la question « quelle est la plus grande mosquée de Tunisie ? »",
  date="2026-02-23",
  temps_lecture="6 min",
  eyebrow="Maghreb",
  intro="Poser la question de « la plus belle et la plus grande mosquée de Tunisie » revient en réalité à en désigner deux : la mosquée Zitouna, cœur spirituel et intellectuel de la médina de Tunis depuis plus de treize siècles, et la mosquée Malek Ibn Anas, géant contemporain de Carthage qui détient aujourd'hui le record de capacité du pays.",
  corps=[
    ("Zitouna, « l'olivier » au cœur de la médina",
     "Fondée à la toute fin du VIIe siècle et considérablement agrandie sous les Aghlabides au IXe siècle, la Grande Mosquée Zitouna (« mosquée de l'olivier ») est la plus ancienne mosquée de Tunis et l'une des plus vastes du pays, avec près de 5 000 m² au cœur de la médina classée à l'UNESCO. Sa salle de prière hypostyle, portée par plus de 160 colonnes antiques réemployées (marbre, granit, porphyre), et son minaret carré de style almohade en font l'un des monuments les plus photographiés de Tunisie."),
    ("Une université presque aussi vieille que la mosquée",
     "Comme Al Quaraouiyine à Fès ou Al-Azhar au Caire, Zitouna n'est pas seulement un lieu de culte : dès le VIIIe siècle, on y enseigne le droit, la grammaire et les sciences religieuses, ce qui en fait l'un des plus anciens foyers d'enseignement supérieur du monde musulman. Cette double vocation, spirituelle et savante, a irrigué toute l'histoire intellectuelle tunisienne jusqu'à la création de l'université Zitouna moderne, qui perpétue cet héritage."),
    ("Malek Ibn Anas, le nouveau record de capacité",
     "À une vingtaine de kilomètres de là, sur la colline de Carthage, la mosquée Malek Ibn Anas — aussi connue sous le nom de mosquée El Abidine — est aujourd'hui la plus grande mosquée de Tunisie par sa capacité d'accueil, de l'ordre de plusieurs dizaines de milliers de fidèles esplanade comprise. Achevée au début des années 2000, elle reprend le vocabulaire almohade classique (arcs outrepassés, minaret élancé, portails sculptés) à une échelle monumentale, dans la lignée des grandes mosquées nationales bâties ailleurs dans le Maghreb au tournant du XXIe siècle."),
    ("Deux réponses à une même question",
     "Zitouna l'emporte sur l'ancienneté, le rayonnement intellectuel et la densité patrimoniale ; Malek Ibn Anas l'emporte sur la superficie et la capacité d'accueil. Plutôt qu'un classement, les deux édifices racontent la même histoire sous deux angles : celle d'un pays qui n'a jamais cessé de bâtir des mosquées, du VIIe siècle à aujourd'hui, sans rompre avec son vocabulaire architectural nord-africain — arcs en fer à cheval, minarets carrés, portails sculptés — hérité de Kairouan et transmis de génération en génération de bâtisseurs.")
  ],
  mosquees_liees=["kairouan"],
  photos=[
    dict(chemin="blog/mosquees-tunisie-zitouna-malik-ibn-anas/photo-1.webp", description="Cour intérieure et minaret de la Grande Mosquée Zitouna, Tunis",
         source="Wikimedia Commons", auteur="Noomen9", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Minaret_zitouna_(44957).jpg"),
    dict(chemin="blog/mosquees-tunisie-zitouna-malik-ibn-anas/photo-2.webp", description="Façade et minaret illuminés de la mosquée Malek Ibn Anas, Carthage",
         source="Wikimedia Commons", auteur="Gharbi Ryadh", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:Grande_mosqu%C3%A9e_Anas_Ibn_Malak_de_Carthage.jpg"),
  ]
),
dict(
  slug="top-3-plus-belles-mosquees-malaisie",
  titre="Top 3 des plus belles mosquées de Malaisie",
  description="Masjid Kristal, mosquée Putra et Masjid Negara : notre sélection des trois mosquées les plus spectaculaires de Malaisie, entre verre, granit rose et modernisme des années 1960.",
  date="2026-03-02",
  temps_lecture="8 min",
  eyebrow="Classement",
  intro="Difficile de choisir tant la Malaisie a multiplié, depuis son indépendance, les mosquées-manifestes. Voici néanmoins notre sélection des trois plus spectaculaires, du verre flottant de Terengganu au granit rose de Putrajaya, avec pour chacune l'histoire, les chiffres et les détails qui justifient sa place sur ce podium.",
  corps=[
    ("#1 — Masjid Kristal, la mosquée de verre flottante",
     "À Kuala Terengganu, capitale de l'État du Terengganu sur la côte est de la péninsule malaise, la Masjid Kristal (« mosquée de cristal ») occupe la première place pour une raison simple : c'est l'une des seules mosquées au monde bâtie presque entièrement en verre, en acier et en aluminium, posée sur une plateforme qui semble flotter à la confluence de la rivière Terengganu et de la mer de Chine méridionale. Construite sur l'île de Wan Man, inaugurée en février 2008 par le sultan de l'État, elle constitue la pièce maîtresse du Parc de la civilisation islamique (Taman Tamadun Islam), un vaste complexe qui présente, sur cette même île, des répliques à échelle réduite d'une vingtaine de monuments islamiques célèbres à travers le monde, de la Kaaba au Taj Mahal. "
     "Sa structure d'acier et de verre feuilleté, plutôt qu'une maçonnerie traditionnelle, lui permet un tour de force que ni la pierre ni le béton ne pourraient offrir : changer littéralement d'apparence selon l'heure et la météo. Dorée et cuivrée au lever et au coucher du soleil, elle vire à l'argenté sous le plein soleil de midi et se pare, la nuit venue, d'un jeu de lumières LED programmables qui colorent tour à tour dômes et minarets. Sa position, presque entièrement entourée d'eau, ajoute un effet miroir quasi permanent qu'aucune autre grande mosquée d'Asie du Sud-Est ne reproduit à cette échelle. Elle peut accueillir environ 1 500 fidèles, un gabarit modeste comparé aux deux mosquées suivantes de ce classement, compensé par une identité visuelle qu'aucune autre mosquée du pays ne revendique."),
    ("#2 — La mosquée Putra, le granit rose sur le lac",
     "À <a href=\"{RAC}mosquees/putra/index.html\">Putrajaya</a>, ville administrative fédérale construite de toutes pièces à la fin des années 1990 pour désengorger Kuala Lumpur, la mosquée Putra doit sa place sur ce podium à un choix de matériau aussi simple que radical : un dôme et des murs en granit rose, une teinte que l'on ne retrouve dans aucune autre grande mosquée d'Asie du Sud-Est, directement inspirée des camaïeux de rose de la mosquée du Cheikh Lotfollah et d'autres édifices persans safavides. Achevée en 1999, elle peut accueillir environ 15 000 fidèles répartis entre la salle de prière et l'esplanade, et se dresse aux trois quarts au-dessus du lac artificiel de Putrajaya, creusé spécialement pour donner à la nouvelle capitale administrative un visage monumental. "
     "Son minaret, qui culmine à 116 mètres — l'un des plus hauts d'Asie du Sud-Est — est structuré en cinq sections distinctes, un découpage qui symbolise les cinq piliers de l'islam ; l'ensemble du complexe, avec sa grande cour à arcades et ses portes sculptées, assume un mélange revendiqué d'influences moyen-orientales (perse et moyen-orientale pour le vocabulaire décoratif) et malaises (dans les proportions générales et certains détails de toiture). Elle est aujourd'hui l'une des mosquées les plus visitées du pays, notamment en raison de sa proximité avec le complexe du Premier ministre et les administrations fédérales qui l'entourent."),
    ("#3 — Masjid Negara, le manifeste de l'indépendance",
     "La Mosquée nationale de Kuala Lumpur ferme ce podium, non pas pour son ancienneté au sens absolu — elle date de 1965, quand plusieurs mosquées de ce site remontent à plusieurs siècles — mais pour sa radicalité formelle. Inaugurée le 27 août 1965, moins de dix ans après l'indépendance de la Malaisie (1957), elle est conçue dès l'origine comme un symbole national plutôt que comme une simple mosquée de quartier : sa toiture principale, un parapluie de béton plissé à 18 pointes, rompt délibérément avec la coupole hémisphérique traditionnelle du monde ottoman ou moghol, et son minaret en forme de fusée à ailerons, haut de 73 mètres, reste, soixante ans après son inauguration, l'une des silhouettes les plus reconnaissables de toute l'architecture mosquée du XXe siècle. "
     "Le chiffre 18 n'est pas arbitraire : il additionne les treize États fédérés de la Malaisie et les cinq piliers de l'islam. Le complexe, qui peut accueillir environ 15 000 fidèles, s'étend sur près de 5 hectares de jardins et de bassins réfléchissants, sur le site de l'ancien terrain de polo du Selangor Turf Club en plein cœur de la capitale. Le projet, mené par une équipe d'architectes britanniques et malaisiens réunis pour l'occasion, a volontairement cherché à s'affranchir des références ottomanes ou mogholes alors dominantes dans l'imagerie mondiale de la mosquée, pour proposer un vocabulaire propre — une démarche que l'on retrouvera, des décennies plus tard, dans la mosquée Putra puis la Masjid Kristal."),
    ("Des critères forcément subjectifs",
     "Ce classement reste évidemment une question de goût — la « Mosquée bleue » de Shah Alam (mosquée du Sultan Salahuddin Abdul Aziz), avec l'un des plus grands dômes du monde et une capacité dépassant parfois les 24 000 fidèles, ou la doyenne Masjid Kampung Kling à Malacca, un rare exemple de mosquée malaisienne au toit étagé de style pagode chinoise datant du XVIIIe siècle, auraient tout aussi bien mérité leur place. Mais Masjid Kristal, Putra et Negara ont ceci de commun qu'elles illustrent, chacune à sa manière et à une génération d'écart (1965, 1999, 2008), la même ambition constante depuis l'indépendance : faire de la mosquée malaisienne un manifeste architectural et une affirmation d'identité nationale, plutôt qu'une simple reproduction des modèles importés du Moyen-Orient.")
  ],
  mosquees_liees=["putra"],
  photos=[
    dict(chemin="blog/top-3-plus-belles-mosquees-malaisie/photo-1.webp", nom="Masjid Kristal", description="La Masjid Kristal (mosquée de cristal) flottant sur l'eau, Kuala Terengganu",
         source="Wikimedia Commons", auteur="DestinationFearFan", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Crystal_Mosque_in_Kuala_Terengganu_Malaysia.jpg"),
    dict(chemin="blog/top-3-plus-belles-mosquees-malaisie/photo-2.webp", nom="Masjid Kristal", description="Vue aérienne de la Masjid Kristal sur la rivière Terengganu",
         source="Wikimedia Commons", auteur="Saha 165", licence="CC BY 3.0",
         url="https://commons.wikimedia.org/wiki/File:Crystal_Mosque_Aerial_Shot_1.jpg"),
    dict(chemin="blog/top-3-plus-belles-mosquees-malaisie/photo-3.webp", nom="Masjid Kristal", description="Intérieur du dôme de verre et lustre central de la Masjid Kristal",
         source="Wikimedia Commons", auteur="Azuladnan", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Crystal_Mosque_Interior.jpg"),
    dict(chemin="putra/photo-2.webp", nom="Mosquée Putra", description="La mosquée Putra et son dôme de granit rose, Putrajaya",
         source="Wikimedia Commons", auteur="Muhammad Faqih", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Masjid_Putra,_Putrajaya.jpg"),
    dict(chemin="putra/photo-3.webp", nom="Mosquée Putra", description="Intérieur de la grande salle de prière de la mosquée Putra",
         source="Wikimedia Commons", auteur="Slices of Light", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Masjid_Putra_-_Main_Prayer_Hall.jpg"),
    dict(chemin="putra/photo-4.webp", nom="Mosquée Putra", description="Le minaret à cinq étages de la mosquée Putra",
         source="Wikimedia Commons", auteur="Slices of Light", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Putra_Mosque_Spire.jpg"),
    dict(chemin="blog/top-3-plus-belles-mosquees-malaisie/photo-4.webp", nom="Masjid Negara", description="Le minaret en forme de fusée de la Masjid Negara, Kuala Lumpur",
         source="Wikimedia Commons", auteur="Non spécifié (domaine public, CC0)", licence="CC0",
         url="https://commons.wikimedia.org/wiki/File:20190822_National_Mosque_of_Malaysia_minaret-1.jpg"),
    dict(chemin="blog/top-3-plus-belles-mosquees-malaisie/photo-5.webp", nom="Masjid Negara", description="Cour à bassins et bâtiments annexes de la Masjid Negara",
         source="Wikimedia Commons", auteur="Non spécifié (domaine public, CC0)", licence="CC0",
         url="https://commons.wikimedia.org/wiki/File:20190822_National_Mosque_of_Malaysia_fountain-1.jpg"),
    dict(chemin="blog/mosquees-malaisie-architecture-moderne/photo-1.webp", nom="Masjid Negara", description="La toiture en étoile plissée à 18 pointes de la Masjid Negara",
         source="Wikimedia Commons", auteur="Marcin Konsek", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:2016_Kuala_Lumpur,_Meczet_Narodowy_Malezji_(02).jpg"),
  ]
),
dict(
  slug="mosquees-insolites-architecture-hors-normes",
  titre="6 mosquées insolites qui sortent des sentiers battus",
  description="Terre crue, 99 coupoles, dôme en or, mosquée enterrée dans une colline : six lieux de culte qui prouvent que l'architecture mosquée ne se résume pas au dôme et au minaret classiques.",
  date="2026-03-09",
  temps_lecture="7 min",
  eyebrow="Insolite",
  intro="Pas de dôme, pas de minaret, une couleur qui détonne ou un matériau improbable : ces six mosquées ont en commun de rompre, chacune à sa façon, avec l'image la plus attendue de l'architecture mosquée. Deux figurent déjà parmi nos mosquées incontournables ; les quatre autres méritaient elles aussi le détour.",
  corps=[
    ("La Grande Mosquée de Djenné, une ville entière en terre crue",
     "Impossible de parler d'insolite sans commencer par <a href=\"{RAC}mosquees/djenne/index.html\">Djenné</a>, au Mali : c'est tout simplement le plus grand édifice en terre crue (banco) du monde. Chaque année, avant la saison des pluies, toute la ville participe au « crépissage », une fête collective où l'on ré-enduit les murs de terre fraîche à mains nues. Les torons de palmier qui hérissent la façade ne sont pas décoratifs : ce sont des échafaudages permanents, plantés dans le mur, qui permettent cet entretien annuel indispensable à la survie du bâtiment."),
    ("La Grande Mosquée de Xi'an, sans dôme ni minaret",
     "À l'autre extrême esthétique, la <a href=\"{RAC}mosquees/xian/index.html\">Grande Mosquée de Xi'an</a>, en Chine, ne ressemble à aucune autre mosquée du monde : ni dôme, ni minaret visibles, mais une succession de cours et de pavillons de bois aux toitures incurvées, strictement identiques dans leur composition aux temples chinois traditionnels. Seule l'orientation est-ouest de son axe, contraire aux temples chinois classiques orientés nord-sud, trahit sa fonction : elle pointe vers La Mecque."),
    ("La mosquée aux 99 coupoles de Makassar",
     "En Indonésie, la mosquée Al-Asmaul Husna, plus connue sous le nom de « mosquée aux 99 coupoles » (Masjid 99 Kubah), pousse un symbole islamique jusqu'à l'extrême architectural : son toit est littéralement composé de 99 petites coupoles, une pour chacun des 99 noms attribués à Dieu dans la tradition musulmane (les Asmaul Husna). Construite sur un terre-plein gagné sur la mer à Makassar, dans le sud de l'île de Sulawesi, vue de l'intérieur, la coupole centrale forme une étoile éclatante entourée de ce chapelet de mini-dômes, un motif que l'on ne retrouve dans aucune autre mosquée au monde."),
    ("La mosquée au dôme d'or de Depok",
     "Toujours en Indonésie, la mosquée Dian Al-Mahri, surnommée « mosquée au dôme d'or » (Masjid Kubah Emas), assume un autre genre de démesure : ses coupoles sont recouvertes de plaques d'or véritable. Financée par une fondation privée et inaugurée en 2006 dans la banlieue de Depok, près de Jakarta, elle est devenue l'un des monuments religieux les plus photographiés du pays, visible de loin grâce à l'éclat de ses dômes dorés qui tranche avec le vert et le blanc habituels des grandes mosquées d'Asie du Sud-Est."),
    ("La mosquée creusée dans une colline, en Turquie",
     "Près d'Istanbul, la mosquée de Sancaklar prend le contre-pied total de l'imagerie classique : conçue par l'architecte Emre Arolat et achevée en 2012, elle est littéralement enfouie dans le flanc d'une colline, sans dôme ni minaret traditionnel — seule une fine colonne de pierre, à peine plus haute qu'un lampadaire, en tient lieu. À l'intérieur, la lumière filtre depuis une fente au sommet du volume, dans une ambiance minérale presque monacale. Le projet a été distingué par l'un des plus prestigieux prix internationaux d'architecture, l'Aga Khan Award for Architecture."),
    ("La mosquée au plafond étoilé de Dhaka",
     "À Dhaka, capitale du Bangladesh, la mosquée Bait ur Rouf, conçue par l'architecte Marina Tabassum et achevée en 2012, renonce elle aussi au dôme et au minaret : un simple cylindre de brique nue, financé par une donatrice privée sur un terrain modeste de quartier. Sa prouesse se cache au plafond : des puits de lumière circulaires percent la voûte de béton et projettent, la nuit venue, un semis de points lumineux qui évoque un ciel étoilé au-dessus des fidèles. Le bâtiment a remporté l'Aga Khan Award for Architecture en 2016, une récompense rare pour une mosquée de quartier au budget aussi modeste.")
  ],
  mosquees_liees=["djenne", "xian"],
  photos=[
    dict(chemin="djenne/hero.webp", nom="Grande Mosquée de Djenné", description="Façade en terre crue (banco) de la Grande Mosquée de Djenné, Mali",
         source="Wikimedia Commons", auteur="Andy Gilham", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:Great_Mosque_of_Djenn%C3%A9_1.jpg"),
    dict(chemin="xian/hero.webp", nom="Grande Mosquée de Xi'an", description="Pavillons de style chinois traditionnel de la Grande Mosquée de Xi'an",
         source="Wikimedia Commons", auteur="Gaius Cornelius", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:Great_Mosque_of_Xi'an,_long_view.JPG"),
    dict(chemin="blog/mosquees-insolites/photo-1.webp", nom="Masjid 99 Kubah Asmaul Husna", description="Les 99 petites coupoles vues de l'intérieur de la mosquée Asmaul Husna, Makassar",
         source="Wikimedia Commons", auteur="Sekar Jarwo Soekarno", licence="CC BY 4.0",
         url="https://commons.wikimedia.org/wiki/File:Masjid_99_Kubah_Asmaul_Husna_Makassar_1.jpg"),
    dict(chemin="blog/mosquees-insolites/photo-2.webp", nom="Masjid Dian Al-Mahri (Kubah Emas)", description="Les coupoles recouvertes d'or de la mosquée Dian Al-Mahri, Depok",
         source="Wikimedia Commons", auteur="Alamnirvana", licence="CC BY-SA 3.0",
         url="https://commons.wikimedia.org/wiki/File:Menara_Masjid_Dian_Al_Mahri.jpg"),
    dict(chemin="blog/mosquees-insolites/photo-3.webp", nom="Mosquée de Sancaklar", description="La mosquée de Sancaklar, enfouie dans le flanc d'une colline, Turquie",
         source="Wikimedia Commons", auteur="Miraydwerri", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:04_EAA_Sancaklar-Mosque_ph-Cemal-Emden_full.jpg"),
    dict(chemin="blog/mosquees-insolites/photo-4.webp", nom="Mosquée Bait ur Rouf", description="Le plafond percé de puits de lumière de la mosquée Bait ur Rouf, Dhaka",
         source="Wikimedia Commons", auteur="Aashaa", licence="CC BY-SA 4.0",
         url="https://commons.wikimedia.org/wiki/File:Bait_Ur_Rouf_mosque.jpg"),
  ]
),
]
