# -*- coding: utf-8 -*-
"""Questions du quiz Qibla (français) — 3 thèmes, 100 questions chacun.
Contenu cadré sur la tradition sunnite (majoritaire) : les points de doctrine propres au chiisme
(imamat, statut particulier de certains compagnons, etc.) ne sont pas abordés. Contenu factuel,
respectueux, à visée culturelle et pédagogique — aucune information n'est présentée comme un jugement
de valeur entre traditions musulmanes."""

# ============================================================== THÈME 1 : ISLAM ET SON PROPHÈTE
_ISLAM_PROPHETE = [
  # --- Vie du Prophète ---
  dict(q="Dans quelle ville le prophète Muhammad est-il né ?",
       options=["La Mecque", "Médine", "Jérusalem", "Damas"], reponse=0,
       explication="Muhammad naît à La Mecque vers 570, dans la tribu des Quraych."),
  dict(q="Comment appelle-t-on la migration du Prophète de La Mecque à Médine ?",
       options=["Le Mi'raj", "L'Hégire (Hijra)", "Le Hajj", "La Sunna"], reponse=1,
       explication="L'Hégire, en 622, marque aussi le point de départ du calendrier musulman."),
  dict(q="Dans quelle grotte le Prophète aurait-il reçu sa première révélation ?",
       options=["La grotte de Thawr", "La grotte de Hira", "La grotte des Sept Dormants", "La grotte de Qumrân"], reponse=1,
       explication="La grotte de Hira se trouve sur le mont Jabal al-Nour, près de La Mecque."),
  dict(q="Quel ange est traditionnellement associé à la transmission de la révélation au Prophète ?",
       options=["Mika'il", "Isrāfīl", "Jibril (Gabriel)", "Malik"], reponse=2),
  dict(q="Quel est le nom de la première épouse du Prophète, la première à avoir cru en son message ?",
       options=["Aïcha", "Fatima", "Khadija", "Zaynab"], reponse=2),
  dict(q="En quelle année du calendrier grégorien situe-t-on traditionnellement la naissance du Prophète ?",
       options=["Vers 510", "Vers 570", "Vers 610", "Vers 630"], reponse=1),
  dict(q="Quel est le nom de l'oncle qui a élevé et protégé Muhammad après la mort de ses parents et de son grand-père ?",
       options=["Abou Talib", "Abou Lahab", "Al-Abbas", "Hamza"], reponse=0),
  dict(q="Comment se nomme le voyage nocturne miraculeux du Prophète de La Mecque à Jérusalem puis vers les cieux ?",
       options=["Le Hajj", "L'Isra et le Mi'raj", "La Omra", "La Hijra"], reponse=1,
       explication="L'Isra désigne le voyage nocturne vers Jérusalem, le Mi'raj l'ascension céleste."),
  dict(q="En quelle année le Prophète meurt-il, à Médine ?",
       options=["622", "630", "632", "661"], reponse=2),
  dict(q="Quel est le nom du père du Prophète, mort avant sa naissance ?",
       options=["Abdallah", "Abdel Mouttalib", "Abou Bakr", "Zayd"], reponse=0),
  dict(q="Quel est le nom de la mère du Prophète, morte alors qu'il était enfant ?",
       options=["Halima", "Amina", "Safiya", "Ruqayya"], reponse=1),
  dict(q="Quel métier le Prophète a-t-il exercé avant de recevoir la révélation ?",
       options=["Berger puis marchand caravanier", "Forgeron", "Scribe", "Médecin"], reponse=0),
  dict(q="En quelle année les musulmans conquièrent-ils pacifiquement La Mecque, permettant au Prophète d'y retourner ?",
       options=["622", "628", "630", "632"], reponse=2,
       explication="La conquête de La Mecque en 630 se déroule presque sans effusion de sang."),
  dict(q="Que fait le Prophète en priorité en entrant dans la Kaaba lors de la conquête de La Mecque, selon la tradition ?",
       options=["Il y installe son trône", "Il fait détruire les idoles qui l'occupaient", "Il la ferme définitivement", "Il la rebâtit entièrement"], reponse=1),
  dict(q="Quel est le nom du dernier sermon prononcé par le Prophète, peu avant sa mort ?",
       options=["Le sermon de l'adieu", "Le sermon de la lumière", "Le sermon du jeûne", "Le sermon de la nuit"], reponse=0),
  dict(q="Quelle tribu de La Mecque était celle du prophète Muhammad ?",
       options=["Les Quraych", "Les Aws", "Les Khazraj", "Les Thaqif"], reponse=0),
  dict(q="Comment se nomme la pratique et les paroles rapportées du Prophète, second fondement de l'islam après le Coran ?",
       options=["La Sunna", "La Charia seule", "Le Tafsir", "Le Fiqh seul"], reponse=0),
  dict(q="Quel est le surnom donné à Muhammad avant même la révélation, en reconnaissance de son honnêteté ?",
       options=["Al-Amin (le digne de confiance)", "Al-Fatih (le conquérant)", "Al-Karim (le généreux)", "An-Nour (la lumière)"], reponse=0),
  dict(q="Combien d'années, selon la tradition, dure la période de révélation du Coran au Prophète ?",
       options=["Environ 5 ans", "Environ 13 ans", "Environ 23 ans", "Environ 40 ans"], reponse=2),
  dict(q="Quel âge avait le Prophète lorsqu'il reçut sa première révélation ?",
       options=["25 ans", "40 ans", "50 ans", "60 ans"], reponse=1),

  # --- Les cinq piliers ---
  dict(q="Combien l'islam compte-t-il de piliers (obligations fondamentales) ?",
       options=["3", "4", "5", "7"], reponse=2,
       explication="Attestation de foi, prière, aumône, jeûne du Ramadan et pèlerinage."),
  dict(q="Comment se nomme l'attestation de foi, premier pilier de l'islam ?",
       options=["La Chahada", "La Salat", "La Zakat", "Le Sawm"], reponse=0),
  dict(q="Combien de prières quotidiennes obligatoires un musulman doit-il accomplir ?",
       options=["3", "5", "7", "9"], reponse=1),
  dict(q="Comment se nomme l'aumône légale, troisième pilier de l'islam ?",
       options=["La Sadaqa", "La Zakat", "Le Waqf", "La Kaffara"], reponse=1,
       explication="La Sadaqa désigne l'aumône volontaire, distincte de la Zakat qui est obligatoire."),
  dict(q="Vers quelle ville les musulmans se tournent-ils pendant la prière ?",
       options=["Médine", "Jérusalem", "Damas", "La Mecque"], reponse=3,
       explication="Cette direction s'appelle la qibla, qui a donné son nom à ce site."),
  dict(q="Comment se nomme le jeûne du mois de Ramadan, quatrième pilier de l'islam ?",
       options=["Le Sawm", "L'I'tikaf", "Le Qiyam", "Le Tarawih"], reponse=0),
  dict(q="Comment se nomme le pèlerinage annuel à La Mecque, cinquième pilier de l'islam ?",
       options=["La Omra", "Le Hajj", "Le Ramadan", "La Zakat"], reponse=1,
       explication="Le Hajj a lieu une fois par an ; l'Omra, un pèlerinage non obligatoire, peut se faire toute l'année."),
  dict(q="Le Hajj est-il obligatoire pour tous les musulmans, sans exception ?",
       options=["Oui, absolument tous", "Seulement pour les hommes", "Uniquement s'ils en ont la capacité physique et financière", "Seulement une fois tous les dix ans"], reponse=2),
  dict(q="Quel geste rituel accomplissent les pèlerins autour de la Kaaba pendant le Hajj ?",
       options=["Le tawaf (les sept circumambulations)", "Le sujud unique", "La qiyam prolongée", "Le sa'i uniquement"], reponse=0),
  dict(q="Quel est le nom de la course rituelle entre les monts Safa et Marwa, effectuée pendant le Hajj et la Omra ?",
       options=["Le Tawaf", "Le Sa'i", "Le Wuquf", "Le Ramy"], reponse=1),
  dict(q="Quel jour de la semaine la prière collective du vendredi (Jumu'a) est-elle prescrite ?",
       options=["Le jeudi", "Le vendredi", "Le samedi", "Le dimanche"], reponse=1),

  # --- Le Coran ---
  dict(q="Quel est le nom du livre sacré de l'islam ?",
       options=["La Torah", "Le Coran", "Les Évangiles", "Les Psaumes"], reponse=1,
       explication="Le Coran est considéré par les musulmans comme la parole de Dieu révélée à Muhammad."),
  dict(q="Comment appelle-t-on un chapitre du Coran ?",
       options=["Un verset", "Une sourate", "Un juz'", "Un hadith"], reponse=1),
  dict(q="Combien le Coran compte-t-il de sourates ?",
       options=["99", "114", "144", "200"], reponse=1),
  dict(q="Comment appelle-t-on un verset du Coran ?",
       options=["Une sourate", "Un ayat", "Un hizb", "Un juz'"], reponse=1),
  dict(q="Quelle est la sourate la plus courte du Coran, souvent citée par son nombre de versets réduit ?",
       options=["Al-Fatiha", "Al-Baqara", "Al-Kawthar", "Yasin"], reponse=2),
  dict(q="Comment se nomme la première sourate du Coran, récitée à chaque unité de prière ?",
       options=["Al-Ikhlas", "Al-Fatiha", "An-Nas", "Al-Falaq"], reponse=1),
  dict(q="Dans quelle langue le Coran a-t-il été révélé ?",
       options=["L'araméen", "L'hébreu", "L'arabe", "Le persan"], reponse=2),
  dict(q="Comment se nomme la nuit durant laquelle le Coran aurait commencé à être révélé, célébrée pendant le Ramadan ?",
       options=["La Nuit du Destin (Laylat al-Qadr)", "La Nuit du Voyage", "La Nuit du Pardon", "La Nuit de la Mi-Chaabane"], reponse=0),
  dict(q="En combien de parties égales (juz') le Coran est-il traditionnellement divisé pour faciliter sa lecture complète ?",
       options=["7", "12", "30", "60"], reponse=2,
       explication="Cette division en 30 parties permet une lecture complète en un mois, notamment pendant le Ramadan."),
  dict(q="Comment appelle-t-on la récitation psalmodiée du Coran ?",
       options=["Le tajwid", "Le tafsir", "Le fiqh", "Le kalam"], reponse=0),

  # --- Hadith et savants sunnites ---
  dict(q="Comment appelle-t-on les paroles et actes rapportés du Prophète, distincts du Coran ?",
       options=["Les hadiths", "Les sourates", "Les fatwas", "Les zabours"], reponse=0),
  dict(q="Quel recueil de hadiths, compilé par l'imam Al-Bukhari, est considéré par les sunnites comme l'un des plus fiables ?",
       options=["Sahih al-Bukhari", "Le Muwatta", "Les Évangiles", "Le Zabur"], reponse=0),
  dict(q="Avec Sahih al-Bukhari, quel autre recueil de hadiths, compilé par l'imam Muslim, fait autorité chez les sunnites ?",
       options=["Sahih Muslim", "Sunan Abi Dawud", "Jami' at-Tirmidhi", "Sunan Ibn Majah"], reponse=0,
       explication="Ces deux recueils forment ce qu'on appelle « les deux Sahih », les plus rigoureusement vérifiés."),
  dict(q="Comment appelle-t-on l'ensemble des six recueils de hadiths les plus reconnus dans la tradition sunnite ?",
       options=["Les Sihah Sittah (les six authentiques)", "Les Quatre Piliers", "Les Dix Rapporteurs", "Le Canon unique"], reponse=0),
  dict(q="Comment appelle-t-on la science qui étudie la fiabilité de la chaîne de transmission d'un hadith ?",
       options=["Le tafsir", "La science de l'isnad", "Le kalam", "La sira"], reponse=1),
  dict(q="Comment appelle-t-on un avis juridique rendu par un savant musulman ?",
       options=["Une fatwa", "Un hadith", "Un tafsir", "Une sourate"], reponse=0),
  dict(q="Comment se nomme la biographie traditionnelle du Prophète ?",
       options=["La Sira", "La Sunna", "Le Fiqh", "Le Tafsir"], reponse=0),
  dict(q="Comment appelle-t-on le commentaire et l'exégèse du Coran ?",
       options=["Le Tafsir", "La Sira", "Le Hadith", "La Fatwa"], reponse=0),
  dict(q="Comment appelle-t-on la science du droit musulman ?",
       options=["Le Fiqh", "Le Kalam", "Le Tajwid", "Le Isnad"], reponse=0),
  dict(q="Comment appelle-t-on le consensus des savants, une des sources du droit musulman sunnite ?",
       options=["L'Ijma", "Le Qiyas", "L'Ijtihad", "Le Taqlid"], reponse=0),

  # --- Califes bien-guidés et compagnons (spécifique tradition sunnite) ---
  dict(q="Dans la tradition sunnite, comment appelle-t-on les quatre premiers califes ayant succédé au Prophète ?",
       options=["Les califes bien-guidés (Rashidun)", "Les califes omeyyades", "Les grands vizirs", "Les Imams infaillibles"], reponse=0,
       explication="Abou Bakr, Omar, Othman et Ali sont reconnus comme les quatre califes « bien-guidés » dans la tradition sunnite."),
  dict(q="Qui fut le premier calife après la mort du Prophète, selon la tradition sunnite ?",
       options=["Abou Bakr", "Omar ibn al-Khattab", "Othman ibn Affan", "Ali ibn Abi Talib"], reponse=0,
       explication="Abou Bakr, proche compagnon et beau-père du Prophète, est le premier des quatre califes bien-guidés."),
  dict(q="Quel calife bien-guidé est réputé pour l'expansion territoriale rapide de l'État musulman naissant ?",
       options=["Abou Bakr", "Omar ibn al-Khattab", "Othman ibn Affan", "Ali ibn Abi Talib"], reponse=1),
  dict(q="Sous quel calife la compilation officielle et unifiée du Coran fut-elle établie ?",
       options=["Abou Bakr", "Omar ibn al-Khattab", "Othman ibn Affan", "Ali ibn Abi Talib"], reponse=2,
       explication="Le calife Othman fait établir une version canonique du Coran diffusée dans toutes les provinces."),
  dict(q="Qui est le quatrième calife bien-guidé, cousin et gendre du Prophète ?",
       options=["Abou Bakr", "Omar ibn al-Khattab", "Othman ibn Affan", "Ali ibn Abi Talib"], reponse=3),
  dict(q="Comment appelle-t-on les compagnons du Prophète, ayant vécu à ses côtés ?",
       options=["Les Sahaba", "Les Tabi'un", "Les Ansar seulement", "Les Muhajirun seulement"], reponse=0),
  dict(q="Comment appelle-t-on les habitants de Médine qui accueillirent le Prophète et ses compagnons lors de l'Hégire ?",
       options=["Les Muhajirun", "Les Ansar", "Les Quraych", "Les Sahaba uniquement"], reponse=1),
  dict(q="Comment appelle-t-on les compagnons mecquois qui émigrèrent avec le Prophète vers Médine ?",
       options=["Les Ansar", "Les Muhajirun", "Les Rashidun", "Les Tabi'un"], reponse=1),
  dict(q="Quelle épouse du Prophète, fille d'Abou Bakr, est une source majeure de hadiths dans la tradition sunnite ?",
       options=["Khadija", "Aïcha", "Hafsa", "Safiya"], reponse=1),
  dict(q="Quel compagnon est réputé pour avoir été un scribe fidèle de la révélation et rapporteur de hadiths ?",
       options=["Zayd ibn Thabit", "Abou Jahl", "Abou Lahab", "Al-Walid"], reponse=0,
       explication="Zayd ibn Thabit a notamment supervisé la compilation du Coran sous le calife Abou Bakr puis Othman."),

  # --- Écoles juridiques sunnites ---
  dict(q="Combien de grandes écoles juridiques (madhahib) sont reconnues dans le sunnisme ?",
       options=["Deux", "Quatre", "Six", "Douze"], reponse=1,
       explication="Les écoles hanafite, malikite, chaféite et hanbalite."),
  dict(q="Quelle école juridique sunnite porte le nom de l'imam Abou Hanifa ?",
       options=["L'école hanafite", "L'école malikite", "L'école chaféite", "L'école hanbalite"], reponse=0),
  dict(q="Quelle école juridique sunnite porte le nom de l'imam Malik ibn Anas ?",
       options=["L'école hanafite", "L'école malikite", "L'école chaféite", "L'école hanbalite"], reponse=1),
  dict(q="Quelle école juridique sunnite porte le nom de l'imam Ash-Shafi'i ?",
       options=["L'école hanafite", "L'école malikite", "L'école chaféite", "L'école hanbalite"], reponse=2),
  dict(q="Quelle école juridique sunnite porte le nom de l'imam Ahmad ibn Hanbal ?",
       options=["L'école hanafite", "L'école malikite", "L'école chaféite", "L'école hanbalite"], reponse=3),
  dict(q="Ces quatre écoles juridiques sunnites divergent-elles sur les piliers fondamentaux de la foi ?",
       options=["Oui, chacune a sa propre profession de foi", "Non, elles partagent les mêmes fondements de foi et diffèrent sur des détails de pratique", "Oui, elles ne reconnaissent pas le même Coran", "Non, elles sont identiques en tout point sans aucune différence"], reponse=1),
  dict(q="Dans quelle région le madhab malikite est-il aujourd'hui le plus répandu ?",
       options=["Afrique du Nord et Afrique de l'Ouest", "Asie du Sud-Est", "Asie centrale", "Péninsule arabique"], reponse=0),
  dict(q="Dans quelle région le madhab hanafite est-il historiquement le plus répandu ?",
       options=["Turquie, Asie centrale et sous-continent indien", "Afrique de l'Ouest uniquement", "Océanie", "Amérique du Sud"], reponse=0),

  # --- Ramadan et fêtes ---
  dict(q="Pendant quel mois du calendrier musulman les musulmans jeûnent-ils ?",
       options=["Muharram", "Chaabane", "Ramadan", "Dhou al-Hijja"], reponse=2),
  dict(q="Quel repas marque la rupture du jeûne quotidien pendant le Ramadan ?",
       options=["Le suhoor", "L'iftar", "Le tarawih", "Le witr"], reponse=1),
  dict(q="Comment se nomme le repas pris avant l'aube pendant le Ramadan ?",
       options=["Le suhoor", "L'iftar", "L'i'tikaf", "Le qiyam"], reponse=0),
  dict(q="Quelle fête marque la fin du mois de Ramadan ?",
       options=["L'Aïd al-Fitr", "L'Aïd al-Adha", "Achoura", "Al-Mawlid"], reponse=0),
  dict(q="Quelle fête commémore, dans la tradition musulmane, la disposition d'Ibrahim à sacrifier son fils ?",
       options=["L'Aïd al-Fitr", "L'Aïd al-Adha", "Achoura", "Laylat al-Qadr"], reponse=1),
  dict(q="Pendant quel mois du calendrier musulman le Hajj a-t-il lieu ?",
       options=["Ramadan", "Chawwal", "Dhou al-Hijja", "Rajab"], reponse=2),
  dict(q="Le calendrier musulman est-il basé sur le cycle solaire ou lunaire ?",
       options=["Solaire", "Lunaire", "Un mélange fixe des deux", "Ni l'un ni l'autre"], reponse=1,
       explication="C'est pourquoi les dates du Ramadan et de l'Aïd reculent chaque année dans le calendrier grégorien."),
  dict(q="Quelle prière additionnelle est traditionnellement accomplie la nuit pendant le mois de Ramadan ?",
       options=["Le tarawih", "Le tahajjud seul", "Le witr uniquement", "La Jumu'a"], reponse=0),

  # --- Batailles et événements clés ---
  dict(q="Comment se nomme la première grande bataille remportée par les musulmans de Médine, en 624 ?",
       options=["La bataille de Badr", "La bataille d'Uhud", "La bataille du Fossé", "La bataille de Hunayn"], reponse=0),
  dict(q="Quelle bataille de 625 vit les musulmans essuyer un revers face aux Mecquois ?",
       options=["La bataille de Badr", "La bataille d'Uhud", "La bataille du Fossé", "La bataille de Tabouk"], reponse=1),
  dict(q="Comment se nomme la bataille de 627 où les Médinois creusèrent une tranchée défensive autour de leur ville ?",
       options=["La bataille de Badr", "La bataille d'Uhud", "La bataille du Fossé (Khandaq)", "La bataille de Hunayn"], reponse=2),
  dict(q="Quel traité de 628, conclu entre les Mecquois et les musulmans, permit une trêve avant la conquête pacifique de La Mecque ?",
       options=["Le traité de Hudaybiya", "Le traité de Tabouk", "Le pacte de Médine", "Le traité de Ta'if"], reponse=0),
  dict(q="Quel document, rédigé peu après l'Hégire, organisa les relations entre les différentes communautés de Médine ?",
       options=["La Charte de Médine", "Le traité de Hudaybiya", "Le Pacte des Vertueux", "La Constitution de La Mecque"], reponse=0),
  dict(q="Quelle expédition tardive du vivant du Prophète visa les confins nord de l'Arabie, vers le territoire byzantin ?",
       options=["L'expédition de Badr", "L'expédition de Tabouk", "L'expédition d'Uhud", "L'expédition de Khaybar"], reponse=1),
  dict(q="Quelle oasis fut conquise par les musulmans en 628, connue pour ses palmeraies et forteresses juives ?",
       options=["Khaybar", "Ta'if", "Tabouk", "Najran"], reponse=0),
  dict(q="Après la conquête de La Mecque, quelle bataille opposa les musulmans à des tribus bédouines coalisées, en 630 ?",
       options=["La bataille de Hunayn", "La bataille de Badr", "La bataille d'Uhud", "La bataille du Fossé"], reponse=0),

  # --- Famille et société ---
  dict(q="Quelle fille du Prophète est particulièrement connue et vénérée dans l'ensemble du monde musulman ?",
       options=["Fatima", "Zaynab bint Jahsh", "Ruqayya", "Oum Kalthoum"], reponse=0,
       explication="Fatima, épouse d'Ali, est la fille du Prophète dont la postérité s'est perpétuée."),
  dict(q="Combien le Prophète a-t-il eu de filles parvenues à l'âge adulte, selon la tradition ?",
       options=["Une seule", "Deux", "Quatre", "Aucune"], reponse=2),
  dict(q="Quel est le nom du petit-fils du Prophète, fils d'Ali et de Fatima, dont le nom signifie « beau » ?",
       options=["Hassan", "Houssein", "Zayd", "Qassim"], reponse=0),
  dict(q="La notion de « Umma » désigne en islam :",
       options=["La communauté des croyants", "Un type de prière", "Un chapitre du Coran", "Un pèlerinage secondaire"], reponse=0),
  dict(q="Quel terme arabe désigne la loi islamique dans son ensemble ?",
       options=["La Charia", "Le Fiqh seul", "Le Kalam", "Le Tafsir"], reponse=0),
  dict(q="Quel terme désigne la profession de foi musulmane (« Il n'y a de dieu que Dieu... ») ?",
       options=["La Chahada", "La Salat", "La Niyya", "La Khutba"], reponse=0),

  # --- Lieux et pratiques ---
  dict(q="Quelles sont, selon la tradition sunnite, les trois mosquées vers lesquelles il est recommandé d'entreprendre un voyage pieux ?",
       options=["La Mecque, Médine et Jérusalem", "La Mecque, Istanbul et Le Caire", "Médine, Bagdad et Damas", "La Mecque, Kairouan et Fès"], reponse=0,
       explication="Un hadith rapporte qu'on ne doit entreprendre de voyage pieux que vers ces trois lieux saints."),
  dict(q="Comment se nomme l'appel à la prière lancé cinq fois par jour ?",
       options=["Le adhan", "Le khutba", "Le takbir", "Le tasbih"], reponse=0),
  dict(q="Comment se nomme la personne qui lance l'appel à la prière depuis la mosquée ?",
       options=["L'imam", "Le muezzin", "Le calife", "Le mufti"], reponse=1),
  dict(q="Comment se nomme la personne qui dirige la prière collective dans une mosquée ?",
       options=["Le muezzin", "L'imam", "Le mufti", "Le calife"], reponse=1),
  dict(q="Comment se nomme la niche murale d'une mosquée indiquant la direction de la prière ?",
       options=["Le minbar", "Le mihrab", "Le sahn", "Le mawqif"], reponse=1),
  dict(q="Comment se nomme la chaire d'où l'imam prononce le sermon du vendredi ?",
       options=["Le minbar", "Le mihrab", "Le mawqif", "Le liwan"], reponse=0),
  dict(q="Comment se nomme la cour intérieure à ciel ouvert d'une mosquée ?",
       options=["Le sahn", "Le liwan", "Le minbar", "Le mihrab"], reponse=0),
  dict(q="Comment se nomme le lieu où les fidèles font leurs ablutions rituelles avant la prière ?",
       options=["Le mida'a (ou lieu d'ablutions)", "Le minbar", "Le mawqif", "Le riwaq"], reponse=0),
  dict(q="Comment appelle-t-on les ablutions rituelles précédant la prière ?",
       options=["Le wudu", "Le tayammum uniquement", "Le ghusl uniquement", "Le tawaf"], reponse=0,
       explication="Le tayammum (ablution sèche) et le ghusl (grande ablution) sont d'autres formes d'ablution utilisées dans des circonstances particulières."),
]

# ============================================================== THÈME 2 : MOSQUÉES CÉLÈBRES
_MOSQUEES_CELEBRES = [
  # Masjid al-Haram
  dict(q="Dans quelle ville se trouve la Masjid al-Haram, qui entoure la Kaaba ?",
       options=["Médine", "La Mecque", "Jérusalem", "Le Caire"], reponse=1),
  dict(q="Quelle est la particularité de la Masjid al-Haram par rapport aux autres mosquées ?",
       options=["Elle n'a pas de minaret", "Elle entoure directement la Kaaba", "Elle est entièrement souterraine", "Elle n'accueille que les hommes"], reponse=1),
  dict(q="Qui a supervisé les principaux agrandissements modernes de la Masjid al-Haram ?",
       options=["La dynastie ottomane seule", "La dynastie saoudienne (Al Saoud)", "L'Empire moghol", "La dynastie fatimide"], reponse=1),
  dict(q="Que serait, selon la tradition, la Pierre noire enchâssée dans l'angle de la Kaaba ?",
       options=["Une météorite tombée du ciel à l'époque d'Adam", "Un cadeau de l'empereur byzantin", "Une pierre taillée par Salomon", "Un fragment du mont Sinaï"], reponse=0),
  dict(q="Quel puits, situé dans l'enceinte de la Masjid al-Haram, alimente les pèlerins en eau depuis des siècles ?",
       options=["Le puits de Badr", "Le puits de Zamzam", "Le puits de Hira", "Le puits de Khaybar"], reponse=1),

  # Masjid an-Nabawi
  dict(q="Dans quelle ville se trouve la Masjid an-Nabawi ?",
       options=["La Mecque", "Médine", "Damas", "Bagdad"], reponse=1),
  dict(q="Quelle couleur caractérise le dôme emblématique de la Masjid an-Nabawi ?",
       options=["Bleu", "Doré", "Vert", "Blanc"], reponse=2),
  dict(q="Qui est le fondateur originel de la Masjid an-Nabawi ?",
       options=["Le prophète Muhammad", "Le calife Omar", "Le calife Othman", "L'architecte Sinan"], reponse=0),
  dict(q="Quel équipement caractéristique protège aujourd'hui l'esplanade de la Masjid an-Nabawi du soleil ?",
       options=["Des voiles tendus en permanence", "250 parasols géants déployables", "Une verrière climatisée", "Des arbres centenaires"], reponse=1),
  dict(q="La Masjid an-Nabawi a été l'un des premiers lieux du monde arabe à bénéficier de quelle innovation, dès la fin du XIXe siècle ?",
       options=["L'éclairage électrique", "L'eau courante", "Le téléphone", "L'imprimerie"], reponse=0),

  # Al-Aqsa
  dict(q="Dans quelle ville se trouve la mosquée Al-Aqsa ?",
       options=["Le Caire", "Damas", "Jérusalem", "Amman"], reponse=2),
  dict(q="Sous quel calife omeyyade la mosquée Al-Aqsa actuelle est-elle édifiée, au début du VIIIe siècle ?",
       options=["Al-Walid Ier", "Omar ibn al-Khattab", "Mu'awiya", "Abd al-Malik"], reponse=0),
  dict(q="Que signifie le nom « Al-Aqsa » ?",
       options=["« La sacrée »", "« La plus éloignée »", "« La dorée »", "« La première »"], reponse=1),
  dict(q="Quel sanctuaire voisin, à la coupole dorée, est parfois confondu avec la mosquée Al-Aqsa elle-même ?",
       options=["Le Dôme du Rocher", "La mosquée Omeyyade", "La citadelle de David", "Le Saint-Sépulcre"], reponse=0),
  dict(q="Dans quel récit traditionnel la mosquée Al-Aqsa est-elle mentionnée comme destination du voyage nocturne du Prophète ?",
       options=["L'Isra et le Mi'raj", "L'Hégire", "Le Hajj", "La bataille du Fossé"], reponse=0),

  # Hassan II
  dict(q="Dans quelle ville se trouve la mosquée Hassan II ?",
       options=["Rabat", "Casablanca", "Marrakech", "Fès"], reponse=1),
  dict(q="Qui est l'architecte de la mosquée Hassan II ?",
       options=["Michel Pinseau", "Mimar Sinan", "Zaha Hadid", "Vedat Dalokay"], reponse=0),
  dict(q="En quelle année la mosquée Hassan II est-elle inaugurée ?",
       options=["1976", "1985", "1993", "2001"], reponse=2),
  dict(q="Quelle est la particularité de l'implantation de la mosquée Hassan II ?",
       options=["Elle est bâtie en partie sur l'océan Atlantique", "Elle est entièrement souterraine", "Elle est construite sur une île artificielle au large", "Elle n'a aucune fondation en mer"], reponse=0),
  dict(q="Quelle prouesse technique caractérise la salle de prière de la mosquée Hassan II ?",
       options=["Un toit ouvrant de plus de 1 000 tonnes", "Un sol entièrement chauffant", "Un minaret pivotant", "Une coupole rotative"], reponse=0),

  # Mosquée bleue
  dict(q="Dans quelle ville se trouve la Mosquée bleue (Sultan Ahmed) ?",
       options=["Ankara", "Istanbul", "Izmir", "Bursa"], reponse=1),
  dict(q="Combien de minarets compte la Mosquée bleue, un nombre exceptionnel à son époque ?",
       options=["Deux", "Quatre", "Six", "Huit"], reponse=2),
  dict(q="Qui est l'architecte de la Mosquée bleue ?",
       options=["Mimar Sinan", "Sedefkâr Mehmed Ağa", "Michel Pinseau", "Ahmad ibn Touloun"], reponse=1),
  dict(q="D'où vient le surnom « Mosquée bleue » ?",
       options=["De la couleur de son dôme extérieur", "Des milliers de carreaux de céramique d'Iznik qui ornent son intérieur", "De la couleur de son minaret", "D'un éclairage nocturne moderne"], reponse=1),
  dict(q="En quel siècle la Mosquée bleue a-t-elle été construite ?",
       options=["XVe siècle", "XVIe siècle", "XVIIe siècle", "XIXe siècle"], reponse=2),

  # Süleymaniye
  dict(q="Dans quelle ville se trouve la mosquée Süleymaniye ?",
       options=["Istanbul", "Le Caire", "Bagdad", "Konya"], reponse=0),
  dict(q="Qui est l'architecte de la mosquée Süleymaniye, considéré comme le plus grand architecte ottoman ?",
       options=["Mimar Sinan", "Sedefkâr Mehmed Ağa", "Vedat Dalokay", "Ahmad ibn Touloun"], reponse=0),
  dict(q="En l'honneur de quel sultan la mosquée Süleymaniye est-elle construite ?",
       options=["Soliman le Magnifique", "Mehmed le Conquérant", "Selim Ier", "Ahmed Ier"], reponse=0),
  dict(q="À quoi servait une pièce spéciale de la mosquée Süleymaniye collectant la suie des lampes à huile ?",
       options=["À fabriquer l'encre des calligraphes", "À teindre les tapis", "À produire de la peinture murale", "À alimenter le chauffage"], reponse=0),
  dict(q="En quel siècle la mosquée Süleymaniye a-t-elle été construite ?",
       options=["XIVe siècle", "XVIe siècle", "XVIIIe siècle", "XXe siècle"], reponse=1),

  # Cheikh Zayed
  dict(q="Dans quelle ville se trouve la mosquée Cheikh Zayed ?",
       options=["Dubaï", "Abou Dabi", "Doha", "Riyad"], reponse=1),
  dict(q="Combien de coupoles de marbre blanc compte environ la mosquée Cheikh Zayed ?",
       options=["12", "40", "82", "150"], reponse=2),
  dict(q="Quelle particularité caractérise le tapis de la salle de prière principale de la mosquée Cheikh Zayed ?",
       options=["C'est le plus grand tapis noué main du monde", "Il est tissé en or massif", "Il change de couleur selon l'heure", "Il est fait de plumes de paon"], reponse=0),
  dict(q="En quelle année la mosquée Cheikh Zayed est-elle achevée ?",
       options=["1985", "1999", "2007", "2015"], reponse=2),
  dict(q="Quel élément du lustre principal de la mosquée Cheikh Zayed est particulièrement remarquable ?",
       options=["Des cristaux Swarovski", "De l'or massif", "Des diamants", "Du bois sculpté"], reponse=0),

  # Cordoue
  dict(q="Dans quelle ville se trouve la mosquée-cathédrale de Cordoue ?",
       options=["Séville", "Grenade", "Cordoue", "Tolède"], reponse=2),
  dict(q="Sous quel dirigeant omeyyade la mosquée de Cordoue est-elle fondée en 785 ?",
       options=["Abd al-Rahman Ier", "Al-Walid Ier", "Abd al-Malik", "Mu'awiya"], reponse=0),
  dict(q="Quelle est la particularité architecturale la plus célèbre de la mosquée de Cordoue ?",
       options=["Ses arcs superposés bicolores", "Son unique coupole dorée", "Son absence totale de colonnes", "Son minaret spiralé"], reponse=0),
  dict(q="Qu'est devenue la mosquée de Cordoue après la Reconquista chrétienne ?",
       options=["Une cathédrale", "Un palais royal", "Une bibliothèque", "Elle a été détruite"], reponse=0),
  dict(q="Pourquoi de nombreuses colonnes de la mosquée de Cordoue ont-elles des hauteurs inégales ?",
       options=["Ce sont des réemplois de monuments romains et wisigothiques", "Une erreur de calcul de l'architecte", "Un tremblement de terre les a déplacées", "Elles ont été raccourcies au XIXe siècle"], reponse=0),

  # Jama Masjid
  dict(q="Dans quelle ville se trouve la Jama Masjid, l'une des plus grandes mosquées d'Inde ?",
       options=["Bombay", "Delhi", "Agra", "Lahore"], reponse=1),
  dict(q="Quel empereur moghol a commandé la construction de la Jama Masjid de Delhi ?",
       options=["Akbar", "Shah Jahan", "Aurangzeb", "Babur"], reponse=1),
  dict(q="En quels matériaux principaux la Jama Masjid de Delhi est-elle construite ?",
       options=["Grès rouge et marbre blanc", "Marbre noir uniquement", "Bois et terre crue", "Granit rose"], reponse=0),
  dict(q="Que signifie le nom officiel de la Jama Masjid, Masjid-i Jahan-Numa ?",
       options=["« La mosquée du désert »", "« La mosquée qui reflète le monde »", "« La mosquée éternelle »", "« La mosquée royale »"], reponse=1),
  dict(q="Quel monument célèbre de Delhi peut-on apercevoir depuis le sommet d'un des minarets de la Jama Masjid ?",
       options=["Le Fort rouge", "Le Taj Mahal", "Le Qutub Minar", "Le palais du Rajasthan"], reponse=0),

  # Badshahi
  dict(q="Dans quelle ville se trouve la mosquée Badshahi ?",
       options=["Islamabad", "Karachi", "Lahore", "Peshawar"], reponse=2),
  dict(q="Quel empereur moghol a commandé la construction de la mosquée Badshahi ?",
       options=["Shah Jahan", "Aurangzeb", "Akbar", "Humayun"], reponse=1),
  dict(q="Comment traduit-on le nom « Badshahi » ?",
       options=["« La mosquée du désert »", "« La mosquée impériale »", "« La mosquée sacrée »", "« La mosquée blanche »"], reponse=1),
  dict(q="À quel usage la mosquée Badshahi a-t-elle été détournée durant l'occupation sikhe puis britannique ?",
       options=["Une caserne et une poudrière", "Un hôpital militaire", "Un marché couvert", "Un tribunal"], reponse=0),
  dict(q="Comment les minarets de la mosquée Badshahi se comparent-ils à ceux du Taj Mahal ?",
       options=["Ils sont plus hauts", "Ils sont plus bas", "Ils ont exactement la même hauteur", "Le Taj Mahal n'a pas de minarets"], reponse=0),

  # Djenné
  dict(q="Dans quel pays se trouve la Grande Mosquée de Djenné ?",
       options=["Sénégal", "Mali", "Niger", "Burkina Faso"], reponse=1),
  dict(q="En quel matériau principal la Grande Mosquée de Djenné est-elle construite ?",
       options=["Marbre blanc", "Grès rose", "Banco (terre crue)", "Brique cuite émaillée"], reponse=2),
  dict(q="Comment appelle-t-on la cérémonie annuelle où toute la ville de Djenné ré-enduit la mosquée de terre fraîche ?",
       options=["Le crépissage", "La Omra locale", "Le tawaf communautaire", "La grande lessive"], reponse=0),
  dict(q="À quoi servent les torons de palmier qui hérissent les façades de la Grande Mosquée de Djenné ?",
       options=["D'échafaudages permanents pour l'entretien", "De paratonnerres", "De supports pour des lanternes", "De simples décorations sans fonction"], reponse=0),
  dict(q="En quelle année la Grande Mosquée de Djenné, dans sa forme actuelle, a-t-elle été reconstruite ?",
       options=["1650", "1820", "1907", "1960"], reponse=2),

  # Faisal
  dict(q="Dans quelle ville se trouve la mosquée Faisal ?",
       options=["Karachi", "Lahore", "Islamabad", "Peshawar"], reponse=2),
  dict(q="Quelle forme originale caractérise la mosquée Faisal, sans dôme ni arc traditionnels ?",
       options=["Une forme de tente bédouine", "Une forme de pyramide", "Une forme de spirale", "Une forme de bateau"], reponse=0),
  dict(q="Qui est l'architecte de la mosquée Faisal ?",
       options=["Vedat Dalokay", "Michel Pinseau", "Mimar Sinan", "Zaha Hadid"], reponse=0),
  dict(q="Parmi combien de propositions internationales le projet de la mosquée Faisal a-t-il été choisi ?",
       options=["5", "12", "43", "100"], reponse=2),
  dict(q="En quelle décennie la mosquée Faisal est-elle achevée ?",
       options=["Les années 1960", "Les années 1980", "Les années 2000", "Les années 2010"], reponse=1),

  # Al-Azhar
  dict(q="Dans quelle ville se trouve la mosquée Al-Azhar ?",
       options=["Alexandrie", "Le Caire", "Louxor", "Assouan"], reponse=1),
  dict(q="En quel siècle la mosquée Al-Azhar est-elle fondée ?",
       options=["VIIIe siècle", "Xe siècle", "XIIe siècle", "XVe siècle"], reponse=1),
  dict(q="Quelle dynastie a fondé la mosquée Al-Azhar ?",
       options=["Les Fatimides", "Les Omeyyades", "Les Abbassides", "Les Mamelouks"], reponse=0),
  dict(q="Au-delà de son rôle religieux, quelle autre fonction majeure la mosquée Al-Azhar a-t-elle développée au fil des siècles ?",
       options=["Une forteresse militaire", "Une université, aujourd'hui un centre d'enseignement sunnite reconnu", "Un marché international", "Un observatoire astronomique"], reponse=1),
  dict(q="D'où viendrait le nom « Al-Azhar » (« la resplendissante ») selon la tradition ?",
       options=["D'un jeu de lumière unique dans la cour", "D'une référence à Fatima al-Zahra, fille du Prophète", "D'une pierre précieuse enchâssée au mihrab", "Du nom de son premier calligraphe"], reponse=1),

  # Ibn Touloun
  dict(q="Dans quelle ville se trouve la mosquée Ibn Touloun ?",
       options=["Le Caire", "Alexandrie", "Damas", "Bagdad"], reponse=0),
  dict(q="Quelle est la particularité du minaret de la mosquée Ibn Touloun, unique en Égypte ?",
       options=["Un escalier extérieur en spirale", "L'absence totale de minaret", "Un minaret pivotant", "Un minaret entièrement doré"], reponse=0),
  dict(q="Qui a commandé la construction de la mosquée Ibn Touloun, achevée vers 879 ?",
       options=["Ahmad ibn Touloun", "Saladin", "Jawhar al-Siqilli", "Al-Walid Ier"], reponse=0),
  dict(q="Selon la légende locale, à quel événement biblique/coranique la colline sur laquelle repose la mosquée serait-elle associée ?",
       options=["L'endroit où l'arche de Noé se serait posée", "Le lieu de naissance d'un prophète", "Le site d'une ancienne bataille", "Le tombeau d'un roi pharaon"], reponse=0),
  dict(q="En quel style architectural la mosquée Ibn Touloun a-t-elle été édifiée ?",
       options=["Style abbasside", "Style ottoman", "Style moghol", "Style andalou"], reponse=0),

  # Kairouan
  dict(q="Dans quel pays se trouve la Grande Mosquée de Kairouan ?",
       options=["Maroc", "Algérie", "Tunisie", "Libye"], reponse=2),
  dict(q="Qui a fondé la Grande Mosquée de Kairouan, vers 670 ?",
       options=["Uqba ibn Nafi", "Abd al-Rahman Ier", "Jawhar al-Siqilli", "Ahmad ibn Touloun"], reponse=0),
  dict(q="Quelle particularité présente le minaret de la Grande Mosquée de Kairouan ?",
       options=["Il serait le plus ancien minaret encore debout", "Il est entièrement en bois", "Il n'a jamais été terminé", "Il est incliné volontairement"], reponse=0),
  dict(q="D'où proviennent de nombreuses colonnes en marbre et porphyre de la Grande Mosquée de Kairouan ?",
       options=["De sites romains et byzantins comme Carthage", "De carrières locales exclusivement", "D'Andalousie", "De Perse"], reponse=0),
  dict(q="La Grande Mosquée de Kairouan est souvent présentée comme :",
       options=["Le plus récent sanctuaire du monde musulman", "Le plus ancien grand sanctuaire de l'Occident musulman", "Une mosquée entièrement moderne", "Une mosquée construite au XXe siècle"], reponse=1),

  # Koutoubia
  dict(q="Dans quelle ville se trouve la mosquée Koutoubia ?",
       options=["Fès", "Rabat", "Marrakech", "Tanger"], reponse=2),
  dict(q="Quelle dynastie a fait édifier le minaret de la Koutoubia, achevé vers 1195 ?",
       options=["Les Almohades", "Les Fatimides", "Les Omeyyades", "Les Mamelouks"], reponse=0),
  dict(q="Quels autres monuments célèbres le minaret de la Koutoubia a-t-il inspirés ?",
       options=["La Giralda de Séville et la tour Hassan de Rabat", "La tour Eiffel", "Le Big Ben de Londres", "Le Colisée de Rome"], reponse=0),
  dict(q="Selon la légende, en quoi seraient faites les trois boules dorées au sommet du minaret de la Koutoubia ?",
       options=["En or fondu des bijoux d'une épouse de sultan, en pénitence", "En bronze importé d'Andalousie", "En cuivre offert par des marchands", "En argent massif"], reponse=0),
  dict(q="Comment le muezzin pouvait-il historiquement monter au sommet du minaret de la Koutoubia ?",
       options=["Par une rampe intérieure, à cheval", "Par un ascenseur mécanique", "Par une échelle de corde", "Il ne montait jamais, un assistant s'en chargeait"], reponse=0),

  # Nasir al-Mulk
  dict(q="Dans quelle ville se trouve la mosquée Nasir al-Mulk ?",
       options=["Ispahan", "Chiraz", "Téhéran", "Yazd"], reponse=1),
  dict(q="Pourquoi la mosquée Nasir al-Mulk est-elle surnommée « mosquée rose » ?",
       options=["Ses murs extérieurs sont peints en rose", "Ses vitraux colorés projettent des motifs kaléidoscopiques le matin", "Elle est entourée de jardins de roses", "Son dôme est en pierre rose"], reponse=1),
  dict(q="En quel siècle la mosquée Nasir al-Mulk a-t-elle été construite ?",
       options=["XIIe siècle", "XVe siècle", "XIXe siècle", "XXe siècle"], reponse=2),
  dict(q="À quel moment de la journée le spectacle des vitraux de la mosquée Nasir al-Mulk est-il le plus visible ?",
       options=["Tôt le matin", "En plein midi", "Au coucher du soleil", "La nuit, grâce à un éclairage artificiel"], reponse=0),
  dict(q="Sous quelle dynastie iranienne la mosquée Nasir al-Mulk a-t-elle été édifiée ?",
       options=["Safavide", "Qajar", "Sassanide", "Ottomane"], reponse=1),

  # Cheikh Lotfollah
  dict(q="Dans quelle ville se trouve la mosquée Cheikh Lotfollah ?",
       options=["Chiraz", "Ispahan", "Téhéran", "Tabriz"], reponse=1),
  dict(q="Quelle particularité distingue la mosquée Cheikh Lotfollah des autres grandes mosquées ?",
       options=["Elle n'a ni minaret ni cour", "Elle n'a pas de dôme", "Elle est entièrement souterraine", "Elle est ouverte uniquement la nuit"], reponse=0,
       explication="C'était une mosquée privée réservée à la cour royale safavide, d'où l'absence de cour et de minaret."),
  dict(q="Quel effet optique célèbre peut-on observer depuis l'entrée de la salle de la mosquée Cheikh Lotfollah ?",
       options=["La forme d'un paon formée par le jeu de lumière sur le dôme", "Un arc-en-ciel permanent", "Une ombre en forme d'étoile", "Un reflet du soleil couchant sur le mihrab"], reponse=0),
  dict(q="Pourquoi le couloir d'accès à la salle de la mosquée Cheikh Lotfollah est-il volontairement coudé et sombre ?",
       options=["Pour renforcer l'éblouissement à la découverte de la coupole", "Pour des raisons défensives", "Pour économiser les matériaux", "Par erreur de conception jamais corrigée"], reponse=0),
  dict(q="Sous quelle dynastie la mosquée Cheikh Lotfollah a-t-elle été construite, au début du XVIIe siècle ?",
       options=["Safavide", "Qajar", "Ottomane", "Moghole"], reponse=0),

  # Putra
  dict(q="Dans quel pays se trouve la mosquée Putra ?",
       options=["Indonésie", "Malaisie", "Brunei", "Singapour"], reponse=1),
  dict(q="Sur quel élément naturel la mosquée Putra est-elle en grande partie construite ?",
       options=["Un lac artificiel", "Une colline", "Une falaise", "Une île volcanique"], reponse=0),
  dict(q="En quelle matière principale la mosquée Putra est-elle construite, lui donnant une teinte rosée ?",
       options=["Granit rose", "Marbre blanc", "Grès rouge", "Bois laqué"], reponse=0),
  dict(q="Combien d'étages compte le minaret de la mosquée Putra, symbolisant les piliers de l'islam ?",
       options=["Trois", "Cinq", "Sept", "Neuf"], reponse=1),
  dict(q="En quelle année la mosquée Putra est-elle achevée ?",
       options=["1985", "1999", "2005", "2012"], reponse=1),

  # Xi'an
  dict(q="Dans quel pays se trouve la Grande Mosquée de Xi'an ?",
       options=["Chine", "Ouzbékistan", "Mongolie", "Kazakhstan"], reponse=0),
  dict(q="Quelle est la particularité architecturale majeure de la Grande Mosquée de Xi'an ?",
       options=["Elle n'a ni dôme ni minaret visibles, dans un style de temple chinois", "Elle a huit minarets", "Elle est entièrement blanche", "Elle est construite sur pilotis"], reponse=0),
  dict(q="Sous quelle dynastie la Grande Mosquée de Xi'an aurait-elle été fondée, selon la tradition ?",
       options=["Les Tang", "Les Ming uniquement", "Les Qing uniquement", "Les Song"], reponse=0),
  dict(q="Dans quelle direction l'axe de la Grande Mosquée de Xi'an est-il orienté, à l'inverse des temples chinois classiques ?",
       options=["Nord-sud", "Est-ouest, vers La Mecque", "Aucune orientation particulière", "Vers le centre-ville"], reponse=1),
  dict(q="Sur certaines stèles de la Grande Mosquée de Xi'an, en quelles langues un même texte est-il parfois gravé ?",
       options=["Arabe et chinois classique", "Persan et turc", "Sanskrit et arabe", "Mongol et arabe"], reponse=0),

  # --- Deuxième série de questions par mosquée ---

  # Masjid al-Haram
  dict(q="Quelle tour, voisine de la Masjid al-Haram, porte l'un des plus grands cadrans d'horloge du monde ?",
       options=["La tour Al-Faisaliah", "L'Abraj Al Bait", "La tour du Zamzam", "Le minaret royal"], reponse=1),
  dict(q="Quelle capacité peut atteindre la Masjid al-Haram lors du pèlerinage ?",
       options=["Environ 200 000 fidèles", "Environ 500 000 fidèles", "Plus de 2 000 000 de fidèles", "Environ 1 000 fidèles"], reponse=2),

  # Masjid an-Nabawi
  dict(q="Que désigne la « Rawda », espace vénéré au sein de la Masjid an-Nabawi ?",
       options=["Le jardin du Paradis, entre le mihrab et la tombe du Prophète", "Le minaret principal", "La bibliothèque de la mosquée", "L'entrée réservée aux pèlerins étrangers"], reponse=0),
  dict(q="Qui a fondé la Masjid an-Nabawi, en 622 ?",
       options=["Le calife Omar", "Le prophète Muhammad", "Le calife Othman", "Le calife Abou Bakr"], reponse=1),

  # Al-Aqsa
  dict(q="En quel siècle la mosquée Al-Aqsa actuelle est-elle édifiée sous le calife al-Walid Ier ?",
       options=["VIIe siècle", "VIIIe siècle", "Xe siècle", "XIIe siècle"], reponse=1),
  dict(q="D'où proviennent certaines colonnes de marbre de la salle de prière d'Al-Aqsa ?",
       options=["D'édifices byzantins et romains réemployés", "Elles ont toutes été taillées sur place au VIIIe siècle", "D'un temple perse démonté", "D'une carrière locale unique"], reponse=0),

  # Hassan II
  dict(q="Sur quelle distance environ le laser du minaret de la mosquée Hassan II balaie-t-il le ciel la nuit, en direction de La Mecque ?",
       options=["Une dizaine de kilomètres", "Une trentaine de kilomètres", "Une centaine de kilomètres", "Un kilomètre"], reponse=1),
  dict(q="Quelle capacité totale (intérieur et esplanade) peut accueillir la mosquée Hassan II ?",
       options=["Environ 10 000 fidèles", "Environ 25 000 fidèles à l'intérieur, 80 000 sur l'esplanade", "Environ 5 000 fidèles au total", "Environ 200 000 fidèles à l'intérieur"], reponse=1),

  # Mosquée bleue
  dict(q="Quelle légende circule sur l'origine du nombre de minarets de la Mosquée bleue ?",
       options=["L'architecte aurait confondu « or » et « six » dans les ordres du sultan", "Le sultan en voulait dix mais le budget a été réduit", "Chaque minaret représente un continent", "Aucune légende n'existe à ce sujet"], reponse=0),
  dict(q="En quelle période la Mosquée bleue est-elle construite ?",
       options=["1450-1453", "1609-1616", "1700-1710", "1850-1860"], reponse=1),

  # Süleymaniye
  dict(q="À quoi servait la suie collectée dans une pièce spéciale de la mosquée Süleymaniye ?",
       options=["À fabriquer l'encre des calligraphes", "À teindre les tapis", "À l'éclairage nocturne", "À aucun usage particulier"], reponse=0),
  dict(q="Quel âge avait approximativement l'architecte Sinan lorsqu'il acheva la Süleymaniye ?",
       options=["Une vingtaine d'années", "Une quarantaine d'années", "Une soixantaine d'années", "Une soixante-dizaine d'années"], reponse=3),

  # Cheikh Zayed
  dict(q="Combien d'artisanes ont noué à la main le tapis de la salle de prière de la mosquée Cheikh Zayed ?",
       options=["Environ 200", "Environ 1 200", "Environ 5 000", "Environ 50"], reponse=1),
  dict(q="Que suit le système d'éclairage projetant des nuages sur le marbre blanc de la mosquée Cheikh Zayed ?",
       options=["Les phases de la lune", "Les heures de prière", "La météo en temps réel", "Le rythme des saisons"], reponse=0),

  # Cordoue
  dict(q="Quelle phrase Charles Quint aurait-il prononcée après avoir vu la cathédrale construite dans la mosquée de Cordoue ?",
       options=["« Vous avez détruit ce qui était unique au monde »", "« C'est un chef d'œuvre absolu »", "« Il fallait la démolir entièrement »", "Aucune phrase ne lui est attribuée"], reponse=0),
  dict(q="Pourquoi de nombreuses colonnes de la mosquée de Cordoue ont-elles des hauteurs inégales ?",
       options=["Ce sont des réemplois romains et wisigothiques, compensés par des arcs superposés", "Elles ont été endommagées par un séisme", "C'est un choix esthétique voulu dès l'origine", "Elles ont été remplacées à des époques différentes sans souci d'harmonie"], reponse=0),

  # Jama Masjid
  dict(q="Que signifie le nom officiel de la Jama Masjid, Masjid-i Jahan-Numa ?",
       options=["« La mosquée qui reflète le monde »", "« La mosquée du roi »", "« La grande mosquée de pierre »", "« La mosquée aux mille colonnes »"], reponse=0),
  dict(q="Qui a commandé la construction de la Jama Masjid de Delhi ?",
       options=["Akbar", "Shah Jahan", "Aurangzeb", "Babur"], reponse=1),

  # Badshahi
  dict(q="À quel usage la mosquée Badshahi a-t-elle été détournée à l'époque sikhe puis britannique ?",
       options=["Caserne et poudrière", "Marché couvert", "Hôpital militaire", "Prison"], reponse=0),
  dict(q="Qui a commandé la construction de la mosquée Badshahi de Lahore ?",
       options=["Shah Jahan", "Aurangzeb", "Akbar", "Jahangir"], reponse=1),

  # Djenné
  dict(q="Que symbolisent traditionnellement les œufs d'autruche placés au sommet des pinacles de la mosquée de Djenné ?",
       options=["Fertilité et pureté", "Richesse et pouvoir", "Protection contre la foudre", "Aucun symbole particulier"], reponse=0),
  dict(q="En quelle année la mosquée de Djenné actuelle, reconstruite, est-elle achevée ?",
       options=["1850", "1907", "1950", "1980"], reponse=1),

  # Faisal
  dict(q="Parmi combien de propositions internationales le projet de Vedat Dalokay pour la mosquée Faisal a-t-il été choisi ?",
       options=["Une dizaine", "43 propositions de 17 pays", "Une centaine de pays", "Aucune autre proposition n'a été soumise"], reponse=1),
  dict(q="Quel élément se trouve dans l'enceinte de l'esplanade de la mosquée Faisal, à Islamabad ?",
       options=["Le mausolée du général Zia ul-Haq", "Un musée national", "Une ancienne forteresse moghole", "Un jardin botanique"], reponse=0),

  # Al-Azhar
  dict(q="D'où viendrait le nom « Al-Azhar » (« la resplendissante ») ?",
       options=["Une référence à Fatima al-Zahra, fille du Prophète", "Le nom de l'architecte fondateur", "La couleur dorée de sa façade", "Le nom de la dynastie ottomane"], reponse=0),
  dict(q="Combien de minarets, construits à des époques différentes, compte la mosquée Al-Azhar ?",
       options=["Un seul", "Deux", "Cinq", "Dix"], reponse=2),

  # Ibn Touloun
  dict(q="Sur quelle colline la mosquée Ibn Touloun aurait-elle été bâtie, selon la tradition locale ?",
       options=["La colline de Yashkur, où l'arche de Noé se serait posée", "La colline de Moqattam", "La colline des Pyramides", "Aucune tradition ne s'y attache"], reponse=0),
  dict(q="La mosquée Ibn Touloun a servi de décor à quel type de production, par le passé ?",
       options=["Un film de la saga James Bond", "Une série documentaire uniquement", "Aucune production audiovisuelle", "Un jeu vidéo uniquement"], reponse=0),

  # Kairouan
  dict(q="Qui est le fondateur de la Grande Mosquée de Kairouan, vers 670 ?",
       options=["Uqba ibn Nafi", "Ahmad ibn Touloun", "Abd al-Rahman Ier", "Jawhar al-Siqilli"], reponse=0),
  dict(q="D'où proviennent certaines colonnes de marbre et de porphyre de la mosquée de Kairouan ?",
       options=["De sites romains et byzantins comme Carthage", "Elles ont toutes été taillées sur place", "D'un temple perse démonté", "D'Andalousie"], reponse=0),

  # Koutoubia
  dict(q="Que représenteraient, selon la légende, les trois boules dorées au sommet du minaret de la Koutoubia ?",
       options=["L'or fondu des bijoux d'une épouse de sultan, en pénitence", "Les trois piliers de la dynastie almohade", "Un cadeau d'un émir andalou", "Aucune légende ne s'y attache"], reponse=0),
  dict(q="Comment le muezzin accédait-il traditionnellement au sommet du minaret de la Koutoubia ?",
       options=["Par un escalier étroit à pied", "Par une rampe intérieure, à cheval", "Par un ascenseur mécanique", "Il n'y montait jamais"], reponse=1),

  # Nasir al-Mulk
  dict(q="À quel moment de la journée le spectacle des vitraux de la mosquée Nasir al-Mulk est-il le plus visible ?",
       options=["Tôt le matin", "En milieu d'après-midi", "Au coucher du soleil", "Uniquement la nuit"], reponse=0),
  dict(q="Qui continue de gérer la fondation qui entretient la mosquée Nasir al-Mulk ?",
       options=["Les descendants de son commanditaire", "L'État iranien uniquement", "Une organisation internationale", "Personne, elle est à l'abandon"], reponse=0),

  # Cheikh Lotfollah
  dict(q="Quelle forme évoque le reflet de lumière qui se déploie sous le dôme de la mosquée Cheikh Lotfollah ?",
       options=["La queue déployée d'un paon", "Une rose des sables", "Un tapis volant", "Une étoile à huit branches"], reponse=0),
  dict(q="Pourquoi le couloir d'accès à la mosquée Cheikh Lotfollah est-il volontairement coudé et sombre ?",
       options=["Pour renforcer l'éblouissement en découvrant la coupole", "Pour des raisons défensives", "Pour économiser des matériaux", "Aucune raison particulière"], reponse=0),

  # Putra
  dict(q="Sur quelle proportion de sa surface la mosquée Putra repose-t-elle au-dessus du lac ?",
       options=["Un quart", "La moitié", "Les trois quarts", "Elle ne touche pas le lac"], reponse=2),
  dict(q="Que symbolise le minaret à cinq étages de la mosquée Putra ?",
       options=["Les cinq piliers de l'islam", "Les cinq prières quotidiennes uniquement", "Les cinq États fondateurs de la Malaisie", "Aucun symbole particulier"], reponse=0),

  # Xi'an
  dict(q="Dans quel quartier de Xi'an la Grande Mosquée se trouve-t-elle, toujours en activité ?",
       options=["Le quartier musulman hui", "Le quartier impérial", "Le quartier chrétien", "Le quartier bouddhiste"], reponse=0),
  dict(q="En quelle langue certaines stèles de la Grande Mosquée de Xi'an portent-elles un texte gravé, en plus de l'arabe ?",
       options=["Le chinois classique", "Le persan", "Le mongol", "Le tibétain"], reponse=0),
]

# ============================================================== THÈME 3 : LES PROPHÈTES DE L'ISLAM
_PROPHETES_ISLAM = [
  # Adam
  dict(q="Quel est, selon la tradition islamique, le premier homme et premier prophète ?",
       options=["Idris", "Adam", "Noé", "Seth"], reponse=1),
  dict(q="Comment se nomme l'épouse d'Adam dans la tradition islamique ?",
       options=["Hawwa (Ève)", "Sarah", "Hajar", "Maryam"], reponse=0),
  dict(q="Que Dieu aurait-il enseigné à Adam, le distinguant des anges selon le récit coranique ?",
       options=["Les noms de toute chose", "L'art de la guerre", "L'écriture uniquement", "La navigation"], reponse=0),
  dict(q="Que se serait-il passé après qu'Adam et Hawwa eurent cédé à la tentation dans le jardin ?",
       options=["Ils furent élevés au rang d'anges", "Ils furent renvoyés sur terre", "Rien, l'épisode n'a aucune suite", "Ils devinrent immortels"], reponse=1),

  # Idris
  dict(q="Pour quelle qualité le prophète Idris est-il particulièrement connu dans la tradition islamique ?",
       options=["Sa grande sagesse et son savoir", "Sa force physique", "Sa richesse", "Son habileté militaire"], reponse=0),
  dict(q="Le prophète Idris est parfois associé, dans la tradition, à quelle autre figure des récits bibliques ?",
       options=["Hénoch", "Élie", "Moïse", "Salomon"], reponse=0),
  dict(q="Que dit le Coran du rang accordé à Idris ?",
       options=["Il a été élevé à un haut rang", "Il a été banni", "Il n'est jamais mentionné", "Il a régné sur un royaume"], reponse=0),
  dict(q="Idris est-il compté, dans la tradition, parmi les prophètes ayant précédé Noé ?",
       options=["Oui", "Non, il vient après Noé", "Non, il est contemporain de Moïse", "La tradition ne le classe pas dans le temps"], reponse=0),

  # Nuh (Noé)
  dict(q="Quel prophète aurait survécu à un grand déluge grâce à une arche ?",
       options=["Houd", "Salih", "Nuh (Noé)", "Loth"], reponse=2),
  dict(q="Pendant combien d'années, selon la tradition coranique, Nuh aurait-il prêché avant le déluge ?",
       options=["Environ 50 ans", "Environ 100 ans", "Environ 950 ans", "Environ 10 ans"], reponse=2),
  dict(q="Que serait-il arrivé au fils de Nuh qui refusa de monter dans l'arche ?",
       options=["Il fut sauvé in extremis", "Il périt dans le déluge", "Il devint prophète à son tour", "Il partit vivre ailleurs"], reponse=1),
  dict(q="Que transportait l'arche de Nuh, selon le récit traditionnel ?",
       options=["Sa famille croyante et un couple de chaque espèce animale", "Uniquement sa famille", "Uniquement des vivres", "Des trésors royaux"], reponse=0),

  # Hud
  dict(q="À quel peuple le prophète Hud a-t-il été envoyé ?",
       options=["Le peuple de 'Ad", "Le peuple de Thamud", "Le peuple de Madyan", "Le peuple de Sodome"], reponse=0),
  dict(q="De quel vice le peuple de 'Ad est-il accusé dans le récit coranique concernant Hud ?",
       options=["L'arrogance et l'idolâtrie", "La pauvreté extrême", "L'absence de tout commerce", "Le nomadisme"], reponse=0),
  dict(q="Par quel phénomène le peuple de 'Ad aurait-il été détruit, selon la tradition ?",
       options=["Un vent violent et destructeur", "Un tremblement de terre", "Une inondation", "Une invasion étrangère"], reponse=0),
  dict(q="Le peuple de 'Ad, auquel Hud fut envoyé, est réputé pour :",
       options=["Sa grande stature physique et ses constructions imposantes", "Sa vie exclusivement maritime", "Son absence totale d'habitat fixe", "Sa petite taille"], reponse=0),

  # Salih
  dict(q="À quel peuple le prophète Salih a-t-il été envoyé ?",
       options=["Le peuple de 'Ad", "Le peuple de Thamud", "Le peuple de Madyan", "Le peuple de Ninive"], reponse=1),
  dict(q="Quel miracle est associé au prophète Salih ?",
       options=["Une chamelle surgie miraculeusement d'un rocher", "La traversée d'une mer", "La résurrection d'un mort", "La pluie de manne"], reponse=0),
  dict(q="Que fit le peuple de Thamud à la chamelle miraculeuse, provoquant leur châtiment ?",
       options=["Ils la vénérèrent", "Ils la tuèrent (la hamstrent)", "Ils l'offrirent en cadeau", "Ils l'élevèrent avec soin"], reponse=1),
  dict(q="Par quel phénomène le peuple de Thamud aurait-il été anéanti ?",
       options=["Un cri ou une secousse foudroyante (la Sayha)", "Une famine prolongée", "Une guerre civile", "Un exil forcé"], reponse=0),

  # Ibrahim (Abraham)
  dict(q="Quel prophète est associé à la (re)construction de la Kaaba avec son fils Ismaël ?",
       options=["Ibrahim (Abraham)", "Ishaq (Isaac)", "Yaqub (Jacob)", "Dawud (David)"], reponse=0),
  dict(q="Que serait-il arrivé à Ibrahim lorsqu'il fut jeté dans un grand feu par son peuple, selon la tradition ?",
       options=["Il en mourut en martyr", "Le feu se fit frais et sûr pour lui, il en sortit indemne", "Il fut sauvé par des anges qui l'emportèrent au ciel", "Il ne fut jamais jeté au feu"], reponse=1),
  dict(q="Quel geste d'Ibrahim envers son fils, sur ordre divin dans un songe, est commémoré par l'Aïd al-Adha ?",
       options=["Sa disposition à le sacrifier, remplacée par un bélier", "Son départ en exil avec lui", "Sa bénédiction publique", "Son mariage arrangé"], reponse=0),
  dict(q="Ibrahim est traditionnellement considéré comme la figure fondatrice de :",
       options=["Le monothéisme abrahamique", "Le polythéisme arabe", "L'astrologie", "Le commerce caravanier"], reponse=0),

  # Lut (Lot)
  dict(q="Quel lien de parenté unit le prophète Lut au prophète Ibrahim, selon la tradition ?",
       options=["Il est son neveu", "Il est son frère", "Il est son fils", "Aucun lien"], reponse=0),
  dict(q="Vers quelle cité corrompue le prophète Lut a-t-il été envoyé ?",
       options=["Sodome (et les cités de la plaine)", "Ninive", "Babylone", "Thamud"], reponse=0),
  dict(q="Que serait-il arrivé à l'épouse de Lut lors de la destruction de la cité ?",
       options=["Elle fut sauvée avec lui", "Elle périt, n'ayant pas cru en son message", "Elle devint prophétesse", "Elle s'enfuit vers l'Égypte"], reponse=1),
  dict(q="Comment la cité de Lut aurait-elle été détruite, selon le récit traditionnel ?",
       options=["Elle fut submergée par la mer", "Elle fut renversée et frappée d'une pluie de pierres", "Elle brûla dans un incendie naturel", "Elle fut abandonnée progressivement"], reponse=1),

  # Ismail (Ismaël)
  dict(q="Qui sont les parents du prophète Ismaël, selon la tradition islamique ?",
       options=["Ibrahim et Hajar", "Ibrahim et Sarah", "Ishaq et Rifqa", "Yaqub et Rahil"], reponse=0),
  dict(q="Quel puits, toujours visible à La Mecque, est associé à la soif d'Ismaël enfant ?",
       options=["Le puits de Zamzam", "Le puits de Badr", "Le puits de Khaybar", "Le puits de Hira"], reponse=0),
  dict(q="Avec quel autre prophète Ismaël aurait-il élevé les fondations de la Kaaba ?",
       options=["Son père Ibrahim", "Son frère Ishaq", "Moïse", "Noé"], reponse=0),
  dict(q="La lignée d'Ismaël est traditionnellement rattachée à quel peuple ?",
       options=["Les tribus arabes, dont celle du prophète Muhammad", "Les tribus perses", "Les tribus grecques", "Les tribus égyptiennes uniquement"], reponse=0),

  # Ishaq (Isaac)
  dict(q="Qui est le père du prophète Ishaq, selon la tradition islamique ?",
       options=["Ibrahim", "Ismail", "Loth", "Noé"], reponse=0),
  dict(q="Qui est la mère du prophète Ishaq ?",
       options=["Hajar", "Sarah", "Rifqa", "Rahil"], reponse=1),
  dict(q="Quel est le fils du prophète Ishaq, lui-même prophète ?",
       options=["Yaqub (Jacob)", "Yusuf (Joseph)", "Ismail", "Moussa"], reponse=0),
  dict(q="Ishaq et Ismail sont-ils, selon la tradition islamique, tous deux considérés comme prophètes ?",
       options=["Oui, tous les deux", "Seul Ismail l'est", "Seul Ishaq l'est", "Aucun des deux"], reponse=0),

  # Yaqub (Jacob)
  dict(q="Sous quel autre nom le prophète Yaqub est-il également connu ?",
       options=["Israël", "Ismaël", "Yunus", "Idris"], reponse=0),
  dict(q="Combien de fils, à l'origine des douze tribus, Yaqub aurait-il eus selon la tradition ?",
       options=["Sept", "Dix", "Douze", "Vingt"], reponse=2),
  dict(q="Quel fils de Yaqub, disparu puis retrouvé, cause son immense chagrin dans le récit coranique ?",
       options=["Yusuf (Joseph)", "Benyamin uniquement", "Ruben", "Lévi"], reponse=0),
  dict(q="Que serait-il arrivé aux yeux de Yaqub à force de pleurer la disparition de son fils ?",
       options=["Il aurait perdu la vue", "Il serait devenu sourd", "Rien de particulier", "Il aurait perdu la mémoire"], reponse=0),

  # Yusuf (Joseph)
  dict(q="Que firent les frères de Yusuf, jaloux de lui, selon le récit coranique ?",
       options=["Ils le vendirent comme esclave", "Ils le chassèrent du pays", "Ils l'emprisonnèrent chez leur père", "Ils l'envoyèrent étudier à l'étranger"], reponse=0),
  dict(q="Dans quel pays Yusuf finit-il par accéder à une haute fonction, selon la tradition ?",
       options=["L'Égypte", "La Perse", "La Grèce", "Babylone"], reponse=0),
  dict(q="Quelle qualité particulière de Yusuf lui permet de gagner la confiance du souverain d'Égypte ?",
       options=["L'interprétation des rêves", "La force militaire", "L'éloquence poétique", "La richesse héritée"], reponse=0),
  dict(q="Quelle sourate du Coran est entièrement consacrée au récit de Yusuf, un cas unique pour un prophète ?",
       options=["Sourate Yusuf", "Sourate Al-Baqara", "Sourate Al-Kahf", "Sourate Maryam"], reponse=0),

  # Ayyub (Job)
  dict(q="Pour quelle qualité le prophète Ayyub est-il resté un modèle dans la tradition islamique ?",
       options=["Sa patience face à l'épreuve et la maladie", "Sa richesse", "Son éloquence", "Sa bravoure au combat"], reponse=0),
  dict(q="Qu'aurait perdu Ayyub avant que Dieu ne le récompense de sa patience ?",
       options=["Sa santé, ses biens et ses proches", "Uniquement sa fortune", "Uniquement sa réputation", "Rien, il fut toujours préservé"], reponse=0),
  dict(q="Comment se termine, selon la tradition, l'épreuve du prophète Ayyub ?",
       options=["Dieu lui rend la santé et une famille", "Il meurt dans l'épreuve", "Il perd définitivement la foi", "Il part en exil"], reponse=0),
  dict(q="Le récit d'Ayyub est souvent cité en islam comme un exemple de :",
       options=["Sabr (la patience endurante)", "Jihad militaire", "Hijra (migration)", "Ijtihad (effort d'interprétation)"], reponse=0),

  # Shu'ayb
  dict(q="À quel peuple le prophète Shu'ayb a-t-il été envoyé ?",
       options=["Madyan", "Thamud", "'Ad", "Ninive"], reponse=0),
  dict(q="Quel vice économique le prophète Shu'ayb reproche-t-il particulièrement à son peuple ?",
       options=["La fraude sur les poids et mesures dans le commerce", "Le refus total de commercer", "L'excès d'aumônes", "L'interdiction de l'agriculture"], reponse=0),
  dict(q="Shu'ayb est parfois associé, dans certaines traditions, à quel autre prophète comme beau-père ?",
       options=["Moussa (Moïse)", "Ibrahim", "Yusuf", "Dawud"], reponse=0),
  dict(q="Que reproche essentiellement Shu'ayb à son peuple, au-delà des questions commerciales ?",
       options=["L'idolâtrie et l'injustice sociale", "Le refus de l'agriculture", "L'absence de guerriers", "Le nomadisme excessif"], reponse=0),

  # Musa (Moïse)
  dict(q="Dans quel palais le prophète Musa aurait-il été élevé, selon la tradition ?",
       options=["Le palais de Pharaon", "Le palais de Ninive", "Le palais de Saba", "Le palais de Babylone"], reponse=0),
  dict(q="En quoi se transforme le bâton de Musa lors de plusieurs récits coraniques ?",
       options=["Un serpent", "Un oiseau", "Une épée", "Un arbre"], reponse=0),
  dict(q="Quelle mer Musa aurait-il traversée miraculeusement en fuyant l'armée de Pharaon ?",
       options=["La mer Rouge", "La mer Morte", "La mer Méditerranée", "Le Nil"], reponse=0),
  dict(q="Sur quel mont Musa reçoit-il la révélation, selon la tradition ?",
       options=["Le mont Sinaï", "Le mont Sinaï et le mont Hira", "Le mont Sinaï uniquement (Tur Sina)", "Le mont Arafat"], reponse=2),

  # Harun (Aaron)
  dict(q="Quel lien de parenté unit Harun à Musa ?",
       options=["Son frère", "Son fils", "Son cousin", "Son beau-père"], reponse=0),
  dict(q="Pour quelle raison Musa demande-t-il à Dieu que Harun l'accompagne dans sa mission ?",
       options=["Harun est plus éloquent que lui", "Harun est plus riche", "Harun connaît mieux l'Égypte", "Harun est plus jeune"], reponse=0),
  dict(q="Quel rôle Harun joue-t-il principalement aux côtés de Musa face à Pharaon ?",
       options=["Porte-parole et soutien", "Chef militaire", "Trésorier", "Espion"], reponse=0),
  dict(q="Harun et Musa sont-ils tous deux envoyés vers Pharaon, selon le récit coranique ?",
       options=["Oui, ensemble", "Non, seul Musa y va", "Non, seul Harun y va", "Ils y vont à des époques différentes"], reponse=0),

  # Dhul-Kifl
  dict(q="Pour quelle qualité le prophète Dhul-Kifl est-il mentionné dans le Coran ?",
       options=["Sa patience et sa droiture", "Sa richesse", "Ses conquêtes militaires", "Son savoir scientifique"], reponse=0),
  dict(q="Le Coran donne-t-il de nombreux détails narratifs sur la vie de Dhul-Kifl ?",
       options=["Non, il est mentionné brièvement", "Oui, un récit très détaillé lui est consacré", "Oui, une sourate entière lui est dédiée", "Il n'est jamais mentionné dans le Coran"], reponse=0),
  dict(q="Dhul-Kifl est cité dans le Coran aux côtés de quels autres prophètes patients ?",
       options=["Ismail et Idris", "Moussa et Haroun", "Ibrahim et Loth", "Dawud et Souleiman"], reponse=0),
  dict(q="Que signifie approximativement le nom « Dhul-Kifl » ?",
       options=["« Celui qui garantit / qui a une double part »", "« Le voyageur »", "« Le sage ancien »", "« Le messager du désert »"], reponse=0),

  # Dawud (David)
  dict(q="Quel livre sacré aurait été révélé au prophète Dawud, selon la tradition islamique ?",
       options=["Le Zabur (les Psaumes)", "La Torah", "Le Coran", "L'Évangile"], reponse=0),
  dict(q="Quel matériau Dieu aurait-il rendu malléable entre les mains de Dawud, selon le Coran ?",
       options=["Le fer", "L'or", "Le verre", "Le bronze"], reponse=0),
  dict(q="Quel adversaire légendaire Dawud aurait-il vaincu jeune, avant de devenir roi et prophète ?",
       options=["Jalut (Goliath)", "Pharaon", "Nabuchodonosor", "Haman"], reponse=0),
  dict(q="Pour quelle qualité vocale et de jugement Dawud est-il également connu dans la tradition ?",
       options=["Sa belle voix et sa sagesse dans les jugements", "Sa force physique uniquement", "Son silence perpétuel", "Son incapacité à parler en public"], reponse=0),

  # Sulayman (Solomon)
  dict(q="Quel lien de parenté unit Sulayman à Dawud ?",
       options=["Il est son fils", "Il est son frère", "Il est son petit-fils", "Aucun lien"], reponse=0),
  dict(q="Quels éléments Sulayman aurait-il pu commander, selon le récit coranique ?",
       options=["Le vent et certains esprits (jinns)", "La pluie uniquement", "Le feu uniquement", "La mer uniquement"], reponse=0),
  dict(q="Quel petit animal engage un dialogue célèbre avec Sulayman dans le récit coranique de la vallée des fourmis ?",
       options=["Une fourmi", "Une abeille", "Un scarabée", "Une sauterelle"], reponse=0),
  dict(q="Quelle reine étrangère est associée au récit de Sulayman dans le Coran ?",
       options=["La reine de Saba (Bilqis)", "La reine de Ninive", "La reine d'Égypte", "La reine de Babylone"], reponse=0),

  # Ilyas (Élie)
  dict(q="Contre quelle pratique religieuse de son peuple le prophète Ilyas s'élève-t-il principalement ?",
       options=["Le culte de l'idole Ba'al", "L'usure commerciale", "La polygamie", "Le nomadisme"], reponse=0),
  dict(q="Ilyas est traditionnellement associé à une région correspondant à quelle zone géographique actuelle ?",
       options=["La région du Levant (actuel Israël/Liban)", "La péninsule Arabique", "L'Égypte", "La Perse"], reponse=0),
  dict(q="Le Coran mentionne-t-il Ilyas comme faisant partie des « vertueux » (salihin) ?",
       options=["Oui", "Non, il n'est pas cité", "Non, il est cité comme un exemple négatif", "Le Coran ne le nomme jamais explicitement"], reponse=0),
  dict(q="Quel type de message le prophète Ilyas délivre-t-il essentiellement à son peuple ?",
       options=["Un appel à l'adoration du seul Dieu", "Un code de lois commerciales", "Un traité de paix", "Un calendrier agricole"], reponse=0),

  # Al-Yasa (Élisée)
  dict(q="Quel prophète est traditionnellement présenté comme le successeur d'Ilyas ?",
       options=["Al-Yasa", "Dawud", "Sulayman", "Yunus"], reponse=0),
  dict(q="Comment le Coran qualifie-t-il globalement Al-Yasa, parmi une liste de prophètes ?",
       options=["Un homme parmi les meilleurs (al-akhyar)", "Un roi puissant", "Un guerrier redouté", "Un marchand prospère"], reponse=0),
  dict(q="Le Coran développe-t-il un long récit narratif sur Al-Yasa, comme il le fait pour Yusuf ?",
       options=["Non, il est mentionné brièvement dans des listes de prophètes", "Oui, une sourate entière lui est consacrée", "Oui, plusieurs chapitres détaillent sa vie", "Non, il n'apparaît jamais dans le Coran"], reponse=0),
  dict(q="Al-Yasa est cité dans le Coran aux côtés de quels autres prophètes, dans une liste commune ?",
       options=["Ismail, Idris et Dhul-Kifl", "Ibrahim et Loth uniquement", "Moussa et Haroun uniquement", "Dawud et Sulayman uniquement"], reponse=0),

  # Yunus (Jonas)
  dict(q="Quel prophète est englouti par un grand poisson avant d'être sauvé ?",
       options=["Yunus (Jonas)", "Ayyub (Job)", "Zakariya (Zacharie)", "Al-Yasa (Élisée)"], reponse=0),
  dict(q="Pourquoi Yunus se retrouve-t-il en mer avant d'être avalé par le poisson, selon le récit ?",
       options=["Il avait quitté son peuple avec colère, sans attendre l'ordre divin", "Il pêchait pour se nourrir", "Il fuyait une tempête", "Il accompagnait des marchands"], reponse=0),
  dict(q="Quelle invocation Yunus aurait-il prononcée dans l'obscurité du ventre du poisson ?",
       options=["« Il n'y a de dieu que Toi, gloire à Toi, j'ai été parmi les injustes »", "« Seigneur, augmente mon savoir »", "« Seigneur, pardonne à mon peuple »", "« Seigneur, montre-Toi à moi »"], reponse=0),
  dict(q="Vers quelle ville Yunus avait-il été envoyé prêcher ?",
       options=["Ninive", "Babylone", "Sodome", "Damas"], reponse=0,
       explication="Fait rare dans les récits prophétiques : le peuple de Ninive finit par croire et fut épargné du châtiment."),

  # Zakariya (Zacharie)
  dict(q="Pour quelle raison la naissance d'un fils est-elle présentée comme un événement extraordinaire pour Zakariya ?",
       options=["Il était âgé et son épouse stérile", "Il avait fait vœu de ne jamais avoir d'enfant", "Il vivait loin de son épouse", "Aucune raison particulière"], reponse=0),
  dict(q="De qui Zakariya est-il le gardien, selon la tradition islamique ?",
       options=["Maryam (Marie)", "Hajar", "Sarah", "Asiya"], reponse=0),
  dict(q="Quel fils, lui-même prophète, est accordé à Zakariya en réponse à sa prière ?",
       options=["Yahya (Jean)", "Isa (Jésus)", "Yusuf", "Musa"], reponse=0),
  dict(q="Dans quel lieu Zakariya remarque-t-il des provisions inexpliquées auprès de Maryam, épisode qui le pousse à prier pour un enfant ?",
       options=["Le sanctuaire (mihrab) où elle se consacrait à l'adoration", "Un jardin public", "Sa propre maison", "Un marché de Jérusalem"], reponse=0),

  # Yahya (Jean)
  dict(q="Quel lien de parenté unit Yahya à Isa, selon certaines traditions ?",
       options=["Ils seraient cousins", "Ils seraient frères", "Ils seraient père et fils", "Aucun lien"], reponse=0),
  dict(q="Le Coran mentionne-t-il que Yahya reçut la sagesse dès son enfance ?",
       options=["Oui", "Non, seulement à l'âge adulte", "Non, il ne reçut jamais la sagesse", "Le Coran ne mentionne pas Yahya"], reponse=0),
  dict(q="Qui sont les parents du prophète Yahya ?",
       options=["Zakariya et son épouse", "Ibrahim et Sarah", "Imran et son épouse (parents de Maryam)", "Ismail et Hajar"], reponse=0),
  dict(q="Quelle qualité de piété et de retenue est particulièrement associée à Yahya dans la tradition ?",
       options=["Une grande piété et une pureté de vie exemplaires", "Une richesse matérielle importante", "Un talent militaire reconnu", "Un rôle de roi puissant"], reponse=0),

  # Isa (Jésus)
  dict(q="Quel prophète, selon la tradition islamique, est né miraculeusement de Maryam (Marie), sans père ?",
       options=["Yahya (Jean)", "Souleiman (Salomon)", "Issa (Jésus)", "Idris (Hénoch)"], reponse=2,
       explication="Issa (Jésus) est considéré en islam comme un prophète et messager de Dieu, et non comme une divinité."),
  dict(q="Selon la tradition islamique, à quel âge Isa aurait-il parlé pour la première fois, de façon miraculeuse ?",
       options=["Dès le berceau", "À l'âge de 5 ans", "À l'âge de 12 ans", "À l'âge adulte seulement"], reponse=0),
  dict(q="Quel livre sacré Isa aurait-il reçu, selon la tradition islamique ?",
       options=["L'Injil (l'Évangile)", "La Torah", "Le Zabur", "Le Coran"], reponse=0),
  dict(q="Que dit la tradition sunnite majoritaire du destin final d'Isa sur terre ?",
       options=["Il n'a pas été crucifié et a été élevé auprès de Dieu", "Il est mort de vieillesse à Jérusalem", "Il a été crucifié comme le rapportent les Évangiles", "Aucune tradition n'existe à ce sujet"], reponse=0),

  # Muhammad (dernier prophète)
  dict(q="Qui est considéré comme le dernier prophète, le « sceau des prophètes », en islam ?",
       options=["Issa (Jésus)", "Ibrahim (Abraham)", "Muhammad", "Musa (Moïse)"], reponse=2),
  dict(q="Le message de Muhammad est-il considéré, en islam, comme destiné à un seul peuple ou à toute l'humanité ?",
       options=["À toute l'humanité", "Uniquement aux Arabes", "Uniquement aux habitants de La Mecque", "Uniquement à sa propre tribu"], reponse=0),
  dict(q="Quel est le nom du recueil de révélations reçues par Muhammad, considéré comme la parole de Dieu ?",
       options=["Le Coran", "Le Zabur", "La Torah", "L'Injil"], reponse=0),
  dict(q="Pourquoi Muhammad est-il qualifié dans la tradition de « miséricorde pour les mondes » ?",
       options=["Son message est perçu comme une grâce universelle pour toute l'humanité", "Il n'a jamais connu l'adversité", "Il fut un roi puissant et riche", "Il n'a prêché qu'à sa propre famille"], reponse=0),
]

QUIZ = {
  "islam-prophete": dict(
    titre="Islam et son prophète",
    emoji="☾",
    description="Les fondements de l'islam et la vie du prophète Muhammad (tradition sunnite).",
    questions=_ISLAM_PROPHETE),
  "mosquees-celebres": dict(
    titre="Mosquées célèbres",
    emoji="🕌",
    description="Teste tes connaissances sur les mosquées présentées sur ce site.",
    questions=_MOSQUEES_CELEBRES),
  "prophetes-islam": dict(
    titre="Les prophètes de l'islam",
    emoji="✦",
    description="Cent questions sur les prophètes reconnus par la tradition islamique.",
    questions=_PROPHETES_ISLAM),
}
