# -*- coding: utf-8 -*-
"""Questions du quiz Qibla (français) — 3 thèmes, contenu factuel et respectueux."""

QUIZ = {
  "islam-prophete": dict(
    titre="Islam et son prophète",
    emoji="☾",
    description="Les fondements de l'islam et la vie du prophète Muhammad.",
    questions=[
      dict(q="Dans quelle ville le prophète Muhammad est-il né ?",
           options=["La Mecque", "Médine", "Jérusalem", "Damas"], reponse=0,
           explication="Muhammad naît à La Mecque vers 570, dans la tribu des Quraych."),
      dict(q="Comment appelle-t-on la migration du Prophète de La Mecque à Médine ?",
           options=["Le Mi'raj", "L'Hégire (Hijra)", "Le Hajj", "La Sunna"], reponse=1,
           explication="L'Hégire, en 622, marque aussi le point de départ du calendrier musulman."),
      dict(q="Combien l'islam compte-t-il de piliers (obligations fondamentales) ?",
           options=["3", "4", "5", "7"], reponse=2,
           explication="Attestation de foi, prière, aumône, jeûne du Ramadan et pèlerinage."),
      dict(q="Quel est le nom du livre sacré de l'islam ?",
           options=["La Torah", "Le Coran", "Les Évangiles", "Les Psaumes"], reponse=1,
           explication="Le Coran est considéré par les musulmans comme la parole de Dieu révélée à Muhammad."),
      dict(q="Dans quelle grotte le Prophète aurait-il reçu sa première révélation ?",
           options=["La grotte de Thawr", "La grotte de Hira", "La grotte des Sept Dormants", "La grotte de Qumrân"], reponse=1,
           explication="La grotte de Hira se trouve sur le mont Jabal al-Nour, près de La Mecque."),
      dict(q="Quel ange est traditionnellement associé à la transmission de la révélation au Prophète ?",
           options=["Mika'il", "Isrāfīl", "Jibril (Gabriel)", "Malik"], reponse=2),
      dict(q="Comment se nomme le pèlerinage annuel à La Mecque, cinquième pilier de l'islam ?",
           options=["La Omra", "Le Hajj", "Le Ramadan", "La Zakat"], reponse=1,
           explication="Le Hajj a lieu une fois par an ; l'Omra, un pèlerinage non obligatoire, peut se faire toute l'année."),
      dict(q="Quel est le nom de la première épouse du Prophète, la première à avoir cru en son message ?",
           options=["Aïcha", "Fatima", "Khadija", "Zaynab"], reponse=2),
      dict(q="Pendant quel mois du calendrier musulman les musulmans jeûnent-ils ?",
           options=["Muharram", "Chaabane", "Ramadan", "Dhou al-Hijja"], reponse=2),
      dict(q="Vers quelle ville les musulmans se tournent-ils pendant la prière ?",
           options=["Médine", "Jérusalem", "Damas", "La Mecque"], reponse=3,
           explication="Cette direction s'appelle la qibla, qui a donné son nom à ce site."),
    ]),
  "mosquees-celebres": dict(
    titre="Mosquées célèbres",
    emoji="🕌",
    description="Teste tes connaissances sur les 20 mosquées présentées sur ce site.",
    questions=[
      dict(q="Quelle mosquée entoure la Kaaba ?",
           options=["Masjid an-Nabawi", "Masjid al-Haram", "Al-Azhar", "Badshahi"], reponse=1),
      dict(q="Dans quelle ville se trouve la Mosquée bleue (Sultan Ahmed) ?",
           options=["Le Caire", "Marrakech", "Istanbul", "Lahore"], reponse=2),
      dict(q="Qui est l'architecte de la mosquée Hassan II à Casablanca ?",
           options=["Michel Pinseau", "Sinan", "Zaha Hadid", "Fazlur Rahman Khan"], reponse=0,
           explication="Michel Pinseau, architecte français, a dirigé sa construction achevée en 1993."),
      dict(q="En quel matériau principal est construite la Grande Mosquée de Djenné, au Mali ?",
           options=["Marbre blanc", "Grès rose", "Banco (terre crue)", "Brique cuite"], reponse=2,
           explication="C'est le plus grand édifice en terre crue au monde ; il est ré-enduit chaque année."),
      dict(q="Quelle mosquée d'Iran est surnommée « mosquée rose » pour ses vitraux colorés ?",
           options=["Cheikh Lotfollah", "Nasir al-Mulk", "Jama Masjid", "Faisal"], reponse=1),
      dict(q="Quelle mosquée abrite le tombeau du prophète Muhammad ?",
           options=["Masjid al-Haram", "Al-Aqsa", "Masjid an-Nabawi", "Ibn Touloun"], reponse=2,
           explication="Elle se trouve à Médine, en Arabie Saoudite."),
      dict(q="Quel est le nom du minaret emblématique de Marrakech, qui a inspiré la Giralda de Séville ?",
           options=["La Koutoubia", "Le minaret d'Al-Azhar", "La tour de Hassan", "Le minaret de Kairouan"], reponse=0),
      dict(q="Dans quel pays se trouve la mosquée Cheikh Zayed ?",
           options=["Qatar", "Arabie Saoudite", "Émirats arabes unis", "Bahreïn"], reponse=2,
           explication="Elle se trouve à Abou Dabi et compte parmi les plus grandes mosquées du monde."),
      dict(q="Quelle mosquée espagnole a été transformée en cathédrale après la Reconquista ?",
           options=["La mosquée de l'Alhambra", "La mosquée-cathédrale de Cordoue", "La Giralda de Séville", "La Koutoubia"], reponse=1),
      dict(q="Quelle est la particularité de la Grande Mosquée de Xi'an, en Chine ?",
           options=["Elle est entièrement souterraine", "Son architecture s'inspire des temples chinois traditionnels", "Elle n'a aucun minaret visible", "Elle est construite sur pilotis"], reponse=1,
           explication="Toitures incurvées, cours successives et pavillons de bois : son plan suit les codes de l'architecture chinoise classique."),
    ]),
  "prophetes-islam": dict(
    titre="Les prophètes de l'islam",
    emoji="✦",
    description="Dix questions sur les prophètes reconnus par la tradition islamique.",
    questions=[
      dict(q="Quel est, selon la tradition islamique, le premier homme et premier prophète ?",
           options=["Idris", "Adam", "Noé", "Seth"], reponse=1),
      dict(q="Quel prophète aurait survécu à un grand déluge grâce à une arche ?",
           options=["Houd", "Salih", "Nuh (Noé)", "Loth"], reponse=2),
      dict(q="Quel prophète est associé à la (re)construction de la Kaaba avec son fils Ismaël ?",
           options=["Ibrahim (Abraham)", "Ishaq (Isaac)", "Yaqub (Jacob)", "Dawud (David)"], reponse=0,
           explication="Selon le Coran, Abraham et son fils Ismaël élèvent les fondations de la Kaaba à La Mecque."),
      dict(q="Quel prophète reçut les Tables de la Loi sur le mont Sinaï ?",
           options=["Haroun (Aaron)", "Musa (Moïse)", "Yusha (Josué)", "Dawud (David)"], reponse=1),
      dict(q="Quel prophète est englouti par un grand poisson avant d'être sauvé, dans le récit associé à Ninive ?",
           options=["Yunus (Jonas)", "Ayyub (Job)", "Zakariya (Zacharie)", "Al-Yasa (Élisée)"], reponse=0),
      dict(q="Quel prophète est réputé pour sa patience exemplaire face à la maladie et l'épreuve ?",
           options=["Chou'aib", "Ayyub (Job)", "Ilyas (Élie)", "Yahya (Jean)"], reponse=1),
      dict(q="Quel prophète, selon la tradition islamique, est né miraculeusement de Marie (Maryam) ?",
           options=["Yahya (Jean)", "Souleiman (Salomon)", "Issa (Jésus)", "Idris (Hénoch)"], reponse=2,
           explication="Issa (Jésus) est considéré en islam comme un prophète et messager de Dieu, non comme une divinité."),
      dict(q="Quel prophète est au cœur du récit où il est vendu par ses frères avant de devenir vizir en Égypte ?",
           options=["Yusuf (Joseph)", "Ismail (Ismaël)", "Haroun (Aaron)", "Dawud (David)"], reponse=0),
      dict(q="Qui est considéré comme le dernier prophète, le « sceau des prophètes », en islam ?",
           options=["Issa (Jésus)", "Ibrahim (Abraham)", "Muhammad", "Musa (Moïse)"], reponse=2),
      dict(q="Quel prophète est traditionnellement associé à une grande sagesse et au contrôle des vents et des animaux ?",
           options=["Souleiman (Salomon)", "Dawud (David)", "Zakariya (Zacharie)", "Houd"], reponse=0,
           explication="Le règne de Salomon (Souleiman) est décrit dans le Coran comme un âge de sagesse et de prodiges."),
    ]),
}
